/*
Copyright 2026 Zero Day AI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package main

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	astchecks "github.com/zeroroot-ai/ast-checks"
)

// internalScopeDirs returns every first-level directory under repoRoot/internal/.
// Used to widen the walker scope to every gibson internal package — per
// slice 3.2 of the production-readiness epic. Adding a new internal/
// package automatically brings it into scope; no manual list to maintain.
func internalScopeDirs(t *testing.T, repoRoot string) []string {
	t.Helper()
	internalRoot := filepath.Join(repoRoot, "internal")
	entries, err := os.ReadDir(internalRoot)
	if err != nil {
		t.Fatalf("read internal/: %v", err)
	}
	var dirs []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dirs = append(dirs, filepath.Join(internalRoot, e.Name()))
	}
	sort.Strings(dirs)
	return dirs
}

// TestNoGracefulNilInRequestPaths walks every request-path Go file in
// the daemon and flags any `if X == nil { return ... }` pattern where
// the body silently returns success (return nil / return true, nil /
// return false, nil / return nil, nil) without recording an error.
//
// Why: the "one-code-path" PRD (deploy#186, codified in [[0003]]) forbids
// degraded-mode branches in request paths. Every dependency must be
// validated at startup (in cmd/gibson/main.go) — once the daemon is
// running, every callsite assumes deps are non-nil. A silent skip on a
// missing dep produces a user-visible "Failed to load" with no log trail.
//
// Implementation: this test is a thin caller of the shared ast-checks
// harness (zeroroot-ai/ast-checks). The harness owns the walking, the
// pattern matcher, and the allowlist-filtering machinery. Per slice 3.1
// of the production-readiness epic, this is the gibson refactor proof
// of the harness design.
//
// Scope: files under `internal/{daemon,datapool,harness,mission,state,authz}`.
// The widening to all 48 gibson internal/ dirs is slice 3.2's work
// (board #16) — narrowing the matcher to receiver-field shape lands in
// the same slice. This file ships the broad-mode matcher pending that
// work, preserving today's allowlist exactly.
func TestNoGracefulNilInRequestPaths(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	// thisFile lives at cmd/gibson/no_graceful_nil_test.go; repo root
	// is two levels up.
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")

	// Fixture subtest: assert walker correctness against known fixtures.
	t.Run("fixtures", func(t *testing.T) {
		fixturesRoot := filepath.Join(filepath.Dir(thisFile), "testdata", "scope")
		// Narrowed pattern: receiver-field shape only. Per slice 3.2.
		matchers := []astchecks.Matcher{astchecks.NewNilGuard(true)}
		// Two known-illegal fixtures, no allowlist for fixtures.
		opts := astchecks.WalkOpts{
			ScopeDirs:     []string{filepath.Join(fixturesRoot, "internal")},
			RepoRoot:      fixturesRoot,
			Matchers:      matchers,
			SkipTestFiles: true,
			SkipGenerated: true,
		}
		findings, err := astchecks.Walk(opts)
		if err != nil {
			t.Fatalf("Walk fixtures: %v", err)
		}
		if want := 2; len(findings) != want {
			t.Errorf("fixture scan: got %d findings, want %d:\n%s",
				len(findings), want, astchecks.RenderFindings(findings))
		}
		for _, f := range findings {
			if !strings.Contains(f.Coord, "illegal_silent_skip") {
				t.Errorf("fixture scan: unexpected finding (should only flag illegal_*): %s", f)
			}
		}
	})

	// Existing-debt allowlist. Each entry is a "<file> :: <snippet>" content key
	// (relative path from repo root) where the request-path graceful-nil
	// branch is known but has not yet been ripped out (or is a defensive
	// guard the walker over-flags). New findings (not on this list) fail
	// the test loud.
	//
	// Categories (each entry tagged):
	//
	//   - astchecks.CategoryDefensiveGuard: nil-check on a parameter/local
	//     that is a value-shape guard, not a dependency. E.g. converter
	//     helpers returning nil when input is nil; observability span
	//     checks where a nil span legitimately means "no tracing active".
	//     Walker over-flags — the anti-pattern only applies to *injected
	//     dependencies*. Slice 3.2 narrows the matcher to receiver-field
	//     shape and shrinks this list.
	//
	//   - astchecks.CategoryLegacyOptional: a dependency that today is
	//     genuinely wired conditionally, and reasserting it as always-on
	//     is blocked on a follow-up slice. Each reason names the slice.
	//
	//   - astchecks.CategoryReceiverNilGuard: nil-check on the method
	//     receiver itself (`if s == nil`). Used as a defensive shim for
	//     tests that pass a zero-value server; not the dependency
	//     anti-pattern.
	//
	// Generated by the first run of this test against main on 2026-05-17
	// after the gibson slices for one-code-path/195 (#111),
	// one-code-path/205 (#112), one-code-path/207 (#113) merged.
	requestPathAllowlist := astchecks.Allowlist{
		// CONTENT-KEYED (ast-checks v0.2.0, AllowlistByContent below). Each key is
		// "<relpath> :: <snippet>" — the guard text, NOT a line number — so line
		// shifts (license headers, added imports/comments) can never red this gate
		// (the brittleness that hit it in gibson#1025/#1043/#1044/#1041). Identical
		// guards in one file share one key (acceptable coarsening for a tolerated
		// list). Migrated from the prior 134 line-keyed entries; dedupes to 60.
		"internal/engine/finding/export/sarif_exporter.go :: if f.Metadata == nil { ... }":                                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},
		"internal/engine/finding/types.go :: if f.Metadata == nil { ... }":                                                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},
		"internal/engine/graphrag/graph/neo4j.go :: if c.driver == nil { ... }":                                              astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver optional in non-graphrag deployments (mirrors daemon/grpc.go:2504)"},
		"internal/engine/harness/callback_service.go :: if data == nil || s.tracerProvider == nil { ... }":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite data/tracerProvider nil-guard for observability"},
		"internal/engine/harness/callback_service.go :: if s.eventBus == nil { ... }":                                        astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "event bus optional; remove with eventbus-required slice"},
		"internal/engine/harness/compliance_rule_registry.go :: if r.loader == nil { ... }":                                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "rule loader optional in unit-test boot path"},
		"internal/engine/harness/filter.go :: if finding.CVSS == nil || finding.CVSS.Score < *f.MinCVSS { ... }":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil CVSS means no min-score match"},
		"internal/engine/harness/filter.go :: if finding.CVSS == nil || finding.CVSS.Score > *f.MaxCVSS { ... }":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil CVSS means no max-score match"},
		"internal/engine/harness/filter.go :: if finding.TargetID == nil || *finding.TargetID != *f.TargetID { ... }":        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil target ID means no filter match"},
		"internal/engine/harness/implementation.go :: if h.nodeSlotOverrides == nil { ... }":                                 astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "per-node slot-override map may be unset; nil → no override (documented fall-through, gibson#539)"},
		"internal/engine/harness/schema_convert.go :: if s.Type == \"\" && len(s.Properties) == 0 && s.Items == nil { ... }": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "empty schema shape means no conversion"},
		"internal/engine/llm/config.go :: if m.Features == nil { ... }":                                                      astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Features field on llm config, legitimately nil-able"},
		"internal/engine/llm/config.go :: if p.Models == nil { ... }":                                                        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Models field on llm config, legitimately nil-able"},
		"internal/engine/llm/pricing.go :: if other == nil || other.Pricing == nil { ... }":                                  astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite nil-check on other-side comparison"},
		"internal/engine/llm/pricing.go :: if p.Pricing == nil { ... }":                                                      astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Pricing field, legitimately nil-able when provider has no pricing config"},
		"internal/engine/llm/ratelimit.go :: if p.requestLimit == nil { ... }":                                               astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "requestLimit nil means unlimited (legitimate semantic)"},
		"internal/engine/llm/ratelimit.go :: if p.tokenLimit == nil || usage.TotalTokens <= 0 { ... }":                       astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "tokenLimit nil means unlimited (legitimate semantic)"},
		"internal/engine/memory/vector/embedded.go :: if record.Metadata == nil { ... }":                                     astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Metadata field on vector record, legitimately nil-able"},
		"internal/engine/mission/definitionutil/definitionutil.go :: if def == nil || def.Nodes == nil { ... }":              astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil definition means empty traverse"},
		"internal/engine/mission/state.go :: if ms.Definition == nil { ... }":                                                astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil Definition means no-op"},
		"internal/engine/state/client.go :: if c.client == nil { ... }":                                                      astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "nil-client shim for tests"},
		"internal/infra/datapool/conn_ops_mission.go :: if m.rdb == nil { ... }":                                             astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "redis client nil-guard predates pool-required hardening"},
		"internal/infra/datapool/recovery_hook.go :: if conn.Redis == nil { ... }":                                           astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Redis nil guard in recovery hook; conn.Redis nil means Redis not configured for this tenant — silent return is correct"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.agentExecutionsTotal == nil { ... }":               astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.authzDecisionsTotal == nil { ... }":                astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.classificationsTotal == nil { ... }":               astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.componentAuthzFailOpenTotal == nil { ... }":        astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.componentAuthzTotal == nil { ... }":                astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.decisionsTotal == nil { ... }":                     astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.fgaUnavailableTotal == nil { ... }":                astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.findingsTotal == nil { ... }":                      astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.graphOpsTotal == nil { ... }":                      astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.llmRequestsTotal == nil { ... }":                   astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim — metrics methods callable when metrics disabled"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.memoryOpsTotal == nil { ... }":                     astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.missionsTotal == nil { ... }":                      astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.toolCallsTotal == nil { ... }":                     astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/observability/otel_metrics.go :: if r == nil || r.workTTLExpiredTotal == nil { ... }":                astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/infra/secrets/vault/provider.go :: if secret == nil || secret.Data == nil { ... }":                         astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Vault KV LIST response-shape guard; nil/nil-Data means no secrets exist for the tenant path — empty list is the correct result"},
		"internal/infra/types/target.go :: if t.Capabilities == nil { ... }":                                                 astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Capabilities field on Target, legitimately nil-able"},
		"internal/platform/budget/enforcer.go :: if e.teams == nil { ... }":                                                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "teams dep optional in budget enforcer; reassert via budget-required follow-up"},
		"internal/platform/reservednames/provider.go :: if p.watcher == nil { ... }":                                         astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "watcher nil guard in watchLoop; nil watcher means no fsnotify subscription (e.g. in-memory mode or test)"},
		"internal/platform/secrets/jwtsource/spire.go :: if s == nil || s.src == nil { ... }":                                astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim for SPIRE JWT source"},
		"internal/server/admin/invitation_store.go :: if s == nil || s.db == nil { ... }":                                    astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver/nil-db shim in ListPending; store is always wired with a db in production (nil-safe for test injection)"},
		"internal/server/admin/secrets_plugin_associations.go :: if f.authorizer == nil { ... }":                             astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "FGASecretsPluginAssociations nil-authorizer shim; authorizer is always non-nil in production (nil-safe for test injection)"},
		"internal/server/daemon/api/mission_handlers.go :: if s.authorizer == nil { ... }":                                   astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-check in callerIsPlatformOperator; predates noopAuthorizer deletion"},
		"internal/server/daemon/api/server_audit.go :: if s.authorizer == nil { ... }":                                       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-check predates noopAuthorizer deletion"},
		"internal/server/daemon/api/server_entitlements.go :: if s.platformDB == nil { ... }":                                astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.platformDB nil-guard in deleteSharedConnectorManifest; platformDB optional in non-platform deployments (mirrors :374)"},
		"internal/server/daemon/api/server_provider_config.go :: if s.auditLogger == nil { ... }":                            astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "audit logger conditionally wired"},
		"internal/server/daemon/api/server_provider_exec.go :: if s.budgetEnforcer == nil { ... }":                           astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "budget enforcer conditionally wired; remove with budget-required slice"},
		"internal/server/daemon/api/server_revoke_sessions.go :: if s.authorizer == nil { ... }":                             astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-check in canRevokeSessions; fail-closed (only self permitted) when FGA unwired — predates noopAuthorizer deletion"},
		"internal/server/daemon/api/typed_value_helpers.go :: if v.ArrayValue == nil { ... }":                                astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "typed-value converter, nil input → nil output"},
		"internal/server/daemon/graph_projector.go :: if p.reg == nil || p.writer == nil { ... }":                            astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite reg/writer nil-guard in background projection loop (ADR-0007); both wired by NewGraphProjector in production — nil-safe for zero-value test construction"},
		"internal/server/daemon/grpc.go :: if d.pool == nil { ... }":                                                         astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "pool nil-guard in populateCheckpointPayload; pool-required follow-up (one-code-path#195)"},
		"internal/server/daemon/grpc.go :: if err != nil || m == nil || m.Checkpoint == nil { ... }":                         astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "compound nil-check on mission store Get result + Checkpoint proto field in populateCheckpointPayload"},
		"internal/server/daemon/grpc.go :: if neoConn.Neo4j == nil { ... }":                                                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j connection nil-guard; Neo4j not configured for this tenant — skip silently"},
		"internal/server/daemon/infrastructure.go :: if i.semanticQuerierFactory == nil { ... }":                             astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "semantic querier factory optional in non-graphrag deployments"},
		"internal/server/daemon/log_watcher.go :: if w.file == nil { ... }":                                                  astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "log watcher file handle nil-guard during teardown"},
		"internal/server/daemon/otel_adapter.go :: if d.infrastructure == nil || d.infrastructure.otelStack == nil { ... }":  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "OTel infrastructure conditionally wired"},
		"internal/server/extauthz/fga/check.go :: if resp.Allowed == nil { ... }":                                            astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "OpenFGA *bool Allowed response field, legitimately nil-able; nil maps to fail-closed DENY in CanInvokeTool"},
		"internal/server/extauthz/server/envoy_extauthz.go :: if s.component == nil { ... }":                                 astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "component CG-JWT verifier conditionally wired; nil falls through to unauthenticated DENY (fail-closed) — reassert with component-auth-required follow-up"},
	}

	// Real-code subtest: walk every gibson `internal/` package and fail
	// on any new finding. Slice 3.2 widened the scope from 6 hand-picked
	// dirs to every internal/* subdir; the allowlist absorbs the new
	// surface area inline. `cmd/` and `tests/` remain out of scope
	// (startup wiring + test fixtures are legitimate nil-check sites).
	t.Run("real_code", func(t *testing.T) {
		scopeDirs := internalScopeDirs(t, repoRoot)
		opts := astchecks.WalkOpts{
			ScopeDirs: scopeDirs,
			RepoRoot:  repoRoot,
			// Narrowed pattern: receiver-field shape only.
			// Bare-ident shapes (`if cfg == nil`) are excluded; they're
			// parameter-shape guards, not dependency-shape graceful-nil.
			Matchers:      []astchecks.Matcher{astchecks.NewNilGuard(true)},
			Allowlist:     requestPathAllowlist,
			SkipTestFiles: true,
			SkipGenerated: true,
			// Content-keyed (ast-checks v0.2.0): match the allowlist on the guard
			// itself (file + snippet), not its line number, so unrelated line
			// shifts (license headers, added imports/comments) can't red this gate
			// — the brittleness that hit it repeatedly (gibson#1025/#1043/#1044).
			AllowlistByContent: true,
		}

		// One-shot migration generator (GEN_CK=1): emit the content-keyed
		// allowlist from the current Coord-keyed one. Each finding's Coord is in
		// the (passing) Coord allowlist, so map its Entry to the finding's
		// ContentKey; dedupe (identical guards in a file share one key).

		findings, err := astchecks.Walk(opts)
		if err != nil {
			t.Fatalf("Walk: %v", err)
		}

		if len(findings) > 0 {
			t.Errorf("NEW graceful-nil branches in request paths (forbidden by [[0003]]):\n%s\n\n"+
				"Each is a `if X == nil { return [...] nil }` pattern in a request-path file. The fix is one of:\n"+
				"  (1) Validate the dep at startup (cmd/gibson/main.go) so it can never be nil at request time.\n"+
				"  (2) If this is a legitimate exception, add it to requestPathAllowlist with a category tag + reason.\n",
				astchecks.RenderFindings(findings))
		}

		// Keep the allowlist visible in test output so reviewers see what's
		// tolerated. Matches the pre-refactor format.
		t.Log(astchecks.FormatAllowlistLog(requestPathAllowlist))
	})
}
