/*
Copyright 2026 Zero Day AI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package main

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	astchecks "github.com/zeroroot-ai/ast-checks"
)

// internalScopeDirs returns every first-level directory under repoRoot/internal/.
// Used to widen the walker scope to every gibson internal package — per
// slice 3.2 of the production-readiness epic. Adding a new internal/
// package automatically brings it into scope; no manual list to maintain.
func internalScopeDirs(t *testing.T, repoRoot string) []string {
	t.Helper()
	internalRoot := filepath.Join(repoRoot, "internal")
	entries, err := os.ReadDir(internalRoot)
	if err != nil {
		t.Fatalf("read internal/: %v", err)
	}
	var dirs []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dirs = append(dirs, filepath.Join(internalRoot, e.Name()))
	}
	sort.Strings(dirs)
	return dirs
}

// TestNoGracefulNilInRequestPaths walks every request-path Go file in
// the daemon and flags any `if X == nil { return ... }` pattern where
// the body silently returns success (return nil / return true, nil /
// return false, nil / return nil, nil) without recording an error.
//
// Why: the "one-code-path" PRD (deploy#186, codified in [[0003]]) forbids
// degraded-mode branches in request paths. Every dependency must be
// validated at startup (in cmd/gibson/main.go) — once the daemon is
// running, every callsite assumes deps are non-nil. A silent skip on a
// missing dep produces a user-visible "Failed to load" with no log trail.
//
// Implementation: this test is a thin caller of the shared ast-checks
// harness (zeroroot-ai/ast-checks). The harness owns the walking, the
// pattern matcher, and the allowlist-filtering machinery. Per slice 3.1
// of the production-readiness epic, this is the gibson refactor proof
// of the harness design.
//
// Scope: files under `internal/{daemon,datapool,harness,mission,state,authz}`.
// The widening to all 48 gibson internal/ dirs is slice 3.2's work
// (board #16) — narrowing the matcher to receiver-field shape lands in
// the same slice. This file ships the broad-mode matcher pending that
// work, preserving today's allowlist exactly.
func TestNoGracefulNilInRequestPaths(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	// thisFile lives at cmd/gibson/no_graceful_nil_test.go; repo root
	// is two levels up.
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")

	// Fixture subtest: assert walker correctness against known fixtures.
	t.Run("fixtures", func(t *testing.T) {
		fixturesRoot := filepath.Join(filepath.Dir(thisFile), "testdata", "scope")
		// Narrowed pattern: receiver-field shape only. Per slice 3.2.
		matchers := []astchecks.Matcher{astchecks.NewNilGuard(true)}
		// Two known-illegal fixtures, no allowlist for fixtures.
		opts := astchecks.WalkOpts{
			ScopeDirs:     []string{filepath.Join(fixturesRoot, "internal")},
			RepoRoot:      fixturesRoot,
			Matchers:      matchers,
			SkipTestFiles: true,
			SkipGenerated: true,
		}
		findings, err := astchecks.Walk(opts)
		if err != nil {
			t.Fatalf("Walk fixtures: %v", err)
		}
		if want := 2; len(findings) != want {
			t.Errorf("fixture scan: got %d findings, want %d:\n%s",
				len(findings), want, astchecks.RenderFindings(findings))
		}
		for _, f := range findings {
			if !strings.Contains(f.Coord, "illegal_silent_skip") {
				t.Errorf("fixture scan: unexpected finding (should only flag illegal_*): %s", f)
			}
		}
	})

	// Existing-debt allowlist. Each entry is a "<file>:<line>" coordinate
	// (relative path from repo root) where the request-path graceful-nil
	// branch is known but has not yet been ripped out (or is a defensive
	// guard the walker over-flags). New findings (not on this list) fail
	// the test loud.
	//
	// Categories (each entry tagged):
	//
	//   - astchecks.CategoryDefensiveGuard: nil-check on a parameter/local
	//     that is a value-shape guard, not a dependency. E.g. converter
	//     helpers returning nil when input is nil; observability span
	//     checks where a nil span legitimately means "no tracing active".
	//     Walker over-flags — the anti-pattern only applies to *injected
	//     dependencies*. Slice 3.2 narrows the matcher to receiver-field
	//     shape and shrinks this list.
	//
	//   - astchecks.CategoryLegacyOptional: a dependency that today is
	//     genuinely wired conditionally, and reasserting it as always-on
	//     is blocked on a follow-up slice. Each reason names the slice.
	//
	//   - astchecks.CategoryReceiverNilGuard: nil-check on the method
	//     receiver itself (`if s == nil`). Used as a defensive shim for
	//     tests that pass a zero-value server; not the dependency
	//     anti-pattern.
	//
	// Generated by the first run of this test against main on 2026-05-17
	// after the gibson slices for one-code-path/195 (#111),
	// one-code-path/205 (#112), one-code-path/207 (#113) merged.
	requestPathAllowlist := astchecks.Allowlist{
		// internal/admin — TenantAdminServer
		"internal/admin/tenant_admin.go:337": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-guard in ListMembers; reassert when authorizer-required follow-up lands"},

		// internal/daemon/api — handlers + helpers
		"internal/daemon/api/mission_handlers.go:329":          astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-check in requireMissionViewer; predates noopAuthorizer deletion"},
		"internal/daemon/api/mission_handlers.go:406":          astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-check in callerIsPlatformOperator; predates noopAuthorizer deletion"},
		"internal/daemon/api/mission_handlers.go:979":          astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "err check followed by payload nil-check (caller-shape, not dep)"},
		"internal/daemon/api/server_audit.go:218":              astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "s.authorizer nil-check predates noopAuthorizer deletion"},
		"internal/daemon/api/server_budget.go:88":              astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "nil-receiver shim for budget API helper"},
		"internal/daemon/api/server_budget.go:122":             astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "nil-receiver shim for budget API helper"},
		"internal/daemon/api/server_entitlements_audit.go:122": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "entitlements audit emitter conditionally wired"},
		"internal/daemon/api/server_entitlements_audit.go:160": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "entitlements audit emitter conditionally wired"},
		"internal/daemon/api/server.go:1526":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "response helper, nil data means empty response"},
		"internal/daemon/api/server.go:1551":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "response helper, nil data means empty response"},
		"internal/daemon/api/server.go:1578":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "response helper, nil data means empty response"},
		"internal/daemon/api/server_provider_config.go:75":     astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil cfg means no provider overlay"},
		"internal/daemon/api/server_provider_config.go:150":    astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "audit logger conditionally wired"},
		"internal/daemon/api/server_provider_exec.go:110":      astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "budget enforcer conditionally wired; remove with budget-required slice"},
		"internal/daemon/api/typed_value_helpers.go:25":        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "typed-value converter, nil input → nil output"},
		"internal/daemon/api/typed_value_helpers.go:77":        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "typed-value converter, nil input → nil output"},
		"internal/daemon/api/typed_value_helpers.go:89":        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "typed-value converter, nil input → nil output"},
		"internal/daemon/api/typed_value_helpers.go:106":       astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "typed-value converter, nil input → nil output"},

		// internal/daemon — core
		"internal/daemon/compliance_sink_adapter.go:32": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "compliance sink registered conditionally; remove with compliance-required slice"},
		"internal/daemon/daemon.go:481":                 astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "SPIFFE wiring optional in non-SPIFFE deployments; reassert when SPIFFE-everywhere lands"},
		"internal/daemon/grpc.go:1905":                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "pool nil-guard; pool-required follow-up (one-code-path#195)"},
		"internal/daemon/grpc.go:2002":                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "pool nil-guard; pool-required follow-up (one-code-path#195)"},
		"internal/daemon/grpc.go:2100":                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "pool nil-guard in populateCheckpointPayload; pool-required follow-up"},
		"internal/daemon/grpc.go:2110":                  astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "compound nil-check on mission store Get result + Checkpoint proto field in populateCheckpointPayload"},
		"internal/daemon/grpc.go:2405":                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "pool nil-guard; pool-required follow-up (one-code-path#195)"},
		"internal/daemon/grpc.go:2573":                  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j connection nil-guard; Neo4j not configured for this tenant — skip silently"},
		"internal/daemon/graph_bootstrap.go:411":        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "tenant-value lookup helper, nil means no scoping"},
		"internal/daemon/infrastructure.go:95":          astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "semantic querier factory optional in non-graphrag deployments"},
		"internal/daemon/log_watcher.go:197":            astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "log watcher file handle nil-guard during teardown"},
		"internal/daemon/manifest_loader.go:34":         astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "manifest helper, nil component means no-op"},
		"internal/daemon/otel_adapter.go:65":            astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "OTel infrastructure conditionally wired"},
		"internal/daemon/otel_adapter.go:105":           astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "OTel infrastructure conditionally wired"},
		"internal/daemon/otel_adapter.go:125":           astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "OTel infrastructure conditionally wired"},
		"internal/daemon/otel_adapter.go:146":           astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "OTel infrastructure conditionally wired"},
		"internal/daemon/otel_adapter.go:169":           astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "OTel infrastructure conditionally wired"},

		// internal/datapool
		"internal/datapool/conn_ops_finding.go:62":  astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "goredis.Nil sentinel + nil result handling"},
		"internal/datapool/conn_ops_mission.go:159": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "goredis.Nil sentinel + nil result handling"},
		"internal/datapool/conn_ops_mission.go:376": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "redis client nil-guard predates pool-required hardening"},
		"internal/datapool/recovery_hook.go:72":     astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Redis nil guard in recovery hook; conn.Redis nil means Redis not configured for this tenant — silent return is correct"},

		// internal/harness — middleware + adapters
		"internal/harness/callback_service.go:2366":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite data/tracerProvider nil-guard for observability"},
		"internal/harness/callback_service.go:2808":             astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "event bus optional; remove with eventbus-required slice"},
		"internal/harness/callback_service.go:3045":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "typed-value converter"},
		"internal/harness/callback_service.go:3230":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/callback_service.go:3259":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/callback_service.go:3532":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/callback_service.go:3792":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/callback_service.go:3864":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/callback_service.go:4018":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/compliance_evaluator.go:37":           astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil signature input means no eval"},
		"internal/harness/compliance_middleware_methods.go:101": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil resp passthrough in middleware"},
		"internal/harness/compliance_rule_registry.go:79":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "rule loader optional in unit-test boot path"},
		"internal/harness/filter.go:77":                         astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil target ID means no filter match"},
		"internal/harness/filter.go:110":                        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil CVSS means no min-score match"},
		"internal/harness/filter.go:117":                        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil CVSS means no max-score match"},
		"internal/harness/graphrag_query_bridge.go:1095":        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil props passthrough"},
		"internal/harness/implementation.go:2426":               astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/implementation.go:3046":               astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},
		"internal/harness/middleware/events.go:170":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil result means middleware drops event"},
		"internal/harness/middleware/tracing.go:162":            astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil response passthrough"},
		"internal/harness/middleware_harness.go:53":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil result passthrough"},
		"internal/harness/middleware_harness.go:73":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil result passthrough"},
		"internal/harness/middleware_harness.go:93":             astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil result passthrough"},
		"internal/harness/middleware_harness.go:126":            astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil result passthrough"},
		"internal/harness/mission_context_provider.go:259":      astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil PreviousRunID means first run"},
		"internal/harness/relationship_resolver.go:288":         astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil relationship means no-op"},
		"internal/harness/schema_convert.go:14":                 astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "empty schema shape means no conversion"},
		"internal/harness/structured.go:1216":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil-input → nil-output converter"},

		// internal/mission
		"internal/mission/checkpoint.go:112":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil memory means empty checkpoint"},
		"internal/mission/checkpoint_manager.go:173":           astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil checkpoint means no-op"},
		"internal/mission/constraints.go:91":                   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil constraints/metrics means no eval"},
		"internal/mission/constraints.go:199":                  astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil constraints means no validation (sdk#64 M2 canonical_constraints helper)"},
		"internal/mission/controller.go:239":                   astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim for controller"},
		"internal/mission/controller_checkpoint.go:533":        astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "event bus optional in non-streaming deployments"},
		"internal/mission/controller_checkpoint.go:559":        astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "event bus optional in non-streaming deployments"},
		"internal/mission/definitionutil/definitionutil.go:18": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil definition means empty traverse"},
		"internal/mission/state.go:504":                        astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "nil Definition means no-op"},

		// internal/state
		"internal/state/client.go:229":      astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "nil-client shim for tests"},
		"internal/state/tenant_names.go:83": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite nil-client / empty-tenant guard"},
		"internal/state/tenant_names.go:93": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite nil-client / empty-tenant guard"},

		// --- Slice 3.2: newly-in-scope dirs (the other 43 internal/* dirs) ---
		// Triaged on first widened-scan run. Conservative defaults: DEFENSIVE-GUARD
		// for proto/value-shape fields that legitimately accept nil; LEGACY-OPTIONAL
		// for receiver-field deps that should be reasserted as always-on; RECEIVER-NIL-GUARD
		// for composite nil-receiver shims (typically `r == nil || r.X == nil`).

		// internal/budget
		"internal/budget/enforcer.go:191": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "teams dep optional in budget enforcer; reassert via budget-required follow-up"},

		// internal/checkpoint
		"internal/checkpoint/approval.go:235": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Decision.ExpiresAt field, legitimately nil-able"},
		"internal/checkpoint/state.go:401":    astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto WorkingMemory field, legitimately nil-able"},
		"internal/checkpoint/state.go:418":    astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto MissionMemory field, legitimately nil-able"},

		// internal/component
		"internal/component/installer.go:1702": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "manifest.Dependencies value-shape field"},
		"internal/component/installer.go:2393": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "taxonomy registry conditionally wired; reassert with taxonomy-required follow-up"},
		"internal/component/quota.go:110":      astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "quota DB optional; reassert with platform-Postgres-required follow-up"},

		// internal/finding — Metadata proto field is legitimately nil-able
		"internal/finding/export/sarif_exporter.go:414": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},
		"internal/finding/export/sarif_exporter.go:493": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},
		"internal/finding/export/sarif_exporter.go:611": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},
		"internal/finding/types.go:242":                 astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},
		"internal/finding/types.go:257":                 astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Metadata field on Finding, legitimately nil-able"},

		// internal/graphrag — Neo4j driver mirrors the existing daemon/grpc.go:2504 entry
		"internal/graphrag/graph/neo4j.go:103":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver optional in non-graphrag deployments (mirrors daemon/grpc.go:2504)"},
		"internal/graphrag/graph/neo4j.go:118":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:137":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:198":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:254":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:303":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:338":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:390":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/graph/neo4j.go:406":       astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver nil-guard; driver optional in non-graphrag deployments"},
		"internal/graphrag/intelligence/risk.go:450": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "Neo4j driver optional in non-graphrag deployments"},
		"internal/graphrag/provider/local.go:164":    astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "vector store optional in non-graphrag deployments"},
		"internal/graphrag/provider/local.go:227":    astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "vector store nil-guard in getVectorStore; optional in non-graphrag deployments"},

		// internal/llm — pricing/config/ratelimit values that legitimately accept nil
		"internal/llm/config.go:268":    astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Features field on llm config, legitimately nil-able"},
		"internal/llm/config.go:301":    astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Models field on llm config, legitimately nil-able"},
		"internal/llm/pricing.go:280":   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Pricing field, legitimately nil-able when provider has no pricing config"},
		"internal/llm/pricing.go:368":   astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite nil-check on other-side comparison"},
		"internal/llm/ratelimit.go:123": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "requestLimit nil means unlimited (legitimate semantic)"},
		"internal/llm/ratelimit.go:136": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "tokenLimit nil means unlimited (legitimate semantic)"},

		// internal/memory
		"internal/memory/vector/embedded.go:216": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "Metadata field on vector record, legitimately nil-able"},

		// internal/observability
		"internal/observability/otel_decision_log_adapter.go:209": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "action.AgentExecution proto field, legitimately nil-able"},
		"internal/observability/otel_decision_log_adapter.go:316": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "action.NewNode proto field, legitimately nil-able"},
		// otel_metrics.go uses `if r == nil || r.<metric> == nil { return }` — composite nil-receiver shim
		// allowing the metrics struct to be called from contexts where metrics are disabled.
		"internal/observability/otel_metrics.go:366": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim — metrics methods callable when metrics disabled"},
		"internal/observability/otel_metrics.go:448": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:491": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:525": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:569": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:612": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:644": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:675": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:714": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:742": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:770": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:798": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:825": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},
		"internal/observability/otel_metrics.go:838": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim"},

		// internal/orchestrator
		"internal/orchestrator/checkpoint_loop_hook.go:62": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite action+metadata proto-shape guard"},
		"internal/orchestrator/inventory_validator.go:45":  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "inventory dep conditionally wired"},
		"internal/orchestrator/inventory_validator.go:91":  astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "inventory dep conditionally wired"},
		"internal/orchestrator/observe.go:506":             astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "graphQueries dep optional in non-graphrag deployments"},
		"internal/orchestrator/orchestrator.go:955":        astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "metrics dep optional; reassert with otel-required follow-up"},
		"internal/orchestrator/orchestrator.go:973":        astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "metrics dep optional; reassert with otel-required follow-up"},

		// internal/plan
		"internal/plan/step_executor.go:253": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "guardrails dep optional; reassert with guardrails-required follow-up"},
		"internal/plan/step_executor.go:298": astchecks.Entry{Category: astchecks.CategoryLegacyOptional, Reason: "guardrails dep optional; reassert with guardrails-required follow-up"},

		// internal/prompt — composite value-shape guards
		"internal/prompt/condition.go:89": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite field/value shape — both-nil is a valid match shape"},
		"internal/prompt/condition.go:92": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "composite field/value shape — either-nil short-circuit"},

		// internal/reservednames — fsnotify watcher nil guard in watch loop
		"internal/reservednames/provider.go:177": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "watcher nil guard in watchLoop; nil watcher means no fsnotify subscription (e.g. in-memory mode or test)"},

		// internal/secrets — composite nil-receiver shim for the SPIRE JWT source
		"internal/secrets/jwtsource/spire.go:136": astchecks.Entry{Category: astchecks.CategoryReceiverNilGuard, Reason: "composite nil-receiver shim for SPIRE JWT source"},

		// internal/types — proto Capabilities field
		"internal/types/target.go:334": astchecks.Entry{Category: astchecks.CategoryDefensiveGuard, Reason: "proto Capabilities field on Target, legitimately nil-able"},
	}

	// Real-code subtest: walk every gibson `internal/` package and fail
	// on any new finding. Slice 3.2 widened the scope from 6 hand-picked
	// dirs to every internal/* subdir; the allowlist absorbs the new
	// surface area inline. `cmd/` and `tests/` remain out of scope
	// (startup wiring + test fixtures are legitimate nil-check sites).
	t.Run("real_code", func(t *testing.T) {
		scopeDirs := internalScopeDirs(t, repoRoot)
		opts := astchecks.WalkOpts{
			ScopeDirs: scopeDirs,
			RepoRoot:  repoRoot,
			// Narrowed pattern: receiver-field shape only.
			// Bare-ident shapes (`if cfg == nil`) are excluded; they're
			// parameter-shape guards, not dependency-shape graceful-nil.
			Matchers:      []astchecks.Matcher{astchecks.NewNilGuard(true)},
			Allowlist:     requestPathAllowlist,
			SkipTestFiles: true,
			SkipGenerated: true,
		}

		findings, err := astchecks.Walk(opts)
		if err != nil {
			t.Fatalf("Walk: %v", err)
		}

		if len(findings) > 0 {
			t.Errorf("NEW graceful-nil branches in request paths (forbidden by [[0003]]):\n%s\n\n"+
				"Each is a `if X == nil { return [...] nil }` pattern in a request-path file. The fix is one of:\n"+
				"  (1) Validate the dep at startup (cmd/gibson/main.go) so it can never be nil at request time.\n"+
				"  (2) If this is a legitimate exception, add it to requestPathAllowlist with a category tag + reason.\n",
				astchecks.RenderFindings(findings))
		}

		// Keep the allowlist visible in test output so reviewers see what's
		// tolerated. Matches the pre-refactor format.
		t.Log(astchecks.FormatAllowlistLog(requestPathAllowlist))
	})
}
