// SPDX-License-Identifier: Elastic-2.0
// Copyright 2026 Zero Root AI

// Ingress guards for the harness callback listener (gibson#1450).
//
// HarnessCallbackService is served on exactly ONE listener — the callback
// listener that CallbackServer.Start opens — and Envoy's edge route for
// /gibson.harness.v1.HarnessCallbackService/ targets that listener via the
// gibson_daemon_callback cluster (zeroroot-ai/deploy
// helm/gibson-workloads/files/envoy/envoy.yaml).
//
// Before gibson#1450 that route pointed at the daemon's main :50051 listener,
// where the service is NOT registered and there is no UnknownServiceHandler,
// so every off-cluster component call returned codes.Unimplemented after
// passing jwt_authn and ext-authz. The two guards below pin both halves of the
// invariant that made that possible:
//
//  1. the service stays registered on the callback listener ONLY, so nobody
//     "fixes" a future ingress gap by dual-registering on :50051 and silently
//     splitting the surface across two listeners with two different gates; and
//  2. every method the Envoy peer policy admits has a REAL handler in this
//     package, so a routed method can never fall through to
//     UnimplementedHarnessCallbackServiceServer.
//
// The chart half — that the Envoy route actually targets the callback port —
// is pinned in the deploy repo by
// helm/gibson-workloads/tests/envoy-harness-callback-ingress.bats.

package harness

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	harnesspb "github.com/zeroroot-ai/sdk/api/gen/gibson/harness/v1"
)

// autogeneratedFile is what runtime.FuncForPC reports for a method that a type
// only has by PROMOTION from an embedded field — here, the no-op methods
// HarnessCallbackService inherits from the embedded
// harnesspb.UnimplementedHarnessCallbackServiceServer. A method declared in
// this package reports its real source file instead, which is what makes
// "does this daemon actually serve the RPC?" answerable from the binary rather
// than from a hand-maintained list that drifts.
const autogeneratedFile = "<autogenerated>"

// methodHandlerFile returns the source file declaring the handler for the given
// short RPC name on *HarnessCallbackService, and whether the method exists at
// all. A promoted (unimplemented) method returns autogeneratedFile.
func methodHandlerFile(t *testing.T, shortName string) (string, bool) {
	t.Helper()
	m, ok := reflect.TypeOf(&HarnessCallbackService{}).MethodByName(shortName)
	if !ok {
		return "", false
	}
	file, _ := runtime.FuncForPC(m.Func.Pointer()).FileLine(m.Func.Pointer())
	return file, true
}

// shortMethodName turns "/gibson.harness.v1.HarnessCallbackService/GetFoo"
// into "GetFoo".
func shortMethodName(fullMethod string) string {
	if i := strings.LastIndex(fullMethod, "/"); i >= 0 {
		return fullMethod[i+1:]
	}
	return fullMethod
}

// TestCallbackIngress_EveryEnvoyRoutedMethodHasAHandler is the acceptance guard
// for gibson#1450: an HarnessCallbackService method that Envoy routes must have
// a real server handler on the listener Envoy targets.
//
// "Method Envoy routes" is expressed here as the method set the Envoy peer's
// policy admits (callbackPeerMethodPolicies()[callbackEnvoySVID]) — Envoy is
// the sole ingress for external callers, and the peer policy is the second gate
// every Envoy-forwarded request passes. A method in that set with no handler in
// this package would return codes.Unimplemented to a caller that passed
// jwt_authn, ext-authz, FGA and the peer policy: the exact failure gibson#1450
// reported, one gate later.
func TestCallbackIngress_EveryEnvoyRoutedMethodHasAHandler(t *testing.T) {
	envoyMethods, policed := callbackPeerMethodPolicies()[callbackEnvoySVID]
	require.True(t, policed, "the Envoy peer must have an explicit method policy — it is the ingress peer")
	require.NotEmpty(t, envoyMethods, "the Envoy peer policy is empty; no external component could call anything")

	// The gRPC health probes are served by grpc-go's own health server on the
	// same listener, not by *HarnessCallbackService, so they are not reflected
	// against this type.
	skip := map[string]bool{healthCheckMethod: true, healthWatchMethod: true}

	var missing []string
	for method := range envoyMethods {
		if skip[method] {
			continue
		}
		short := shortMethodName(method)
		file, exists := methodHandlerFile(t, short)
		if !exists {
			missing = append(missing, short+" (no method on *HarnessCallbackService at all)")
			continue
		}
		if file == autogeneratedFile {
			missing = append(missing, short+" (promoted from UnimplementedHarnessCallbackServiceServer)")
		}
	}

	assert.Empty(t, missing,
		"these methods are admitted to the Envoy peer by callbackPeerMethodPolicies but have NO handler "+
			"in this package, so an external component reaching them through the edge gets codes.Unimplemented "+
			"after passing every auth gate (gibson#1450): %v. Either implement the handler or flip the "+
			"callbackMethodPolicy entry to agentSurface:false", missing)
}

// TestCallbackIngress_ServiceRegisteredOnlyOnCallbackListener pins the
// single-listener invariant.
//
// gibson#1450's alternative posture was to register HarnessCallbackService on
// the Envoy-fronted :50051 listener instead. That was rejected: :50051 has no
// per-peer method policy for this service, so it would expose EVERY RPC —
// GetCredential, CreateMission, DelegateToAgent, and DevboxExec once it has a
// handler — to any CG-JWT caller behind a single gate, where the callback
// listener keeps ext-authz/FGA AND the per-peer method policy. Registering on
// BOTH is strictly worse than either: the same service would answer on two
// listeners with two different gates, and which one a caller reached would
// depend on an Envoy route nobody reads next to this code.
//
// The guard is source-level because the two registration sites live in
// different packages and neither imports the other.
func TestCallbackIngress_ServiceRegisteredOnlyOnCallbackListener(t *testing.T) {
	root := repoRootFromTest(t)

	const registerCall = "RegisterHarnessCallbackServiceServer("
	var sites []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "vendor", "node_modules", ".tmp", "bin":
				return filepath.SkipDir
			}
			return nil
		}
		name := d.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			return nil
		}
		// The path comes from filepath.WalkDir rooted at the module directory
		// this test resolved from its own go.mod — not from input. gosec cannot
		// see that, so it flags the variable path.
		b, readErr := os.ReadFile(path) //nolint:gosec // walked path under the module root, not attacker-controlled
		if readErr != nil {
			return fmt.Errorf("read %s: %w", path, readErr)
		}
		for _, line := range strings.Split(string(b), "\n") {
			trimmed := strings.TrimSpace(line)
			// Skip comments — callback_service.go documents the call in a
			// doc comment, and a rendered comment must not make this pass or
			// fail.
			if strings.HasPrefix(trimmed, "//") {
				continue
			}
			if strings.Contains(trimmed, registerCall) {
				rel, _ := filepath.Rel(root, path)
				sites = append(sites, rel)
				break
			}
		}
		return nil
	})
	require.NoError(t, err)

	assert.Equal(t, []string{filepath.Join("internal", "engine", "harness", "callback_server.go")}, sites,
		"HarnessCallbackService must be registered on exactly ONE listener — the callback listener in "+
			"CallbackServer.Start. Envoy's edge route targets that listener's port via the "+
			"gibson_daemon_callback cluster (gibson#1450); a second registration would serve the same "+
			"service behind a different set of gates. Registration sites found: %v", sites)
}

// repoRootFromTest walks up from the test's working directory to the module
// root (the directory holding go.mod).
func repoRootFromTest(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	require.NoError(t, err)
	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		require.NotEqual(t, parent, dir, "walked past the filesystem root without finding go.mod")
		dir = parent
	}
}

// TestCallbackIngress_DeniedMethodsHaveNoHandler is the mirror of the first
// guard and closes the other direction: a method classified agentSurface:false
// must genuinely have no handler here. If someone implements a handler and
// forgets to reclassify — the exact situation DevboxExec (gibson#1183) is
// heading into — the deny is a silent 403 on a working RPC rather than an
// honest Unimplemented, and it will be debugged at the edge instead of here.
func TestCallbackIngress_DeniedMethodsHaveNoHandler(t *testing.T) {
	var surprises []string
	for method, decision := range callbackMethodPolicy {
		if decision.agentSurface {
			continue
		}
		short := shortMethodName(method)
		file, exists := methodHandlerFile(t, short)
		if exists && file != autogeneratedFile {
			surprises = append(surprises, short+" handled in "+filepath.Base(file))
		}
	}

	assert.Empty(t, surprises,
		"these methods are DENIED to the agent-callback peers but now have a real handler in this "+
			"package: %v. A handler with a deny is a working RPC that answers PermissionDenied at the "+
			"peer-policy gate. Flip its callbackMethodPolicy entry to agentSurface:true in the same "+
			"change that adds the handler", surprises)
}

// TestCallbackIngress_SessionRPCsAreReachable pins the three RPCs gibson#1184
// added and zeroroot-ai/zerocool-plugins#13 consumes. They are the reason
// gibson#1450 was a launch blocker: merged, classified agent-surface, and
// unreachable by the only component that calls them.
func TestCallbackIngress_SessionRPCsAreReachable(t *testing.T) {
	envoyMethods := callbackPeerMethodPolicies()[callbackEnvoySVID]

	for _, method := range []string{
		harnesspb.HarnessCallbackService_PutSessionContext_FullMethodName,
		harnesspb.HarnessCallbackService_GetSessionContext_FullMethodName,
		harnesspb.HarnessCallbackService_DeleteSessionContext_FullMethodName,
	} {
		t.Run(shortMethodName(method), func(t *testing.T) {
			assert.True(t, envoyMethods[method],
				"%s must be admitted to the Envoy peer — it is an off-cluster component's RPC and "+
					"Envoy is its only ingress", method)

			file, exists := methodHandlerFile(t, shortMethodName(method))
			require.True(t, exists, "%s has no method on *HarnessCallbackService", method)
			assert.NotEqual(t, autogeneratedFile, file,
				"%s falls through to UnimplementedHarnessCallbackServiceServer", method)
		})
	}
}
