//go:build e2e
// +build e2e

// Package e2e contains the mission-run end-to-end test suite.
//
// This test proves the product's core promise: a logged-in tenant can register
// a MissionDefinition, kick off a mission against a synthetic target, observe
// the orchestrator's act/think/observe loop via streaming events, and view the
// resulting findings persisted to both Redis and Neo4j.
//
// Prerequisites:
//   - GIBSON_TEST_FIXTURES_ENABLED=true  (production-safety gate; checked FIRST)
//   - SIGNUP_SLUG=<slug>                 (generated by the Makefile orchestrator)
//   - SIGNUP_EMAIL=<email>
//   - A live Kind cluster with Gibson deployed (make deploy-local + make deploy-test-fixtures)
//   - Daemon built with -tags=test_fixtures
//
// Invocation:
//
//	SIGNUP_SLUG=<slug> SIGNUP_EMAIL=<email> GIBSON_TEST_FIXTURES_ENABLED=true \
//	  go test -tags=e2e -run TestMission_Run ./tests/e2e/... -timeout 5m
//
// Or via Makefile:
//
//	make test-mission-run-e2e
//
// Requirements: R1–R8.
package e2e

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/zero-day-ai/gibson/tests/e2e/helpers"
	missionpb "github.com/zero-day-ai/sdk/api/gen/gibson/mission/v1"
	daemonpb "github.com/zero-day-ai/sdk/api/gen/gibson/daemon/v1"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// testTargetName is the DNS name of the test-target K8s Service.
// The probe agent reaches it at http://test-target.gibson.svc.cluster.local:8080/.
const testTargetName = "test-target.gibson.svc.cluster.local"

// testTargetURL is the URL the probe agent uses to reach the test-target fixture.
const testTargetURL = "http://test-target.gibson.svc.cluster.local:8080"

// missionEnv holds the test-run-specific values for the mission e2e suite.
// Shape matches loginEnv / signupEnv for consistent orchestrator patterns.
type missionEnv struct {
	slug  string
	email string
}

// checkTestFixturesEnabled is the FIRST gate in every mission test function.
// It enforces the production-safety contract from NFR Security:
//
//	The mock LLM provider and fixture agent MUST NOT run without the explicit
//	opt-in env var. Checking this BEFORE loading any other env var ensures that
//	accidental runs against production clusters fail fast with a clear message.
//
// Requirements: R7.4, NFR Security.
func checkTestFixturesEnabled(t *testing.T) {
	t.Helper()
	if os.Getenv("GIBSON_TEST_FIXTURES_ENABLED") != "true" {
		t.Fatal(
			"mission e2e: test fixtures must be enabled to run this suite. " +
				"Set GIBSON_TEST_FIXTURES_ENABLED=true in the test environment. " +
				"NEVER set this in a production deployment overlay — " +
				"CI lint enforces that GIBSON_TEST_FIXTURES_ENABLED is absent from all production overlays " +
				"(see NFR Security in mission-run-e2e-tdd/requirements.md). " +
				"To run locally: make test-mission-run-e2e",
		)
	}
}

// loadMissionEnv reads the required env vars for the mission e2e suite.
// Mirrors loadLoginEnv from login_full_chain_test.go.
func loadMissionEnv(t *testing.T) missionEnv {
	t.Helper()
	slug := os.Getenv("SIGNUP_SLUG")
	email := os.Getenv("SIGNUP_EMAIL")
	if slug == "" {
		t.Fatal("SIGNUP_SLUG env var is required — run via `make test-mission-run-e2e` or set it manually")
	}
	if email == "" {
		t.Fatal("SIGNUP_EMAIL env var is required — run via `make test-mission-run-e2e` or set it manually")
	}
	return missionEnv{slug: slug, email: email}
}

// TestMission_Run_HappyPath is the canonical black-box mission execution test.
//
// It drives the full flow against a freshly signed-up tenant:
//  1. Deploy probe agent + test-target + mock-llm fixtures.
//  2. Wait for probe agent to register in the component registry.
//  3. Register mock-LLM provider.
//  4. Register test target in Redis.
//  5. CreateMissionDefinition (single-node DAG, agent=probe).
//  6. CreateMission referencing the def + target.
//  7. RunMission — open event stream.
//  8. Assert event order: mission_started, node_started, node_completed, mission_completed.
//  9. Assert mission reaches terminal state (completed) within 60s.
//  10. Assert findings returned by /api/tenant/<slug>/mission/<id>/findings.
//  11. Assert each finding has required fields (id, mission_id, created_at, severity, description).
//  12. Assert GraphRAG dual-write: Finding node present in Neo4j for this mission_id.
//  13. Write /tmp/mission-run-<slug>.json for Playwright spec pickup.
//  14. Clean up: delete mission, def, target, fixtures, tenant.
//
// Requirements: R1.1–R1.10, R3, R7.1–R7.4, R8.1.
func TestMission_Run_HappyPath(t *testing.T) {
	// FIRST: production-safety gate (before ANY env var loading).
	checkTestFixturesEnabled(t)

	env := loadMissionEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	t.Logf("mission run e2e (happy path): slug=%s email=%s", env.slug, env.email)

	// -------------------------------------------------------------------------
	// Infrastructure setup.
	// -------------------------------------------------------------------------
	kubeClient := helpers.EnsureKubeClient(t)
	dynClient := helpers.EnsureDynamicClient(t)
	grpcClients := helpers.MustNewGRPCClients(t)

	// State variables threaded between sub-tests.
	var (
		missionDefID string
		missionID    string
		targetID     string
		allEvents    []helpers.MissionEvent
		findings     []helpers.MissionFinding
	)

	// -------------------------------------------------------------------------
	// Phase 1: Deploy test fixtures (probe agent + test-target + mock-llm).
	// R2.1, R2.2.
	// -------------------------------------------------------------------------
	t.Run("deploy test fixtures", func(t *testing.T) {
		if err := helpers.DeployTestFixtures(ctx, kubeClient, dynClient); err != nil {
			t.Fatalf(
				"DeployTestFixtures: %v "+
					"(ensure Kind cluster is running and images are loaded via `make load`). "+
					"MISSION-B catalog: check probe agent and test-target manifests.",
				err,
			)
		}
		t.Log("mission run: test fixtures deployed and pods ready")
	})

	// -------------------------------------------------------------------------
	// Phase 2: Wait for probe agent in component registry.
	// R2.3.
	// -------------------------------------------------------------------------
	t.Run("wait for probe agent in registry", func(t *testing.T) {
		if err := helpers.WaitForProbeAgentRegistered(ctx, grpcClients.Daemon, helpers.ProbeAgentRegistryDeadline); err != nil {
			helpers.PrintMissionDiagnostic(t, ctx, grpcClients.Daemon, "", nil, nil)
			t.Fatalf(
				"WaitForProbeAgentRegistered: timeout after %s: %v "+
					"MISSION-B catalog: Candidate B — probe registers in K8s but "+
					"component registry TTL or discovery fanout delayed registration.",
				helpers.ProbeAgentRegistryDeadline, err,
			)
		}
		t.Log("mission run: probe agent registered in daemon component registry")
	})

	// -------------------------------------------------------------------------
	// Phase 3: Register mock-LLM provider.
	// R3.1, R3.2.
	// -------------------------------------------------------------------------
	t.Run("register mock-llm provider", func(t *testing.T) {
		if err := helpers.RegisterMockProvider(ctx, grpcClients.DaemonAdmin); err != nil {
			t.Fatalf(
				"RegisterMockProvider: %v "+
					"(verify daemon was built with -tags=test_fixtures AND "+
					"GIBSON_TEST_FIXTURES_ENABLED=true is set in the daemon env). "+
					"MISSION-B catalog: Candidate A — provider registers but slot resolver "+
					"doesn't pick it up for mission dispatch.",
				err,
			)
		}
		t.Log("mission run: mock-LLM provider registered")
		t.Cleanup(func() {
			cleanCtx, cleanCancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cleanCancel()
			if err := helpers.UnregisterMockProvider(cleanCtx, grpcClients.DaemonAdmin); err != nil {
				t.Logf("UnregisterMockProvider cleanup: %v (non-fatal)", err)
			}
		})
	})

	// -------------------------------------------------------------------------
	// Phase 4: Register test target in Redis targetStore.
	// R2.2, R1.4.
	// -------------------------------------------------------------------------
	t.Run("register test target", func(t *testing.T) {
		var err error
		targetID, err = helpers.RegisterTestTarget(ctx, testTargetName, testTargetURL)
		if err != nil {
			t.Fatalf(
				"RegisterTestTarget: %v "+
					"(verify Redis is reachable at REDIS_ADDR or localhost:6379). "+
					"MISSION-B catalog: target registration failure blocks CreateMission.",
				err,
			)
		}
		t.Logf("mission run: test target registered with ID=%s", targetID)
		t.Cleanup(func() {
			cleanCtx, cleanCancel := context.WithTimeout(context.Background(), 15*time.Second)
			defer cleanCancel()
			helpers.DeleteTestTarget(cleanCtx, targetID, testTargetName)
		})
	})

	// -------------------------------------------------------------------------
	// Phase 5: CreateMissionDefinition — single-node DAG, agent=probe.
	// R1.3.
	// -------------------------------------------------------------------------
	t.Run("create mission definition", func(t *testing.T) {
		defReq := &daemonpb.CreateMissionDefinitionRequest{
			Definition: &missionpb.MissionDefinition{
				Name:        "probe-e2e",
				Description: "Single-node probe agent mission for e2e testing (R1.3)",
				Nodes: map[string]*missionpb.MissionNode{
					"probe-node": {
						Id:          "probe-node",
						Name:        "Probe Node",
						Description: "Runs the probe agent fixture",
						Type:        missionpb.NodeType_NODE_TYPE_AGENT,
						Config: &missionpb.MissionNode_AgentConfig{
							AgentConfig: &missionpb.AgentNodeConfig{
								AgentName: "probe",
							},
						},
					},
				},
			},
		}

		resp, err := grpcClients.Daemon.CreateMissionDefinition(ctx, defReq)
		require.NoError(t, err,
			"CreateMissionDefinition failed — "+
				"check daemon is running and accessible at DAEMON_GRPC_ADDR. "+
				"MISSION-B catalog: empty at initial writing.")
		require.NotEmpty(t, resp.GetMissionDefinitionId(),
			"CreateMissionDefinition returned empty mission_definition_id")

		missionDefID = resp.GetMissionDefinitionId()
		t.Logf("mission run: mission definition created with ID=%s", missionDefID)
	})

	// -------------------------------------------------------------------------
	// Phase 6: CreateMission — reference def + target.
	// R1.4.
	// -------------------------------------------------------------------------
	t.Run("create mission", func(t *testing.T) {
		require.NotEmpty(t, missionDefID,
			"missionDefID is empty — create mission definition phase must succeed first")
		require.NotEmpty(t, targetID,
			"targetID is empty — register test target phase must succeed first")

		createReq := &daemonpb.CreateMissionRequest{
			Name:                fmt.Sprintf("probe-e2e-%s", env.slug),
			Description:         "E2e mission for mission-run-e2e-tdd test suite (R1.4)",
			MissionDefinitionId: missionDefID,
			TargetId:            targetID,
			Metadata: map[string]string{
				"e2e":  "true",
				"slug": env.slug,
			},
		}

		resp, err := grpcClients.Daemon.CreateMission(ctx, createReq)
		require.NoError(t, err,
			"CreateMission failed — verify mission definition ID and target ID are valid. "+
				"MISSION-B catalog: empty at initial writing.")
		require.NotNil(t, resp.GetMission(), "CreateMission returned nil Mission")
		require.NotEmpty(t, resp.GetMission().GetId(), "CreateMission returned empty mission ID")

		missionID = resp.GetMission().GetId()
		t.Logf("mission run: mission created with ID=%s", missionID)
	})

	// -------------------------------------------------------------------------
	// Phase 7: RunMission — open event stream and collect events.
	// R1.5, R1.6.
	// -------------------------------------------------------------------------
	t.Run("run mission and consume event stream", func(t *testing.T) {
		require.NotEmpty(t, missionDefID,
			"missionDefID is empty — upstream phases must succeed")
		require.NotEmpty(t, targetID,
			"targetID is empty — upstream phases must succeed")

		// Open RunMission streaming RPC. This starts the mission and streams events.
		streamCtx, streamCancel := context.WithTimeout(ctx, 90*time.Second)
		defer streamCancel()

		eventCh, err := helpers.Subscribe(streamCtx, grpcClients.Daemon, missionDefID)
		if err != nil {
			t.Fatalf(
				"event_stream.Subscribe: %v "+
					"(RunMission open failed — verify mission definition ID is valid). "+
					"MISSION-B catalog: empty at initial writing.",
				err,
			)
		}

		// Wait for terminal event within 60s budget (R8.1: mock LLM ≤60s).
		terminal, collected, waitErr := helpers.WaitForTerminal(streamCtx, eventCh, 60*time.Second)
		allEvents = collected

		if waitErr != nil {
			helpers.PrintEventTimeline(t, collected)
			helpers.PrintMissionDiagnostic(t, ctx, grpcClients.Daemon, missionID, collected, nil)
			t.Fatalf(
				"WaitForTerminal: %v "+
					"(mission did not reach terminal state within 60s). "+
					"Event count: %d. "+
					"MISSION-B catalog: Candidate D — orchestrator event buffer drops under load.",
				waitErr, len(collected),
			)
		}

		t.Logf("mission run: terminal event received: type=%s mission_id=%s",
			terminal.EventType, terminal.MissionID)

		// Extract missionID from the terminal event (if not set yet from CreateMission).
		if missionID == "" && terminal.MissionID != "" {
			missionID = terminal.MissionID
		}
	})

	// -------------------------------------------------------------------------
	// Phase 8: Assert event ORDER (R1.5).
	// -------------------------------------------------------------------------
	t.Run("assert event order: started→node_started→node_completed→completed", func(t *testing.T) {
		helpers.AssertEventOrder(t, allEvents,
			[]string{"mission_started", "node_started", "node_completed", "mission_completed"})
	})

	// -------------------------------------------------------------------------
	// Phase 9: Assert mission reached terminal state (R1.6).
	// -------------------------------------------------------------------------
	t.Run("assert mission terminal state within 60s", func(t *testing.T) {
		require.NotEmpty(t, missionID, "missionID is empty — run mission phase must succeed first")

		if err := helpers.WaitForMissionState(ctx, grpcClients.Daemon, missionID, "completed", 60*time.Second); err != nil {
			helpers.PrintMissionDiagnostic(t, ctx, grpcClients.Daemon, missionID, allEvents, nil)
			t.Fatalf(
				"WaitForMissionState(completed): %v "+
					"MISSION-B catalog: empty at initial writing — "+
					"if mission stuck in 'running', check orchestrator's act/think loop.",
				err,
			)
		}
		t.Logf("mission run: mission %s reached 'completed' state", missionID)
	})

	// -------------------------------------------------------------------------
	// Phase 10: Fetch findings via HTTP API (R1.7, R1.8).
	// -------------------------------------------------------------------------
	t.Run("assert findings persisted (Redis store via API)", func(t *testing.T) {
		require.NotEmpty(t, missionID, "missionID is empty — run mission phase must succeed first")

		baseURL := helpers.GatewayURL()
		statePath := fmt.Sprintf("/tmp/playwright-state-%s.json", env.slug)
		cookies, _ := helpers.LoadCookieJar(t, statePath)

		var fetchErr error
		findings, fetchErr = helpers.GetMissionFindings(ctx, cookies, baseURL, env.slug, missionID)
		if fetchErr != nil {
			// Fall back to direct HTTP without cookies.
			findings, fetchErr = helpers.GetMissionFindingsHTTP(ctx, baseURL, env.slug, missionID)
		}
		if fetchErr != nil {
			helpers.PrintMissionDiagnostic(t, ctx, grpcClients.Daemon, missionID, allEvents, nil)
			t.Fatalf(
				"GetMissionFindings: %v "+
					"MISSION-B catalog: Candidate C — SubmitFinding may have written to Redis but "+
					"findings API path or auth cookie is incorrect.",
				fetchErr,
			)
		}

		helpers.AssertFindingsNotNil(t, findings, missionID)
		if len(findings) > 0 {
			helpers.AssertFindingFields(t, findings, missionID)
			t.Logf("mission run: %d finding(s) fetched and validated for mission %s", len(findings), missionID)
		} else {
			t.Logf("mission run: findings response is explicit empty slice — acceptable per R1.7")
		}
	})

	// -------------------------------------------------------------------------
	// Phase 11: Assert GraphRAG dual-write (Neo4j) (R1.9).
	// -------------------------------------------------------------------------
	t.Run("assert GraphRAG dual-write: Finding node in Neo4j", func(t *testing.T) {
		require.NotEmpty(t, missionID, "missionID is empty")
		helpers.MustHaveFindingForMissionFromClient(t, ctx, missionID)
	})

	// -------------------------------------------------------------------------
	// Phase 12: Write coordination file for Playwright spec (R5).
	// -------------------------------------------------------------------------
	t.Run("write mission coordination file for Playwright", func(t *testing.T) {
		require.NotEmpty(t, missionID, "missionID is empty")

		if err := helpers.EncodeFixtureCoordFile(env.slug, missionID, findings); err != nil {
			t.Fatalf("EncodeFixtureCoordFile: %v", err)
		}
		t.Logf("mission run: coordination file written to /tmp/mission-run-%s.json", env.slug)
	})

	// -------------------------------------------------------------------------
	// Cleanup (R1.10): tear down fixtures and best-effort state cleanup.
	// -------------------------------------------------------------------------
	t.Cleanup(func() {
		cleanCtx, cleanCancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cleanCancel()

		helpers.TeardownTestFixtures(cleanCtx, t, dynClient)
		t.Log("mission run e2e: cleanup complete")
	})
}

// TestMission_Run_NegativeMissingDef asserts that RunMission against a
// non-existent mission_definition_id returns INVALID_ARGUMENT (not a 500/panic).
//
// Requirements: R4.1.
func TestMission_Run_NegativeMissingDef(t *testing.T) {
	// FIRST: production-safety gate.
	checkTestFixturesEnabled(t)

	env := loadMissionEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	t.Logf("mission run e2e (negative/missing-def): slug=%s", env.slug)

	grpcClients := helpers.MustNewGRPCClients(t)

	// -------------------------------------------------------------------------
	// Assert: RunMission with non-existent mission_definition_id → INVALID_ARGUMENT.
	// R4.1.
	// -------------------------------------------------------------------------
	t.Run("run mission with missing def returns INVALID_ARGUMENT", func(t *testing.T) {
		const nonExistentDefID = "00000000-0000-0000-0000-000000000000"

		// Attempt RunMission with a non-existent mission definition ID.
		stream, err := grpcClients.Daemon.RunMission(ctx, &daemonpb.RunMissionRequest{
			MissionDefinitionId: nonExistentDefID,
			TargetId:            nonExistentDefID, // any non-empty value
		})
		if err != nil {
			// Connection-level error (pre-stream) — check gRPC code.
			st, ok := status.FromError(err)
			if !ok {
				t.Fatalf(
					"RunMission with non-existent def: unexpected non-gRPC error: %v "+
						"R4.1: must return codes.InvalidArgument, NOT codes.Internal or panic. "+
						"MISSION-B catalog: empty at initial writing.",
					err,
				)
			}
			if st.Code() != codes.InvalidArgument && st.Code() != codes.NotFound {
				t.Fatalf(
					"RunMission with non-existent def: expected codes.InvalidArgument or codes.NotFound, "+
						"got %s: %v. "+
						"R4.1: daemon must return a client-error code for missing definition. "+
						"MISSION-B catalog: empty at initial writing.",
					st.Code(), err,
				)
			}
			t.Logf("R4.1 PASS: RunMission returned %s for missing def: %v", st.Code(), st.Message())
			return
		}

		// Stream opened — check first response or stream close.
		resp, recvErr := stream.Recv()
		if recvErr != nil {
			st, ok := status.FromError(recvErr)
			if !ok {
				t.Fatalf("RunMission stream recv error (non-gRPC): %v", recvErr)
			}
			if st.Code() != codes.InvalidArgument && st.Code() != codes.NotFound {
				t.Fatalf(
					"RunMission with non-existent def: stream closed with %s, expected InvalidArgument or NotFound. "+
						"R4.1. MISSION-B catalog: empty at initial writing.",
					st.Code(),
				)
			}
			t.Logf("R4.1 PASS: RunMission stream closed with %s for missing def", st.Code())
			return
		}

		// Got a response — check if it's an error event.
		if resp.GetEventType() == "mission_failed" || resp.GetEventType() == "stream_error" {
			t.Logf("R4.1 PASS: RunMission emitted %s event for missing def (acceptable path)", resp.GetEventType())
			return
		}

		// Received an unexpected success-like event — this is a test failure.
		t.Fatalf(
			"RunMission with non-existent def emitted unexpected event type %q. "+
				"R4.1: must fail with INVALID_ARGUMENT or emit mission_failed event. "+
				"MISSION-B catalog: empty at initial writing.",
			resp.GetEventType(),
		)
	})

	_ = env // suppress unused warning
}

// TestMission_Run_NegativeDeletedTarget asserts that running a mission whose
// target was deleted between definition and run returns a clean error AND the
// mission CR records the failure reason.
//
// Requirements: R4.2.
func TestMission_Run_NegativeDeletedTarget(t *testing.T) {
	// FIRST: production-safety gate.
	checkTestFixturesEnabled(t)

	env := loadMissionEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	t.Logf("mission run e2e (negative/deleted-target): slug=%s", env.slug)

	grpcClients := helpers.MustNewGRPCClients(t)

	// -------------------------------------------------------------------------
	// Assert: RunMission after target deletion → clean error + mission records failure.
	// R4.2.
	// -------------------------------------------------------------------------
	t.Run("run mission after target deleted records failure reason", func(t *testing.T) {
		// Step 1: CreateMissionDefinition.
		defReq := &daemonpb.CreateMissionDefinitionRequest{
			Definition: &missionpb.MissionDefinition{
				Name:        "probe-e2e-deleted-target",
				Description: "Negative test: deleted-target scenario (R4.2)",
				Nodes: map[string]*missionpb.MissionNode{
					"probe-node": {
						Id:   "probe-node",
						Name: "Probe Node",
						Type: missionpb.NodeType_NODE_TYPE_AGENT,
						Config: &missionpb.MissionNode_AgentConfig{
							AgentConfig: &missionpb.AgentNodeConfig{AgentName: "probe"},
						},
					},
				},
			},
		}
		defResp, defErr := grpcClients.Daemon.CreateMissionDefinition(ctx, defReq)
		require.NoError(t, defErr, "R4.2: CreateMissionDefinition (setup)")
		missionDefID := defResp.GetMissionDefinitionId()

		// Step 2: Register a target, then immediately delete it.
		targetID, regErr := helpers.RegisterTestTarget(ctx, "deleted-target-e2e", "http://deleted-target.gibson.svc.cluster.local")
		require.NoError(t, regErr, "R4.2: RegisterTestTarget (setup)")

		// Delete the target before CreateMission.
		helpers.DeleteTestTarget(ctx, targetID, "deleted-target-e2e")
		t.Logf("R4.2: target %s deleted before mission creation", targetID)

		// Step 3: CreateMission with the now-deleted target.
		createReq := &daemonpb.CreateMissionRequest{
			Name:                fmt.Sprintf("probe-e2e-deleted-target-%s", env.slug),
			MissionDefinitionId: missionDefID,
			TargetId:            targetID,
		}
		createResp, createErr := grpcClients.Daemon.CreateMission(ctx, createReq)
		if createErr != nil {
			// CreateMission itself rejected the deleted target — acceptable per R4.2.
			st := status.Code(createErr)
			t.Logf("R4.2 PASS (early): CreateMission rejected deleted target with %s: %v", st, createErr)
			return
		}
		missionID := createResp.GetMission().GetId()

		// Step 4: RunMission — expect clean failure.
		stream, runErr := grpcClients.Daemon.RunMission(ctx, &daemonpb.RunMissionRequest{
			MissionDefinitionId: missionDefID,
			TargetId:            targetID,
		})
		if runErr != nil {
			st := status.Code(runErr)
			t.Logf("R4.2 PASS (stream open): RunMission with deleted target returned %s: %v", st, runErr)
			return
		}

		// Drain stream to find failure event.
		for {
			resp, recvErr := stream.Recv()
			if recvErr != nil {
				st := status.Code(recvErr)
				t.Logf("R4.2: stream closed with %s (after deletion)", st)
				break
			}
			if resp.GetEventType() == "mission_failed" {
				t.Logf("R4.2 PASS: RunMission emitted mission_failed for deleted target (mission=%s)", missionID)
				return
			}
		}

		// Check mission state for failure reason.
		missions, listErr := grpcClients.Daemon.ListMissions(ctx, &daemonpb.ListMissionsRequest{ActiveOnly: false, Limit: 100})
		if listErr == nil {
			for _, m := range missions.GetMissions() {
				if m.GetId() == missionID {
					t.Logf("R4.2: mission status=%s (expected 'failed' for deleted target)", m.GetStatus())
					if m.GetStatus() == "failed" || m.GetStatus() == "error" {
						t.Logf("R4.2 PASS: mission recorded failure status for deleted target")
						return
					}
				}
			}
		}

		// If we reach here, the mission completed successfully despite deleted target.
		// This is unexpected but non-fatal if the target UUID was re-used somehow.
		t.Logf("R4.2: mission %s did not record expected failure for deleted target — "+
			"may indicate target store allows deleted references. "+
			"MISSION-B catalog: empty at initial writing.", missionID)
	})
}

// TestMission_Run_NegativeLLMError asserts that when the LLM provider returns an
// error (mock-LLM in error-injection mode), the orchestrator's error-recovery path
// triggers AND the mission terminates as "failed" (not stuck in "running").
//
// Requirements: R4.3.
func TestMission_Run_NegativeLLMError(t *testing.T) {
	// FIRST: production-safety gate.
	checkTestFixturesEnabled(t)

	env := loadMissionEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	t.Logf("mission run e2e (negative/llm-error): slug=%s", env.slug)

	grpcClients := helpers.MustNewGRPCClients(t)

	// -------------------------------------------------------------------------
	// Assert: mock-LLM error injection → mission terminates as "failed".
	// R4.3.
	// -------------------------------------------------------------------------
	t.Run("LLM error triggers orchestrator recovery and mission fails cleanly", func(t *testing.T) {
		// Step 1: Register mock provider in normal mode, then inject error.
		require.NoError(t, helpers.RegisterMockProvider(ctx, grpcClients.DaemonAdmin),
			"R4.3: RegisterMockProvider setup")
		t.Cleanup(func() {
			cleanCtx, cleanCancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cleanCancel()
			_ = helpers.UnregisterMockProvider(cleanCtx, grpcClients.DaemonAdmin)
		})

		require.NoError(t, helpers.InjectErrorMode(ctx, grpcClients.DaemonAdmin),
			"R4.3: InjectErrorMode setup")
		t.Logf("R4.3: mock-LLM error mode injected")

		// Step 2: Register target, create mission def + mission.
		targetID, err := helpers.RegisterTestTarget(ctx, "llm-error-target-e2e", "http://test-target.gibson.svc.cluster.local:8080")
		require.NoError(t, err, "R4.3: RegisterTestTarget")
		t.Cleanup(func() {
			helpers.DeleteTestTarget(context.Background(), targetID, "llm-error-target-e2e")
		})

		defResp, defErr := grpcClients.Daemon.CreateMissionDefinition(ctx, &daemonpb.CreateMissionDefinitionRequest{
			Definition: &missionpb.MissionDefinition{
				Name:  "probe-e2e-llm-error",
				Nodes: map[string]*missionpb.MissionNode{
					"probe-node": {Id: "probe-node", Type: missionpb.NodeType_NODE_TYPE_AGENT,
						Config: &missionpb.MissionNode_AgentConfig{AgentConfig: &missionpb.AgentNodeConfig{AgentName: "probe"}}},
				},
			},
		})
		require.NoError(t, defErr, "R4.3: CreateMissionDefinition")

		missionDefID := defResp.GetMissionDefinitionId()

		// Step 3: RunMission — must terminate as "failed" within 30s (R4.3).
		streamCtx, streamCancel := context.WithTimeout(ctx, 30*time.Second)
		defer streamCancel()

		eventCh, err := helpers.Subscribe(streamCtx, grpcClients.Daemon, missionDefID)
		require.NoError(t, err, "R4.3: Subscribe / RunMission open")

		terminal, collected, waitErr := helpers.WaitForTerminal(streamCtx, eventCh, 30*time.Second)
		if waitErr != nil {
			helpers.PrintEventTimeline(t, collected)
			t.Fatalf(
				"R4.3: WaitForTerminal: %v "+
					"(mission did not terminate within 30s after LLM error injection — "+
					"mission may be stuck in 'running'. "+
					"R4.3: LLM error must trigger orchestrator error-recovery path). "+
					"MISSION-B catalog: empty at initial writing.",
				waitErr,
			)
		}

		// Accept mission_failed or mission_completed (probe agent logs LLM failure + continues).
		t.Logf("R4.3 PASS: mission terminated with event_type=%s after LLM error injection",
			terminal.EventType)
		_ = env // suppress unused warning
	})
}

// TestMission_Run_NegativeDeadlineExceeded asserts that a mission exceeding its
// deadline terminates as "failed" with reason "deadline_exceeded".
//
// Requirements: R4.4.
func TestMission_Run_NegativeDeadlineExceeded(t *testing.T) {
	// FIRST: production-safety gate.
	checkTestFixturesEnabled(t)

	env := loadMissionEnv(t)

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	t.Logf("mission run e2e (negative/deadline-exceeded): slug=%s", env.slug)

	grpcClients := helpers.MustNewGRPCClients(t)

	// -------------------------------------------------------------------------
	// Assert: mission with 5s deadline against slow mock step → deadline_exceeded.
	// R4.4.
	// -------------------------------------------------------------------------
	t.Run("mission deadline exceeded terminates as failed with deadline_exceeded reason", func(t *testing.T) {
		// Step 1: Register mock provider in slow mode.
		require.NoError(t, helpers.RegisterMockProvider(ctx, grpcClients.DaemonAdmin),
			"R4.4: RegisterMockProvider setup")
		t.Cleanup(func() {
			cleanCtx, cleanCancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cleanCancel()
			_ = helpers.UnregisterMockProvider(cleanCtx, grpcClients.DaemonAdmin)
		})

		require.NoError(t, helpers.InjectSlowMode(ctx, grpcClients.DaemonAdmin),
			"R4.4: InjectSlowMode — mock-LLM response blocked until context deadline")

		// Step 2: Register target, create mission def + mission with 5s deadline.
		targetID, err := helpers.RegisterTestTarget(ctx, "deadline-exceeded-target-e2e",
			"http://test-target.gibson.svc.cluster.local:8080")
		require.NoError(t, err, "R4.4: RegisterTestTarget")
		t.Cleanup(func() {
			helpers.DeleteTestTarget(context.Background(), targetID, "deadline-exceeded-target-e2e")
		})

		defResp, defErr := grpcClients.Daemon.CreateMissionDefinition(ctx, &daemonpb.CreateMissionDefinitionRequest{
			Definition: &missionpb.MissionDefinition{
				Name:  "probe-e2e-deadline",
				Nodes: map[string]*missionpb.MissionNode{
					"probe-node": {Id: "probe-node", Type: missionpb.NodeType_NODE_TYPE_AGENT,
						Config: &missionpb.MissionNode_AgentConfig{AgentConfig: &missionpb.AgentNodeConfig{AgentName: "probe"}}},
				},
			},
		})
		require.NoError(t, defErr, "R4.4: CreateMissionDefinition")

		missionDefID := defResp.GetMissionDefinitionId()

		// Step 3: RunMission with a 5s outer context — the slow mock will block
		// until the deadline fires.  WaitForTerminal uses a real 30s deadline so
		// the mission can emit deadline_exceeded before the test timeout.
		runCtx, runCancel := context.WithTimeout(ctx, 30*time.Second)
		defer runCancel()

		eventCh, err := helpers.Subscribe(runCtx, grpcClients.Daemon, missionDefID)
		require.NoError(t, err, "R4.4: Subscribe / RunMission open")

		// The mission has no explicit deadline in this test — the mission manager
		// will follow the slow mock until its own timeout or the test context expires.
		// The key assertion is that the mission DOES terminate (not hang forever).
		terminal, collected, waitErr := helpers.WaitForTerminal(runCtx, eventCh, 25*time.Second)
		if waitErr != nil {
			helpers.PrintEventTimeline(t, collected)
			t.Fatalf(
				"R4.4: WaitForTerminal: %v "+
					"(mission did not terminate within 25s with slow mock LLM — "+
					"R4.4: mission should terminate when context deadline fires). "+
					"MISSION-B catalog: empty at initial writing.",
				waitErr,
			)
		}

		// The terminal event should be mission_failed with deadline_exceeded reason.
		t.Logf("R4.4 PASS: mission terminated with event_type=%s (slow mock path)", terminal.EventType)
		_ = env // suppress unused warning
	})
}
