package state

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/redis/go-redis/v9"
)

// StreamEntry represents a single entry in a Redis Stream.
// Each entry has an auto-generated or custom ID and a map of field-value pairs.
type StreamEntry struct {
	// ID is the stream entry ID (e.g., "1234567890123-0")
	// Format: <millisecondsTime>-<sequenceNumber>
	ID string

	// Values contains the field-value pairs for this entry
	Values map[string]any
}

// StreamReadOptions configures the behavior of StreamRead operations.
type StreamReadOptions struct {
	// Count limits the number of entries returned per stream
	// If 0, no limit is applied
	Count int64

	// Block specifies how long to wait for new entries
	// If 0, returns immediately (non-blocking)
	// If > 0, blocks until entries arrive or timeout expires
	Block time.Duration

	// LastID specifies the starting point for reading
	// Use "0" to read from the beginning
	// Use "$" to read only new entries
	// Use specific ID to read from after that entry
	LastID string
}

// StreamTrimOptions configures the behavior of StreamTrim operations.
type StreamTrimOptions struct {
	// MaxLen limits the stream to approximately this many entries
	// Only used when > 0
	MaxLen int64

	// MinID removes all entries with IDs lower than this
	// Only used when not empty
	MinID string

	// Approximate allows Redis to trim the stream more efficiently
	// When true, uses "~" operator for MAXLEN (less precise but faster)
	Approximate bool
}

// ConsumerGroupOptions configures consumer group operations for exactly-once processing.
type ConsumerGroupOptions struct {
	// Group is the consumer group name
	Group string

	// Consumer is the consumer name within the group
	Consumer string

	// Count limits the number of entries returned
	// If 0, defaults to 10
	Count int64

	// Block specifies how long to wait for new entries
	// If 0, returns immediately (non-blocking)
	Block time.Duration

	// NoAck disables automatic acknowledgment (use XACK explicitly)
	// When false, messages are auto-acked on read
	NoAck bool
}

// PendingMessage represents a pending (unacknowledged) message in a consumer group.
type PendingMessage struct {
	// ID is the message ID
	ID string

	// Consumer is the name of the consumer that fetched this message
	Consumer string

	// IdleTime is how long the message has been pending
	IdleTime time.Duration

	// DeliveryCount is the number of times this message has been delivered
	DeliveryCount int64
}

// StreamAdd appends a new entry to a Redis Stream with an auto-generated ID.
// The ID is generated by Redis based on the current timestamp.
//
// Returns the auto-generated entry ID.
//
// Example:
//
//	values := map[string]any{
//	    "event": "user.created",
//	    "user_id": "123",
//	    "timestamp": time.Now().Unix(),
//	}
//	id, err := client.StreamAdd(ctx, "events:user", values)
//	if err != nil {
//	    log.Fatalf("failed to add stream entry: %v", err)
//	}
//	fmt.Printf("Entry added with ID: %s\n", id)
func (c *StateClient) StreamAdd(ctx context.Context, stream string, values map[string]any) (string, error) {
	if stream == "" {
		return "", fmt.Errorf("stream name cannot be empty")
	}

	if len(values) == 0 {
		return "", fmt.Errorf("values cannot be empty")
	}

	// Use "*" for auto-generated ID
	result, err := c.client.XAdd(ctx, &redis.XAddArgs{
		Stream: stream,
		ID:     "*",
		Values: values,
	}).Result()

	if err != nil {
		return "", fmt.Errorf("failed to add entry to stream %s: %w", stream, err)
	}

	return result, nil
}

// StreamAddWithID appends a new entry to a Redis Stream with a specific ID.
// The ID must be greater than all existing IDs in the stream.
//
// Returns the specified entry ID if successful.
//
// Example:
//
//	id := fmt.Sprintf("%d-0", time.Now().UnixMilli())
//	values := map[string]any{"event": "test"}
//	resultID, err := client.StreamAddWithID(ctx, "events:test", id, values)
func (c *StateClient) StreamAddWithID(ctx context.Context, stream, id string, values map[string]any) (string, error) {
	if stream == "" {
		return "", fmt.Errorf("stream name cannot be empty")
	}

	if id == "" {
		return "", fmt.Errorf("id cannot be empty")
	}

	if len(values) == 0 {
		return "", fmt.Errorf("values cannot be empty")
	}

	result, err := c.client.XAdd(ctx, &redis.XAddArgs{
		Stream: stream,
		ID:     id,
		Values: values,
	}).Result()

	if err != nil {
		return "", fmt.Errorf("failed to add entry to stream %s with ID %s: %w", stream, id, err)
	}

	return result, nil
}

// StreamRead reads entries from one or more Redis Streams.
// It supports blocking and non-blocking reads, and can read from multiple streams simultaneously.
//
// Returns a map of stream names to their entries.
// When blocking with a timeout and no entries arrive, returns an empty map (not an error).
//
// Example:
//
//	// Non-blocking read from beginning
//	opts := &StreamReadOptions{
//	    LastID: "0",
//	    Count:  10,
//	}
//	entries, err := client.StreamRead(ctx, []string{"events:user"}, opts)
//
//	// Blocking read for new entries
//	opts := &StreamReadOptions{
//	    LastID: "$",
//	    Block:  5 * time.Second,
//	}
//	entries, err := client.StreamRead(ctx, []string{"events:user", "events:order"}, opts)
func (c *StateClient) StreamRead(ctx context.Context, streams []string, opts *StreamReadOptions) (map[string][]StreamEntry, error) {
	if len(streams) == 0 {
		return nil, fmt.Errorf("streams cannot be empty")
	}

	// Apply defaults
	if opts == nil {
		opts = &StreamReadOptions{
			LastID: "0",
		}
	}

	if opts.LastID == "" {
		opts.LastID = "0"
	}

	// Build stream IDs for XREAD
	// XREAD expects: STREAMS stream1 stream2 ... id1 id2 ...
	streamIDs := make([]string, len(streams))
	for i := range streams {
		streamIDs[i] = opts.LastID
	}

	// Map the documented Block semantics onto go-redis XReadArgs.Block:
	//   - opts.Block == 0  -> non-blocking (return immediately, even for LastID "$")
	//   - opts.Block  > 0  -> block for that duration, then return
	// go-redis emits the BLOCK option whenever Block >= 0, and BLOCK 0 means
	// "block forever". To honor our non-blocking contract we must pass a
	// negative value so go-redis omits BLOCK entirely. Otherwise a read from
	// "$" with no new entries hangs indefinitely (gibson#410).
	block := opts.Block
	if block <= 0 {
		block = -1
	}

	args := &redis.XReadArgs{
		Streams: append(streams, streamIDs...),
		Count:   opts.Count,
		Block:   block,
	}

	result, err := c.client.XRead(ctx, args).Result()
	if err != nil {
		// XREAD with block timeout returns redis.Nil, which is not an error
		if err == redis.Nil {
			return make(map[string][]StreamEntry), nil
		}
		return nil, fmt.Errorf("failed to read from streams: %w", err)
	}

	// Convert redis.XStream to our StreamEntry format
	entries := make(map[string][]StreamEntry)
	for _, stream := range result {
		streamEntries := make([]StreamEntry, 0, len(stream.Messages))
		for _, msg := range stream.Messages {
			streamEntries = append(streamEntries, StreamEntry{
				ID:     msg.ID,
				Values: msg.Values,
			})
		}
		entries[stream.Stream] = streamEntries
	}

	return entries, nil
}

// StreamRange retrieves entries from a Redis Stream within a range of IDs.
// This is useful for pagination and retrieving historical data.
//
// The start and end parameters define the ID range:
//   - "-" means the minimum ID in the stream
//   - "+" means the maximum ID in the stream
//   - Specific ID like "1234567890123-0"
//
// Count limits the number of entries returned. Use 0 for no limit.
//
// Example:
//
//	// Get all entries
//	entries, err := client.StreamRange(ctx, "events:user", "-", "+", 0)
//
//	// Get first 100 entries
//	entries, err := client.StreamRange(ctx, "events:user", "-", "+", 100)
//
//	// Get entries after specific ID
//	entries, err := client.StreamRange(ctx, "events:user", "1234567890123-0", "+", 50)
func (c *StateClient) StreamRange(ctx context.Context, stream, start, end string, count int64) ([]StreamEntry, error) {
	if stream == "" {
		return nil, fmt.Errorf("stream name cannot be empty")
	}

	if start == "" {
		start = "-"
	}

	if end == "" {
		end = "+"
	}

	result, err := c.client.XRange(ctx, stream, start, end).Result()
	if err != nil {
		return nil, fmt.Errorf("failed to read range from stream %s: %w", stream, err)
	}

	// Convert to StreamEntry format
	entries := make([]StreamEntry, 0, len(result))
	for _, msg := range result {
		entries = append(entries, StreamEntry{
			ID:     msg.ID,
			Values: msg.Values,
		})
	}

	return entries, nil
}

// StreamLen returns the number of entries in a Redis Stream.
//
// Example:
//
//	length, err := client.StreamLen(ctx, "events:user")
//	if err != nil {
//	    log.Fatalf("failed to get stream length: %v", err)
//	}
//	fmt.Printf("Stream has %d entries\n", length)
func (c *StateClient) StreamLen(ctx context.Context, stream string) (int64, error) {
	if stream == "" {
		return 0, fmt.Errorf("stream name cannot be empty")
	}

	length, err := c.client.XLen(ctx, stream).Result()
	if err != nil {
		return 0, fmt.Errorf("failed to get length of stream %s: %w", stream, err)
	}

	return length, nil
}

// StreamTrim removes entries from a Redis Stream to limit its size.
// This is useful for implementing retention policies and preventing unbounded growth.
//
// Returns the number of entries removed.
//
// Example:
//
//	// Keep only the latest 1000 entries (approximate)
//	opts := &StreamTrimOptions{
//	    MaxLen:      1000,
//	    Approximate: true,
//	}
//	removed, err := client.StreamTrim(ctx, "events:user", opts)
//
//	// Remove all entries older than a specific ID
//	opts := &StreamTrimOptions{
//	    MinID: "1234567890123-0",
//	}
//	removed, err := client.StreamTrim(ctx, "events:user", opts)
func (c *StateClient) StreamTrim(ctx context.Context, stream string, opts *StreamTrimOptions) (int64, error) {
	if stream == "" {
		return 0, fmt.Errorf("stream name cannot be empty")
	}

	if opts == nil {
		return 0, fmt.Errorf("trim options cannot be nil")
	}

	// Choose trimming strategy
	var count int64
	var err error

	if opts.MaxLen > 0 {
		// Trim by max length (approximate or exact)
		if opts.Approximate {
			count, err = c.client.XTrimMaxLenApprox(ctx, stream, opts.MaxLen, 0).Result()
		} else {
			count, err = c.client.XTrimMaxLen(ctx, stream, opts.MaxLen).Result()
		}
	} else if opts.MinID != "" {
		// Trim by minimum ID
		count, err = c.client.XTrimMinID(ctx, stream, opts.MinID).Result()
	} else {
		return 0, fmt.Errorf("either MaxLen or MinID must be specified")
	}

	if err != nil {
		return 0, fmt.Errorf("failed to trim stream %s: %w", stream, err)
	}

	return count, nil
}

// StreamDel deletes a Redis Stream and all its entries.
// This is a destructive operation that cannot be undone.
//
// Example:
//
//	err := client.StreamDel(ctx, "events:temp")
//	if err != nil {
//	    log.Fatalf("failed to delete stream: %v", err)
//	}
func (c *StateClient) StreamDel(ctx context.Context, stream string) error {
	if stream == "" {
		return fmt.Errorf("stream name cannot be empty")
	}

	result, err := c.client.Del(ctx, stream).Result()
	if err != nil {
		return fmt.Errorf("failed to delete stream %s: %w", stream, err)
	}

	if result == 0 {
		// Stream didn't exist, but that's not an error
		return nil
	}

	return nil
}

// StreamCreateGroup creates a consumer group for a Redis Stream.
// Consumer groups enable exactly-once message processing with multiple consumers.
//
// The startID parameter specifies where the group should begin reading:
//   - "0" to process all existing messages
//   - "$" to process only new messages
//   - Specific ID to start from that point
//
// The mkStream parameter, when true, creates the stream if it doesn't exist.
//
// This operation is idempotent - if the group already exists, it returns successfully
// without error (BUSYGROUP error is handled gracefully).
//
// Example:
//
//	// Create group to process all existing messages
//	err := client.StreamCreateGroup(ctx, "events:orders", "processors", "0", true)
//	if err != nil {
//	    log.Fatalf("failed to create consumer group: %v", err)
//	}
//
//	// Create group to process only new messages
//	err := client.StreamCreateGroup(ctx, "events:logs", "analytics", "$", true)
func (c *StateClient) StreamCreateGroup(ctx context.Context, stream, group, startID string, mkStream bool) error {
	if stream == "" {
		return fmt.Errorf("stream name cannot be empty")
	}

	if group == "" {
		return fmt.Errorf("group name cannot be empty")
	}

	if startID == "" {
		startID = "0"
	}

	// Build XGROUP CREATE command
	args := []interface{}{"XGROUP", "CREATE", stream, group, startID}
	if mkStream {
		args = append(args, "MKSTREAM")
	}

	err := c.client.Do(ctx, args...).Err()
	if err != nil {
		// Check if group already exists (BUSYGROUP error)
		if strings.Contains(err.Error(), "BUSYGROUP") {
			// Group already exists, which is fine (idempotent operation)
			return nil
		}
		return fmt.Errorf("failed to create consumer group %s for stream %s: %w", group, stream, err)
	}

	return nil
}

// StreamReadGroup reads messages from a Redis Stream using a consumer group.
// This enables exactly-once processing where multiple consumers can process messages
// concurrently, and each message is delivered to only one consumer.
//
// The lastID parameter controls which messages to read:
//   - ">" to read new messages never delivered to any consumer (most common)
//   - "0" to read all pending messages for this consumer
//   - Specific ID to read from that point
//
// Messages are not automatically acknowledged unless opts.NoAck is false.
// Use StreamAck to explicitly acknowledge message processing.
//
// Example:
//
//	opts := &ConsumerGroupOptions{
//	    Group:    "processors",
//	    Consumer: "worker-1",
//	    Count:    10,
//	    Block:    5 * time.Second,
//	    NoAck:    true, // Require explicit ACK
//	}
//
//	entries, err := client.StreamReadGroup(ctx, "events:orders", ">", opts)
//	if err != nil {
//	    log.Fatalf("failed to read from group: %v", err)
//	}
//
//	for _, entry := range entries {
//	    // Process message...
//	    if err := processMessage(entry); err != nil {
//	        continue // Will be retried via pending messages
//	    }
//	    // Acknowledge successful processing
//	    client.StreamAck(ctx, "events:orders", "processors", entry.ID)
//	}
func (c *StateClient) StreamReadGroup(ctx context.Context, stream, lastID string, opts *ConsumerGroupOptions) ([]StreamEntry, error) {
	if stream == "" {
		return nil, fmt.Errorf("stream name cannot be empty")
	}

	if opts == nil {
		return nil, fmt.Errorf("consumer group options cannot be nil")
	}

	if opts.Group == "" {
		return nil, fmt.Errorf("group name cannot be empty")
	}

	if opts.Consumer == "" {
		return nil, fmt.Errorf("consumer name cannot be empty")
	}

	if lastID == "" {
		lastID = ">"
	}

	// Set default count
	count := opts.Count
	if count == 0 {
		count = 10
	}

	// Honor the documented Block semantics: Block == 0 is non-blocking. As with
	// StreamRead, go-redis treats BLOCK 0 as "block forever", so a negative
	// value is required to omit the BLOCK option (gibson#410).
	block := opts.Block
	if block <= 0 {
		block = -1
	}

	args := &redis.XReadGroupArgs{
		Group:    opts.Group,
		Consumer: opts.Consumer,
		Streams:  []string{stream, lastID},
		Count:    count,
		Block:    block,
		NoAck:    opts.NoAck,
	}

	result, err := c.client.XReadGroup(ctx, args).Result()
	if err != nil {
		// XREADGROUP with block timeout returns redis.Nil, which is not an error
		if err == redis.Nil {
			return []StreamEntry{}, nil
		}
		return nil, fmt.Errorf("failed to read from consumer group %s: %w", opts.Group, err)
	}

	// Convert redis.XStream to StreamEntry format
	entries := make([]StreamEntry, 0)
	for _, xstream := range result {
		for _, msg := range xstream.Messages {
			entries = append(entries, StreamEntry{
				ID:     msg.ID,
				Values: msg.Values,
			})
		}
	}

	return entries, nil
}

// StreamAck acknowledges one or more messages in a consumer group.
// This marks the messages as successfully processed and removes them from
// the pending entries list (PEL).
//
// Acknowledging messages is essential for exactly-once processing to work correctly.
// Unacknowledged messages can be claimed by other consumers or reprocessed.
//
// Example:
//
//	// Acknowledge single message
//	err := client.StreamAck(ctx, "events:orders", "processors", "1234567890123-0")
//
//	// Acknowledge multiple messages
//	err := client.StreamAck(ctx, "events:orders", "processors",
//	    "1234567890123-0",
//	    "1234567890124-0",
//	    "1234567890125-0")
func (c *StateClient) StreamAck(ctx context.Context, stream, group string, ids ...string) error {
	if stream == "" {
		return fmt.Errorf("stream name cannot be empty")
	}

	if group == "" {
		return fmt.Errorf("group name cannot be empty")
	}

	if len(ids) == 0 {
		return fmt.Errorf("at least one message ID must be provided")
	}

	// Build args for XACK command
	args := make([]interface{}, 0, len(ids)+2)
	args = append(args, stream, group)
	for _, id := range ids {
		args = append(args, id)
	}

	count, err := c.client.XAck(ctx, stream, group, ids...).Result()
	if err != nil {
		return fmt.Errorf("failed to acknowledge messages in group %s: %w", group, err)
	}

	if count == 0 {
		// No messages were acknowledged (possibly already acked or don't exist)
		// This is not necessarily an error
	}

	return nil
}

// StreamPending retrieves information about pending (unacknowledged) messages
// in a consumer group. This is useful for monitoring stuck messages and
// implementing dead letter queues.
//
// The start and end parameters define the ID range to query:
//   - "-" means the minimum ID
//   - "+" means the maximum ID
//   - Specific IDs for a custom range
//
// The count parameter limits the number of results. Use 0 for no limit (returns all).
//
// If consumer is not empty, only pending messages for that consumer are returned.
//
// Example:
//
//	// Get all pending messages
//	pending, err := client.StreamPending(ctx, "events:orders", "processors", "-", "+", 100, "")
//	if err != nil {
//	    log.Fatalf("failed to get pending messages: %v", err)
//	}
//
//	for _, msg := range pending {
//	    if msg.IdleTime > 5*time.Minute {
//	        log.Printf("Message %s stuck for %v (consumer: %s)", msg.ID, msg.IdleTime, msg.Consumer)
//	        // Consider claiming or moving to dead letter queue
//	    }
//	}
func (c *StateClient) StreamPending(ctx context.Context, stream, group, start, end string, count int64, consumer string) ([]PendingMessage, error) {
	if stream == "" {
		return nil, fmt.Errorf("stream name cannot be empty")
	}

	if group == "" {
		return nil, fmt.Errorf("group name cannot be empty")
	}

	if start == "" {
		start = "-"
	}

	if end == "" {
		end = "+"
	}

	if count == 0 {
		count = 10
	}

	// Build XPENDING command
	args := &redis.XPendingExtArgs{
		Stream: stream,
		Group:  group,
		Start:  start,
		End:    end,
		Count:  count,
	}

	if consumer != "" {
		args.Consumer = consumer
	}

	result, err := c.client.XPendingExt(ctx, args).Result()
	if err != nil {
		if err == redis.Nil {
			return []PendingMessage{}, nil
		}
		return nil, fmt.Errorf("failed to get pending messages for group %s: %w", group, err)
	}

	// Convert to PendingMessage format
	messages := make([]PendingMessage, 0, len(result))
	for _, msg := range result {
		messages = append(messages, PendingMessage{
			ID:            msg.ID,
			Consumer:      msg.Consumer,
			IdleTime:      msg.Idle,
			DeliveryCount: msg.RetryCount,
		})
	}

	return messages, nil
}

// StreamClaim transfers ownership of pending messages from one consumer to another.
// This is useful for reprocessing stuck messages that have been idle for too long.
//
// The minIdleTime parameter specifies the minimum idle time required to claim a message.
// Only messages that have been pending for at least this duration can be claimed.
//
// Example:
//
//	// Find stuck messages
//	pending, err := client.StreamPending(ctx, "events:orders", "processors", "-", "+", 100, "")
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	// Claim messages idle for more than 5 minutes
//	stuckIDs := []string{}
//	for _, msg := range pending {
//	    if msg.IdleTime > 5*time.Minute {
//	        stuckIDs = append(stuckIDs, msg.ID)
//	    }
//	}
//
//	if len(stuckIDs) > 0 {
//	    claimed, err := client.StreamClaim(ctx, "events:orders", "processors",
//	        "worker-2", 5*time.Minute, stuckIDs...)
//	    if err != nil {
//	        log.Fatal(err)
//	    }
//	    // Process claimed messages...
//	}
func (c *StateClient) StreamClaim(ctx context.Context, stream, group, consumer string, minIdleTime time.Duration, ids ...string) ([]StreamEntry, error) {
	if stream == "" {
		return nil, fmt.Errorf("stream name cannot be empty")
	}

	if group == "" {
		return nil, fmt.Errorf("group name cannot be empty")
	}

	if consumer == "" {
		return nil, fmt.Errorf("consumer name cannot be empty")
	}

	if len(ids) == 0 {
		return nil, fmt.Errorf("at least one message ID must be provided")
	}

	args := &redis.XClaimArgs{
		Stream:   stream,
		Group:    group,
		Consumer: consumer,
		MinIdle:  minIdleTime,
		Messages: ids,
	}

	result, err := c.client.XClaim(ctx, args).Result()
	if err != nil {
		if err == redis.Nil {
			return []StreamEntry{}, nil
		}
		return nil, fmt.Errorf("failed to claim messages in group %s: %w", group, err)
	}

	// Convert to StreamEntry format
	entries := make([]StreamEntry, 0, len(result))
	for _, msg := range result {
		entries = append(entries, StreamEntry{
			ID:     msg.ID,
			Values: msg.Values,
		})
	}

	return entries, nil
}

// StreamSubscribe creates a real-time subscription to a Redis Stream.
// It returns a channel that receives new entries as they are added to the stream.
//
// The subscription runs in a goroutine and automatically handles:
//   - Blocking reads with reconnection on errors
//   - Graceful shutdown when context is cancelled
//   - Channel cleanup and closure
//
// The lastID parameter specifies where to start reading:
//   - "0" to read all existing entries
//   - "$" to read only new entries added after subscription
//   - Specific ID to read from after that entry
//
// The returned channel will be closed when:
//   - The context is cancelled
//   - An unrecoverable error occurs
//
// Example:
//
//	// Subscribe to new entries only
//	entryChan, err := client.StreamSubscribe(ctx, "events:user", "$")
//	if err != nil {
//	    log.Fatalf("failed to subscribe: %v", err)
//	}
//
//	for entry := range entryChan {
//	    fmt.Printf("Received entry %s: %+v\n", entry.ID, entry.Values)
//	}
func (c *StateClient) StreamSubscribe(ctx context.Context, stream, lastID string) (<-chan StreamEntry, error) {
	if stream == "" {
		return nil, fmt.Errorf("stream name cannot be empty")
	}

	if lastID == "" {
		lastID = "$"
	}

	entryChan := make(chan StreamEntry, 10) // Buffer to prevent blocking

	go func() {
		defer close(entryChan)

		currentID := lastID

		for {
			select {
			case <-ctx.Done():
				return
			default:
			}

			// Read new entries with blocking
			opts := &StreamReadOptions{
				LastID: currentID,
				Block:  5 * time.Second, // Block for up to 5 seconds
				Count:  100,             // Read up to 100 entries at once
			}

			entries, err := c.StreamRead(ctx, []string{stream}, opts)
			if err != nil {
				// Check if context was cancelled
				select {
				case <-ctx.Done():
					return
				default:
				}

				// Log and continue to next iteration. Per-command retries are
				// handled by go-redis's native MaxRetries (wired in
				// platform-clients v0.10.0 via RedisOptions.MaxRetries).
				continue
			}

			// Process entries
			streamEntries, ok := entries[stream]
			if !ok || len(streamEntries) == 0 {
				// No new entries, continue blocking read
				continue
			}

			// Send entries to channel
			for _, entry := range streamEntries {
				select {
				case entryChan <- entry:
					// Update last seen ID for next iteration
					currentID = entry.ID
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return entryChan, nil
}
