// Copyright 2026 Hack the Planet LLC
// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file in the repo root.

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"sort"
	"strings"
	"testing"
)

// TestNoGracefulNilInRequestPaths walks every request-path Go file in
// the operator and flags any `if X == nil { return ... }` pattern where
// the body silently returns success (return nil / return true, nil /
// return false, nil / return nil, nil) without recording an error.
//
// Why: the "one-code-path" PRD (deploy#186) forbids degraded-mode
// branches in request paths. Every dependency must be validated at
// startup (in cmd/main.go) — once the binary is running, every
// callsite assumes deps are non-nil. A silent skip on a missing dep
// produces a user-visible "Failed to load" with no log trail pointing
// at the dropped step. Real incidents traced to this exact class:
// tenant-operator#76 (broker-config skipped → every dashboard panel
// 412'd).
//
// The walker is intentionally narrow:
//   - condition must be `X == nil` (or `nil == X`)
//   - X must be a field selector (`s.deps.Foo`, `a.b.c`) or a bare
//     identifier — the "dependency" shape
//   - X's rightmost identifier must NOT match err/Err — we don't
//     want to flag legitimate "no error" branches like
//     `if err == nil { return nil }`
//   - the body must be a single ReturnStmt returning only nil-y
//     values (nil, true/false + nil, nil + nil)
//
// Scope: only files under `internal/` are walked. `cmd/` (startup
// wiring), test files, and generated files are excluded. Existing
// debt is tracked in `requestPathAllowlist`; new violations fail.
func TestNoGracefulNilInRequestPaths(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..")

	// Fixture subtest: assert walker correctness against known fixtures.
	// Synthetic fixtures live under cmd/testdata/scope/. The walker is
	// scope-aware: files whose path contains "/cmd/" are excluded; files
	// under "/internal/" are scanned.
	t.Run("fixtures", func(t *testing.T) {
		fixturesRoot := filepath.Join(filepath.Dir(thisFile), "testdata", "scope")

		findings := walkScopeForGracefulNil(t, fixturesRoot)

		// Expected: 2 illegal matches in
		// testdata/scope/internal/saga/flows/illegal_silent_skip.go.txt
		// and 0 legal matches under testdata/scope/cmd/.
		if want := 2; len(findings) != want {
			t.Errorf("fixture scan: got %d findings, want %d:\n%s",
				len(findings), want, strings.Join(findings, "\n"))
		}
		for _, f := range findings {
			if !strings.Contains(f, "illegal_silent_skip") {
				t.Errorf("fixture scan: unexpected finding (should only flag illegal_*): %s", f)
			}
			// scopeRel asserts the finding's path RELATIVE TO fixturesRoot
			// goes through internal/, not cmd/. The absolute path
			// naturally contains "/cmd/" (because the fixtures live under
			// cmd/testdata) — that's a real-repo artifact, not a leak.
			rel, err := filepath.Rel(fixturesRoot, strings.SplitN(f, ":", 2)[0])
			if err == nil && pathHasComponent(rel, "cmd") {
				t.Errorf("fixture scan: walker leaked into cmd/ scope: %s", f)
			}
		}
	})

	// Existing-debt allowlist. Each entry is a "<file>:<line>" coordinate
	// (relative path from repo root) where the request-path graceful-nil
	// branch is known but has not yet been ripped out by the
	// corresponding one-code-path slice. New findings (not on this list)
	// fail the test loud.
	//
	// Adding to this list is allowed ONLY with a linked follow-up issue
	// and a justification. Removing from this list is the goal.
	//
	// Generated by the first run of this test against main on 2026-05-17
	// after slices deploy#194/#196/#197/#198/#199/#195/#205 merged.
	// Remaining surfaces live in two classes:
	//   1. Optional billing capabilities (Stripe) whose follow-up is the
	//      stripe-billing-integration spec.
	//   2. Deprovision flows (teardown.go) that tolerate missing deps so
	//      a tenant can be deleted even if its sub-system was never
	//      provisioned. These are reasserted as hard requirements once
	//      the daemon-side guarantees land.
	//
	// Each line refers to the issue tracking its removal.
	// Reason codes (kept short to honour the 120-char line limit).
	// Long-form rationale documented in the comments above each block.
	// Removed in M7 (tenant-operator#95): stripeOpt, teardownTol, fgaShape, dpReq (saga).
	const (
		dpReq       = "predates dataplane-required hardening"
		httpDiscard = "HTTP helper: out=nil means discard body (caller convention, not dep)"
		ctorGuard   = "client constructor guard; reassert with constructor-inversion slice"
		k8sShape    = "k8s API may return nil map/slice; map-shape guard, not dep"
		veleroOpt   = "FinalBackup tenant-spec style; predates Velero-always-on"
		ctrlShim    = "controller-runtime cleanup-only reconcile tolerates nil"
		applyShim   = "ApplyOpts helper accepts nil dst as no-op"
		emitterOpt  = "emitter optional in early-boot; emitter-required follow-up"
		healthShim  = "health probe accepts nil client to mean unprobeable"
		recorderOpt = "event recorder always set by SetupWithManager; nil only in unit tests (best-effort obs)"
	)

	// CONTENT-KEYED (not line-keyed). Each key is "<relpath> :: <snippet>" —
	// the file path plus the rendered guard expression, NOT a line number.
	// This is deliberate: a line-keyed allowlist breaks every time anything
	// shifts line numbers (a license-header swap, an added import, a comment),
	// which has repeatedly reddened main for no real reason (gibson#1025/#1043/
	// #1044, the ELv2-header merge gibson#1041). Keying on the guard text makes
	// the allowlist immune to line shifts and file-internal moves.
	//
	// Trade-off: one entry tolerates that exact guard ANYWHERE in the file
	// (multiple identical guards in one file collapse to a single key). For a
	// "known-tolerated defensive guards" list that is acceptable — arguably
	// better, since you stop re-litigating the same pattern per occurrence.
	requestPathAllowlist := map[string]string{
		// FinalBackup — VeleroEnabled is a spec/cluster-topology flag, not a
		// dep-nil. K8sClient is always set from mgr. Delete after Velero-always-on.
		"internal/saga/flows/final_backup.go :: if s.deps.K8sClient == nil || !s.deps.VeleroEnabled { ... }": veleroOpt,

		// internal/dataplane/pipeline.go — sub-client optionality within the
		// pipeline provisioner; each sub-client (Postgres, Neo4j, Redis, Vector,
		// KEK) is optional by design. Follow-up: make each required after the
		// dataplane-required hardening spec ships.
		"internal/dataplane/pipeline.go :: if p.cfg.Postgres == nil { ... }":                   dpReq,
		"internal/dataplane/pipeline.go :: if p.cfg.Neo4j == nil { ... }":                      dpReq,
		"internal/dataplane/pipeline.go :: if p.cfg.Redis == nil { ... }":                      dpReq,
		"internal/dataplane/pipeline.go :: if p.cfg.Vector == nil { ... }":                     dpReq,
		"internal/dataplane/pipeline.go :: if p.cfg.KEK == nil { ... }":                        dpReq,
		"internal/dataplane/pipeline.go :: if p.cfg.K8sClient == nil { ... }":                  dpReq,
		"internal/dataplane/pipeline.go :: if tenant == nil || p.cfg.K8sClient == nil { ... }": dpReq,
		"internal/dataplane/pipeline.go :: if p.cfg.Recorder == nil || tenant == nil { ... }":  dpReq,

		// internal/clients/* — HTTP unmarshal helpers (caller passes out=nil to discard body)
		"internal/clients/fga/http.go :: if out == nil || len(raw) == 0 { ... }":                      httpDiscard,
		"internal/clients/zitadel/client.go :: if out == nil || len(raw) == 0 { ... }":                httpDiscard,
		"internal/clients/vault/client.go :: if out == nil { ... }":                                   httpDiscard,
		"internal/clients/vault/transit.go :: if out == nil { ... }":                                  httpDiscard,
		"internal/clients/signupprogress/redis.go :: if c == nil || c.rdb == nil { ... }":             ctorGuard,
		"internal/provision/entitlements_grpc_client.go :: if c == nil || c.transport == nil { ... }": ctorGuard,

		// Controller-runtime patterns
		"internal/controller/tenant_namespace.go :: if dst == nil { ... }": applyShim,

		// E8 declarative reconcilers — each emit*/event helper guards
		// `if r.Recorder == nil { return }`. Recorder is ALWAYS set in production
		// by SetupWithManager; the nil branch exists only for unit tests.
		"internal/controller/tenantdataplane_controller.go :: if r.Recorder == nil { ... }":      recorderOpt,
		"internal/controller/tenantsecretsbackend_controller.go :: if r.Recorder == nil { ... }": recorderOpt,
		"internal/controller/tenantidentity_controller.go :: if r.Recorder == nil { ... }":       recorderOpt,
		"internal/controller/tenantgrants_controller.go :: if r.Recorder == nil { ... }":         recorderOpt,

		// Audit emitter + health probes
		"internal/audit/emitter.go :: if e.cfg.RedisClient == nil { ... }": emitterOpt,
		"internal/health/downstream.go :: if c == nil { ... }":             healthShim,

		// Saga runner — k8s API may return nil maps/conditions from a freshly created object.
		"internal/saga/runner.go :: if conditions == nil { ... }":            k8sShape,
		"internal/saga/runner.go :: if annotations == nil { ... }":           k8sShape,
		"internal/saga/runner.go :: if a == nil || a.emitter == nil { ... }": emitterOpt,
	}

	// Real-code subtest: walk internal/ and fail on any new finding.
	t.Run("real_code", func(t *testing.T) {
		allFindings := walkDirForGracefulNil(t, filepath.Join(repoRoot, "internal"))
		sort.Strings(allFindings)

		var newFindings []string
		for _, f := range allFindings {
			if _, ok := requestPathAllowlist[contentKey(f, repoRoot)]; !ok {
				newFindings = append(newFindings, f)
			}
		}

		if len(newFindings) > 0 {
			t.Errorf("NEW graceful-nil branches in request paths (forbidden by one-code-path PRD deploy#186):\n%s\n\n"+
				"Each is a `if X == nil { return [...] nil }` pattern in a request-path file. The fix is one of:\n"+
				"  (1) Validate the dep at startup (cmd/main.go) so it can never be nil at request time.\n"+
				"  (2) If the skip is tenant-spec-aware, use the saga Step.Skip() predicate (which inspects only Tenant.Spec).\n"+
				"  (3) If this is a legitimate exception, add it to requestPathAllowlist with a linked follow-up issue.\n",
				strings.Join(newFindings, "\n"))
		}

		// Log allowlisted findings so future runs notice when one
		// disappears and the allowlist entry should be deleted.
		for coord, reason := range requestPathAllowlist {
			t.Logf("allowlisted: %s — %s", coord, reason)
		}
	})
}

// walkScopeForGracefulNil walks dir recursively, treating it like a
// fake repo root where path components include "cmd/" (excluded) and
// "internal/" (scanned). Used by the fixtures sub-test. Scope is
// evaluated relative to dir, so a real-world cmd/ ancestor in the
// absolute path is ignored.
func walkScopeForGracefulNil(t *testing.T, dir string) []string {
	t.Helper()
	var findings []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		// Accept both .go and .go.txt for fixtures.
		if !strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, ".go.txt") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		if pathHasComponent(rel, "cmd") {
			return nil
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		findings = append(findings, analyzeSource(t, path, string(src))...)
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", dir, err)
	}
	return findings
}

// walkDirForGracefulNil parses every non-test .go file under dir and
// returns "<file>:<line>: <snippet>" findings for each graceful-nil
// branch detected. Recurses into subdirectories.
func walkDirForGracefulNil(t *testing.T, dir string) []string {
	t.Helper()
	var findings []string

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			// Skip nested testdata trees that may live under internal/.
			if info.Name() == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		findings = append(findings, analyzeSource(t, path, string(src))...)
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", dir, err)
	}
	return findings
}

// pathHasComponent reports whether path contains the given directory
// component (after splitting on os.PathSeparator). Used to detect
// cmd/-scope files regardless of where the repo root is mounted.
func pathHasComponent(path, want string) bool {
	return slices.Contains(strings.Split(path, string(os.PathSeparator)), want)
}

// analyzeSource parses one Go source string and returns
// "<filename>:<line>: <snippet>" findings for each graceful-nil branch.
// Filename is used for reporting only; the parser does not read it.
func analyzeSource(t *testing.T, filename, src string) []string {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", filename, err)
	}

	var findings []string
	ast.Inspect(file, func(n ast.Node) bool {
		ifs, ok := n.(*ast.IfStmt)
		if !ok {
			return true
		}
		if !isDependencyNilCheck(ifs.Cond) {
			return true
		}
		if !isSilentReturnBody(ifs.Body) {
			return true
		}
		pos := fset.Position(ifs.Pos())
		snippet := renderIfHead(ifs, fset, src)
		findings = append(findings, fmt.Sprintf("%s:%d: %s", filename, pos.Line, snippet))
		return true
	})
	return findings
}

// isDependencyNilCheck reports whether expr is `X == nil` (or nil == X)
// where X is a field selector (s.deps.Foo, a.b, etc.) or a bare
// identifier, and the rightmost name doesn't look like an error
// variable. Also recurses through `||` / `&&` so
// `if s.X == nil || s.Y == nil { return nil }` still trips.
func isDependencyNilCheck(expr ast.Expr) bool {
	be, ok := expr.(*ast.BinaryExpr)
	if !ok {
		return false
	}

	if be.Op == token.LOR || be.Op == token.LAND {
		return isDependencyNilCheck(be.X) || isDependencyNilCheck(be.Y)
	}

	if be.Op != token.EQL {
		return false
	}
	var subject ast.Expr
	switch {
	case isNilIdent(be.Y):
		subject = be.X
	case isNilIdent(be.X):
		subject = be.Y
	default:
		return false
	}

	switch s := subject.(type) {
	case *ast.SelectorExpr:
		return !looksLikeError(s.Sel.Name)
	case *ast.Ident:
		return !looksLikeError(s.Name)
	default:
		return false
	}
}

// isSilentReturnBody reports whether body is a single `return ...`
// statement whose values are all nil-y: no real error, no non-nil
// data. Patterns matched:
//
//   - return                       (bare return; legal only for func())
//   - return nil
//   - return nil, nil
//   - return true, nil
//   - return false, nil
//
// We do NOT match `return err` / `return fmt.Errorf(...)` /
// `return false, fmt.Errorf(...)` — those are legitimate error
// propagation, not the anti-pattern.
//
// We require the return to be the ONLY statement in the body. A
// multi-stmt block that happens to start with a return-on-nil is
// unusual enough that flagging it could be a false positive. The
// actual anti-pattern is always "guard, then nothing else".
func isSilentReturnBody(body *ast.BlockStmt) bool {
	if body == nil || len(body.List) == 0 {
		return false
	}
	if len(body.List) != 1 {
		return false
	}
	r, ok := body.List[0].(*ast.ReturnStmt)
	if !ok {
		return false
	}
	return isNilyReturn(r)
}

// isNilyReturn reports whether r returns only nil-y values.
func isNilyReturn(r *ast.ReturnStmt) bool {
	if len(r.Results) == 0 {
		return true
	}
	for _, res := range r.Results {
		if !isNilOrBoolLiteral(res) {
			return false
		}
	}
	return true
}

// isNilOrBoolLiteral reports whether expr is the identifier `nil`,
// `true`, or `false`. Everything else (string literal, fmt.Errorf
// call, wrapped err, etc.) is meaningful.
func isNilOrBoolLiteral(expr ast.Expr) bool {
	id, ok := expr.(*ast.Ident)
	if !ok {
		return false
	}
	switch id.Name {
	case "nil", "true", "false":
		return true
	}
	return false
}

func isNilIdent(expr ast.Expr) bool {
	id, ok := expr.(*ast.Ident)
	return ok && id.Name == "nil"
}

// looksLikeError filters out err/Err/*Error names so we don't flag
// canonical `if err == nil { ... }` branches as the anti-pattern.
func looksLikeError(name string) bool {
	lower := strings.ToLower(name)
	return lower == "err" || strings.HasSuffix(lower, "err") || strings.HasSuffix(lower, "error")
}

// renderIfHead reads the source text for the `if X == nil` head line so
// the failure message includes the literal code.
func renderIfHead(ifs *ast.IfStmt, fset *token.FileSet, src string) string {
	start := fset.Position(ifs.Pos()).Offset
	end := fset.Position(ifs.Body.Lbrace).Offset
	if start < 0 || end < start || end > len(src) {
		return "<unrenderable>"
	}
	line := strings.TrimSpace(src[start:end])
	line = strings.ReplaceAll(line, "\n", " ")
	line = strings.ReplaceAll(line, "\t", " ")
	for strings.Contains(line, "  ") {
		line = strings.ReplaceAll(line, "  ", " ")
	}
	return line + " { ... }"
}

// repoRelCoord turns an absolute-path finding ("<abs>:<line>: <snip>")
// into a stable "<relative-path>:<line>" key used for allowlisting.
func repoRelCoord(finding, repoRoot string) string {
	// finding is "<abs path>:<line>: <snippet>". Strip the snippet first.
	parts := strings.SplitN(finding, ": ", 2)
	pathLine := parts[0]
	// pathLine is "<abs path>:<line>". Split on the last colon to
	// preserve any colons that might appear in the path itself.
	idx := strings.LastIndex(pathLine, ":")
	if idx < 0 {
		return pathLine
	}
	abs := pathLine[:idx]
	line := pathLine[idx+1:]
	if rel, err := filepath.Rel(repoRoot, abs); err == nil {
		return rel + ":" + line
	}
	return pathLine
}

// contentKey turns a finding ("<abs>:<line>: <snippet>") into the
// line-independent allowlist key "<relpath> :: <snippet>". Keying on the guard
// text instead of the line number makes the allowlist immune to line shifts
// (license headers, added imports/comments) and to file-internal moves.
func contentKey(finding, repoRoot string) string {
	relpath := repoRelCoord(finding, repoRoot) // "<relpath>:<line>"
	if i := strings.LastIndex(relpath, ":"); i >= 0 {
		relpath = relpath[:i]
	}
	var snippet string
	if parts := strings.SplitN(finding, ": ", 2); len(parts) == 2 {
		snippet = parts[1]
	}
	return relpath + " :: " + snippet
}
