package dataplane

// Vault per-tenant credential payloads. The operator marshals one of
// these structs and POSTs it to the canonical per-tenant Vault path
// (see VaultPathInfra* constants in credentials.go); the daemon reads
// the same path and unmarshals the same struct. The two processes
// share THIS file so the JSON shape cannot drift.
//
// Spec: tenant-provisioning-unification-phase2 Component 1, Requirement 1.

// PostgresCredentials is the payload at tenant/<id>/infra/postgres.
//
// The DSN field is the canonical libpq URL the daemon's pgxpool can dial
// directly — operator builds it once, daemon uses it unchanged. Other
// fields are preserved for diagnostics + future tooling that needs to
// reason about role/database separately.
type PostgresCredentials struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Database string `json:"database"`
	Role     string `json:"role"`
	Password string `json:"password"`
	DSN      string `json:"dsn"`
}

// Neo4jCredentials is the payload at tenant/<id>/infra/neo4j.
//
// Per spec Requirement 1.2, the password is generated by crypto/rand at
// provision time (NOT KEK-derived) so rotating MasterKEK does not affect
// Neo4j. The same password value is also written to the per-tenant K8s
// Secret consumed by the Neo4j pod's NEO4J_AUTH env.
type Neo4jCredentials struct {
	BoltURI  string `json:"bolt_uri"`
	Username string `json:"username"`
	Password string `json:"password"`
}

// RedisCredentials is the payload at tenant/<id>/infra/redis.
//
// DBIndex is the per-tenant logical-DB index assigned from the
// platform-wide master index hash (RedisIndexHashKey). Password is
// shared cluster-wide for the Redis instance — present here so the
// daemon doesn't need a separate config path.
type RedisCredentials struct {
	Addr     string `json:"addr"`
	DBIndex  int    `json:"db_index"`
	Password string `json:"password"`
}

// VectorCredentials is the payload at tenant/<id>/infra/vector.
type VectorCredentials struct {
	URL        string `json:"url"`
	Collection string `json:"collection"`
	APIKey     string `json:"api_key"`
}

// LangfuseCredentials is the payload at tenant/<id>/infra/langfuse.
//
// Replaces the legacy `langfuse-creds` K8s Secret in the tenant
// namespace per spec Requirement 1.5.
type LangfuseCredentials struct {
	ProjectID string `json:"project_id"`
	PublicKey string `json:"public_key"`
	SecretKey string `json:"secret_key"`
	Host      string `json:"host"`
}
