---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connector-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gibson.zeroroot.ai
  resources:
  - connectorinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gibson.zeroroot.ai
  resources:
  - connectorinstances/finalizers
  verbs:
  - update
- apiGroups:
  - gibson.zeroroot.ai
  resources:
  - connectorinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpremoteproxies
  - mcpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
