// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/daemon/agentconsole/v1/agentconsole.proto

package agentconsolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentConsoleService_ListRunningAgents_FullMethodName = "/gibson.daemon.agentconsole.v1.AgentConsoleService/ListRunningAgents"
	AgentConsoleService_StreamAgentEvents_FullMethodName = "/gibson.daemon.agentconsole.v1.AgentConsoleService/StreamAgentEvents"
)

// AgentConsoleServiceClient is the client API for AgentConsoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentConsoleService is the daemon's read-only, tenant-scoped view of the
// agents running RIGHT NOW and their live structured events (ADR-0016 S11,
// gibson#1599). While a sandboxed agent runs, the launcher tees the agent's
// opencode NDJSON output into the daemon's in-memory registry; this service
// exposes it. It backs the dashboard's live agent console (S12).
//
// The daemon resolves the caller's tenant server-side and reads only that
// tenant's running instances. A subscriber can enumerate EVERY running instance
// for its tenant and follow EACH one independently. A run id owned by another
// tenant returns NOT_FOUND, never data — the isolation boundary is enforced
// server-side, never by the client. There is NO input/write path: this is a
// pure read surface, and each stream ends when its run reaches a terminal state.
//
// It mirrors LogsService / WorldService: daemon-local, tenant-scoped
// observability, read through Envoy + ext-authz. Every RPC is ext-authz-gated
// via the tenant member relation.
type AgentConsoleServiceClient interface {
	// ListRunningAgents enumerates the caller-tenant's currently running agent
	// instances. The tenant scope is derived server-side from the authenticated
	// identity; the client never supplies it, and the result never includes
	// another tenant's instances.
	ListRunningAgents(ctx context.Context, in *ListRunningAgentsRequest, opts ...grpc.CallOption) (*ListRunningAgentsResponse, error)
	// StreamAgentEvents streams one running instance's live structured events by
	// run id. The run id is resolved within the caller's tenant scope; a run id
	// the tenant does not own returns NOT_FOUND, indistinguishable from one that
	// never existed. The stream ends when the run reaches a terminal state.
	StreamAgentEvents(ctx context.Context, in *StreamAgentEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error)
}

type agentConsoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentConsoleServiceClient(cc grpc.ClientConnInterface) AgentConsoleServiceClient {
	return &agentConsoleServiceClient{cc}
}

func (c *agentConsoleServiceClient) ListRunningAgents(ctx context.Context, in *ListRunningAgentsRequest, opts ...grpc.CallOption) (*ListRunningAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunningAgentsResponse)
	err := c.cc.Invoke(ctx, AgentConsoleService_ListRunningAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConsoleServiceClient) StreamAgentEvents(ctx context.Context, in *StreamAgentEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentConsoleService_ServiceDesc.Streams[0], AgentConsoleService_StreamAgentEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAgentEventsRequest, AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentConsoleService_StreamAgentEventsClient = grpc.ServerStreamingClient[AgentEvent]

// AgentConsoleServiceServer is the server API for AgentConsoleService service.
// All implementations must embed UnimplementedAgentConsoleServiceServer
// for forward compatibility.
//
// AgentConsoleService is the daemon's read-only, tenant-scoped view of the
// agents running RIGHT NOW and their live structured events (ADR-0016 S11,
// gibson#1599). While a sandboxed agent runs, the launcher tees the agent's
// opencode NDJSON output into the daemon's in-memory registry; this service
// exposes it. It backs the dashboard's live agent console (S12).
//
// The daemon resolves the caller's tenant server-side and reads only that
// tenant's running instances. A subscriber can enumerate EVERY running instance
// for its tenant and follow EACH one independently. A run id owned by another
// tenant returns NOT_FOUND, never data — the isolation boundary is enforced
// server-side, never by the client. There is NO input/write path: this is a
// pure read surface, and each stream ends when its run reaches a terminal state.
//
// It mirrors LogsService / WorldService: daemon-local, tenant-scoped
// observability, read through Envoy + ext-authz. Every RPC is ext-authz-gated
// via the tenant member relation.
type AgentConsoleServiceServer interface {
	// ListRunningAgents enumerates the caller-tenant's currently running agent
	// instances. The tenant scope is derived server-side from the authenticated
	// identity; the client never supplies it, and the result never includes
	// another tenant's instances.
	ListRunningAgents(context.Context, *ListRunningAgentsRequest) (*ListRunningAgentsResponse, error)
	// StreamAgentEvents streams one running instance's live structured events by
	// run id. The run id is resolved within the caller's tenant scope; a run id
	// the tenant does not own returns NOT_FOUND, indistinguishable from one that
	// never existed. The stream ends when the run reaches a terminal state.
	StreamAgentEvents(*StreamAgentEventsRequest, grpc.ServerStreamingServer[AgentEvent]) error
	mustEmbedUnimplementedAgentConsoleServiceServer()
}

// UnimplementedAgentConsoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentConsoleServiceServer struct{}

func (UnimplementedAgentConsoleServiceServer) ListRunningAgents(context.Context, *ListRunningAgentsRequest) (*ListRunningAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRunningAgents not implemented")
}
func (UnimplementedAgentConsoleServiceServer) StreamAgentEvents(*StreamAgentEventsRequest, grpc.ServerStreamingServer[AgentEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamAgentEvents not implemented")
}
func (UnimplementedAgentConsoleServiceServer) mustEmbedUnimplementedAgentConsoleServiceServer() {}
func (UnimplementedAgentConsoleServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentConsoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentConsoleServiceServer will
// result in compilation errors.
type UnsafeAgentConsoleServiceServer interface {
	mustEmbedUnimplementedAgentConsoleServiceServer()
}

func RegisterAgentConsoleServiceServer(s grpc.ServiceRegistrar, srv AgentConsoleServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentConsoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentConsoleService_ServiceDesc, srv)
}

func _AgentConsoleService_ListRunningAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunningAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConsoleServiceServer).ListRunningAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConsoleService_ListRunningAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConsoleServiceServer).ListRunningAgents(ctx, req.(*ListRunningAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConsoleService_StreamAgentEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentConsoleServiceServer).StreamAgentEvents(m, &grpc.GenericServerStream[StreamAgentEventsRequest, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentConsoleService_StreamAgentEventsServer = grpc.ServerStreamingServer[AgentEvent]

// AgentConsoleService_ServiceDesc is the grpc.ServiceDesc for AgentConsoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentConsoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.daemon.agentconsole.v1.AgentConsoleService",
	HandlerType: (*AgentConsoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRunningAgents",
			Handler:    _AgentConsoleService_ListRunningAgents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAgentEvents",
			Handler:       _AgentConsoleService_StreamAgentEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gibson/daemon/agentconsole/v1/agentconsole.proto",
}
