apiVersion: gibson.zeroroot.ai/v1alpha1
kind: TenantMember
metadata:
  labels:
    app.kubernetes.io/name: tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenantmember-sample
spec:
  # TODO(user): Add fields here
