// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/daemon/operator/v1/operator.proto

package daemonoperatorv1

import (
	context "context"
	v1 "github.com/zeroroot-ai/gibson/internal/server/daemon/api/gibson/tenant/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonOperatorService_WriteAccessTuples_FullMethodName             = "/gibson.daemon.operator.v1.DaemonOperatorService/WriteAccessTuples"
	DaemonOperatorService_UpsertTenantQuota_FullMethodName             = "/gibson.daemon.operator.v1.DaemonOperatorService/UpsertTenantQuota"
	DaemonOperatorService_ListFeatureTuples_FullMethodName             = "/gibson.daemon.operator.v1.DaemonOperatorService/ListFeatureTuples"
	DaemonOperatorService_SeedCatalogTenantEnabled_FullMethodName      = "/gibson.daemon.operator.v1.DaemonOperatorService/SeedCatalogTenantEnabled"
	DaemonOperatorService_EmitAuditEvent_FullMethodName                = "/gibson.daemon.operator.v1.DaemonOperatorService/EmitAuditEvent"
	DaemonOperatorService_SetTenantZitadelOrg_FullMethodName           = "/gibson.daemon.operator.v1.DaemonOperatorService/SetTenantZitadelOrg"
	DaemonOperatorService_ListPendingTenantProvisioning_FullMethodName = "/gibson.daemon.operator.v1.DaemonOperatorService/ListPendingTenantProvisioning"
	DaemonOperatorService_EnqueueTenantProvisioning_FullMethodName     = "/gibson.daemon.operator.v1.DaemonOperatorService/EnqueueTenantProvisioning"
	DaemonOperatorService_AckTenantProvisioned_FullMethodName          = "/gibson.daemon.operator.v1.DaemonOperatorService/AckTenantProvisioned"
	DaemonOperatorService_SetAgentEnrollmentLimits_FullMethodName      = "/gibson.daemon.operator.v1.DaemonOperatorService/SetAgentEnrollmentLimits"
	DaemonOperatorService_ReportTenantStatus_FullMethodName            = "/gibson.daemon.operator.v1.DaemonOperatorService/ReportTenantStatus"
	DaemonOperatorService_ListPendingTenantOps_FullMethodName          = "/gibson.daemon.operator.v1.DaemonOperatorService/ListPendingTenantOps"
	DaemonOperatorService_AckTenantOp_FullMethodName                   = "/gibson.daemon.operator.v1.DaemonOperatorService/AckTenantOp"
	DaemonOperatorService_RevokeConnectorGrant_FullMethodName          = "/gibson.daemon.operator.v1.DaemonOperatorService/RevokeConnectorGrant"
	DaemonOperatorService_GetConnectorAuthStatus_FullMethodName        = "/gibson.daemon.operator.v1.DaemonOperatorService/GetConnectorAuthStatus"
	DaemonOperatorService_GetBeliefTrainingData_FullMethodName         = "/gibson.daemon.operator.v1.DaemonOperatorService/GetBeliefTrainingData"
	DaemonOperatorService_StoreBeliefArtifact_FullMethodName           = "/gibson.daemon.operator.v1.DaemonOperatorService/StoreBeliefArtifact"
	DaemonOperatorService_ListDesiredConnectors_FullMethodName         = "/gibson.daemon.operator.v1.DaemonOperatorService/ListDesiredConnectors"
	DaemonOperatorService_ReportConnectorStatus_FullMethodName         = "/gibson.daemon.operator.v1.DaemonOperatorService/ReportConnectorStatus"
	DaemonOperatorService_AdoptConnector_FullMethodName                = "/gibson.daemon.operator.v1.DaemonOperatorService/AdoptConnector"
	DaemonOperatorService_GetConnectorCredential_FullMethodName        = "/gibson.daemon.operator.v1.DaemonOperatorService/GetConnectorCredential"
)

// DaemonOperatorServiceClient is the client API for DaemonOperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonOperatorService provides strictly ZD-internal operator operations on
// the Gibson daemon. It is the post-ADR-0058 successor to the deleted
// PlatformOperatorService, carrying only the operator-only RPCs that have no
// customer surface. Customer-callable RPCs from the former admin services were
// promoted to DaemonService / TenantService in the OSS SDK (sdk#205).
//
// Every RPC is protected at the transport layer by SPIFFE mTLS and restricted
// to callers holding the "platform_operator" FGA relation on
// system_tenant:_system.
type DaemonOperatorServiceClient interface {
	// WriteAccessTuples atomically adds and/or deletes FGA tuples on behalf of
	// an authenticated caller.
	WriteAccessTuples(ctx context.Context, in *WriteAccessTuplesRequest, opts ...grpc.CallOption) (*WriteAccessTuplesResponse, error)
	// UpsertTenantQuota writes the tenant's runtime quota record to Postgres.
	// Called by the operator's reconcile loop after resolving the plan.
	UpsertTenantQuota(ctx context.Context, in *UpsertTenantQuotaRequest, opts ...grpc.CallOption) (*UpsertTenantQuotaResponse, error)
	// ListFeatureTuples enumerates the tenant feature tuples currently set.
	ListFeatureTuples(ctx context.Context, in *ListFeatureTuplesRequest, opts ...grpc.CallOption) (*ListFeatureTuplesResponse, error)
	// SeedCatalogTenantEnabled writes tenant_enabled tuples for all platform-enabled items.
	SeedCatalogTenantEnabled(ctx context.Context, in *SeedCatalogTenantEnabledRequest, opts ...grpc.CallOption) (*SeedCatalogTenantEnabledResponse, error)
	// EmitAuditEvent writes the audit record of a change that an operator
	// workload makes outside the daemon, for example a tenant namespace, a
	// Velero backup or an FGA grant of the tenant-operator. The daemon writes
	// the record to Postgres before it answers, so the caller makes the change
	// only after the record exists (ADR-0113, gibson#583).
	EmitAuditEvent(ctx context.Context, in *EmitAuditEventRequest, opts ...grpc.CallOption) (*EmitAuditEventResponse, error)
	// SetTenantZitadelOrg seeds the daemon's tenant -> Zitadel-organization-id
	// mapping. Called by the tenant-operator (the lifecycle coordinator) when it
	// provisions a tenant's per-tenant Zitadel org during standup, and on
	// backfill/reconcile.
	//
	// The daemon cannot read Kubernetes (ADR-0023), so it cannot resolve a
	// tenant's per-tenant Zitadel org id from Tenant.Status.ZitadelOrgID itself.
	// The operator owns that org id and hands it to the daemon here. The daemon
	// persists it so that gibson.tenant.v1.MembershipService can write the
	// Zitadel half of human membership (add/remove org member) for granular
	// member operations, without a K8s read or a token-claim dependency
	// (ADR-0093: Zitadel owns users and tenant roles, one tenant for each
	// person).
	//
	// Idempotent: re-seeding the same (tenant_id, zitadel_org_id) is a no-op;
	// a changed org id overwrites the prior mapping.
	SetTenantZitadelOrg(ctx context.Context, in *SetTenantZitadelOrgRequest, opts ...grpc.CallOption) (*SetTenantZitadelOrgResponse, error)
	// ListPendingTenantProvisioning returns the daemon-owned queue of tenants
	// awaiting Tenant-CR creation. The daemon's Signup handler enqueues one row
	// per self-serve signup once it has provisioned the founding-owner Zitadel
	// user (gibson#812); the tenant-operator's reconcile loop drains the queue by
	// creating the Tenant CR for each pending record, then AckTenantProvisioned.
	//
	// ADR-0023: the daemon never touches Kubernetes — it only reads its Postgres
	// queue here. The operator (which holds `tenants` create RBAC) creates the
	// Tenant CR. Idempotent and safe to poll: returns only rows still in
	// status=pending.
	ListPendingTenantProvisioning(ctx context.Context, in *ListPendingTenantProvisioningRequest, opts ...grpc.CallOption) (*ListPendingTenantProvisioningResponse, error)
	// EnqueueTenantProvisioning inserts a pending tenant-provisioning op into the
	// daemon's tenant_admin_ops queue — the same idempotent INSERT that
	// gibson.tenant.v1.AdminTenantService/AdminProvisionTenant performs, but on
	// this WORKLOAD-AUTHENTICATED operator surface instead of the human-facing
	// admin surface (gibson#1496).
	//
	// Why this exists: AdminProvisionTenant is gated by a session-revocation
	// check that only an interactive human login satisfies, so a headless
	// self-hosted install can never call it. This RPC lets the tenant-operator
	// seed the FIRST tenant with its own SPIFFE identity — no user, no session —
	// after which the existing ListPendingTenantProvisioning drain provisions it
	// exactly as a signup-originated op. Idempotent on tenant_id: an already
	// pending provision op returns already_existed=true and no new row.
	EnqueueTenantProvisioning(ctx context.Context, in *EnqueueTenantProvisioningRequest, opts ...grpc.CallOption) (*EnqueueTenantProvisioningResponse, error)
	// AckTenantProvisioned marks a pending-provisioning record done so it is not
	// re-created on the next reconcile pass. The operator calls this AFTER it has
	// ensured the Tenant CR exists (create or already-present), so a crash
	// between create and ack simply re-lists the row and the operator's
	// existence-check makes the re-create a no-op. Idempotent: acking an
	// already-done or unknown tenant_id is a no-op success.
	AckTenantProvisioned(ctx context.Context, in *AckTenantProvisionedRequest, opts ...grpc.CallOption) (*AckTenantProvisionedResponse, error)
	// SetAgentEnrollmentLimits records the runtime cap an AgentEnrollment
	// declares (spec.maxRuntime) so the daemon can bound that agent's
	// sandboxed runs. The daemon cannot read the CR itself (ADR-0023), so the
	// tenant-operator reports it on every enrollment pass. Idempotent upsert.
	SetAgentEnrollmentLimits(ctx context.Context, in *SetAgentEnrollmentLimitsRequest, opts ...grpc.CallOption) (*SetAgentEnrollmentLimitsResponse, error)
	ReportTenantStatus(ctx context.Context, in *ReportTenantStatusRequest, opts ...grpc.CallOption) (*ReportTenantStatusResponse, error)
	// ListPendingTenantOps returns the daemon-owned queue of admin tenant CRUD
	// operations (provision/update/delete) awaiting application to the Tenant CR.
	// The dashboard's AdminTenantService enqueues one row per platform-admin CRUD
	// action; the tenant-operator's reconcile loop drains the queue by applying
	// each op to the Tenant CR (create / patch spec / delete), then AckTenantOp.
	//
	// ADR-0023: the daemon never touches Kubernetes — it only reads its Postgres
	// queue here. The operator (which holds `tenants` create/update/delete RBAC)
	// applies the op. Idempotent and safe to poll: returns only rows still
	// status=pending, in created_at order so a tenant's ops apply in sequence.
	ListPendingTenantOps(ctx context.Context, in *ListPendingTenantOpsRequest, opts ...grpc.CallOption) (*ListPendingTenantOpsResponse, error)
	// AckTenantOp marks a pending admin-op record done so it is not re-applied on
	// the next reconcile pass. The operator calls this AFTER it has applied the op
	// to the Tenant CR (create/patch/delete, all idempotent), so a crash between
	// apply and ack simply re-lists the row and the operator's idempotent apply
	// makes the re-apply a no-op. Idempotent: acking an already-done or unknown
	// op_id is a no-op success.
	AckTenantOp(ctx context.Context, in *AckTenantOpRequest, opts ...grpc.CallOption) (*AckTenantOpResponse, error)
	// RevokeConnectorGrant revokes a tenant's connector grant on behalf of the
	// connector-operator's ConnectorInstance finalizer. Deleting a connector
	// must revoke the vendor grant and remove the Grant and access-token secrets
	// from the tenant store; only the daemon holds a secret-store client, so the
	// operator asks it over the SPIFFE direct-dial path (ADR-0002). Same
	// semantics as gibson.tenant.v1.ConnectorAuthService.RevokeConnectorGrant,
	// with the tenant carried explicitly: best-effort vendor revocation, then
	// local deletion, idempotent.
	RevokeConnectorGrant(ctx context.Context, in *RevokeConnectorGrantRequest, opts ...grpc.CallOption) (*v1.RevokeConnectorGrantResponse, error)
	// GetConnectorAuthStatus reports one tenant connector's grant and token
	// state to the connector-operator, so the ConnectorInstance carries a
	// Degraded condition instead of a silent Active when the credential is
	// dead (ADR-0061 decision 4).
	//
	// Only the daemon holds a secret-store client, so only the daemon knows
	// whether a grant still refreshes. The operator owns the CR status and
	// cannot read the store, so it pulls the reason from here on every
	// reconcile pass, exactly as the finalizer pulls the revoke. The response
	// is the same view the dashboard reads through
	// gibson.tenant.v1.ConnectorAuthService, with the tenant carried
	// explicitly. It never returns credential material.
	GetConnectorAuthStatus(ctx context.Context, in *GetConnectorAuthStatusRequest, opts ...grpc.CallOption) (*GetConnectorAuthStatusResponse, error)
	// GetBeliefTrainingData returns the training data of one tenant from its
	// World: one row for each observed host, and the outcome counts of each
	// edge type (ADR-0106, gibson#788). The belief trainer of that tenant calls
	// it over SPIFFE mTLS. The handler serves only the trainer identity of the
	// tenant in the request, spiffe://<trust domain>/trainer/<tenant_id>.
	GetBeliefTrainingData(ctx context.Context, in *GetBeliefTrainingDataRequest, opts ...grpc.CallOption) (*GetBeliefTrainingDataResponse, error)
	// StoreBeliefArtifact stores the two artifacts of one fit as the next
	// version of one tenant, with the state candidate (ADR-0106, gibson#788).
	// The quality gate decides which version becomes current. The handler
	// serves only the trainer identity of the tenant in the request.
	StoreBeliefArtifact(ctx context.Context, in *StoreBeliefArtifactRequest, opts ...grpc.CallOption) (*StoreBeliefArtifactResponse, error)
	// ListDesiredConnectors returns every (tenant, connector) pair a tenant
	// enabled (gibson#662), with the fields of the catalog entry that the
	// ConnectorInstance needs. The connector operator pulls it and converges
	// the ConnectorInstances. The daemon holds the desired state in Postgres
	// and makes no Kubernetes call (ADR-0023). A row whose connector left the
	// catalog is not in the answer.
	ListDesiredConnectors(ctx context.Context, in *ListDesiredConnectorsRequest, opts ...grpc.CallOption) (*ListDesiredConnectorsResponse, error)
	// ReportConnectorStatus records the state of one tenant connector, as the
	// connector operator reads it from the ConnectorInstance. A report for a
	// pair no tenant enabled changes nothing.
	ReportConnectorStatus(ctx context.Context, in *ReportConnectorStatusRequest, opts ...grpc.CallOption) (*ReportConnectorStatusResponse, error)
	// AdoptConnector records a connector that a tenant enabled before the
	// daemon kept the desired state (gibson#662). The connector operator calls
	// it once for each ConnectorInstance that the daemon wrote in the past. A
	// pair that is already recorded stays as it is.
	AdoptConnector(ctx context.Context, in *AdoptConnectorRequest, opts ...grpc.CallOption) (*AdoptConnectorResponse, error)
	// GetConnectorCredential returns the content of the connector-cred Secret of
	// one tenant connector: the "authorization" header with the short-lived
	// access token, and each declared static credential (gibson#663). It never
	// returns a refresh token or a Grant. The connector operator writes the
	// Secret. The handler serves only the direct-dial SPIFFE peer of the
	// connector operator, and refuses each other caller, also a caller with a
	// platform_operator token through the edge.
	GetConnectorCredential(ctx context.Context, in *GetConnectorCredentialRequest, opts ...grpc.CallOption) (*GetConnectorCredentialResponse, error)
}

type daemonOperatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonOperatorServiceClient(cc grpc.ClientConnInterface) DaemonOperatorServiceClient {
	return &daemonOperatorServiceClient{cc}
}

func (c *daemonOperatorServiceClient) WriteAccessTuples(ctx context.Context, in *WriteAccessTuplesRequest, opts ...grpc.CallOption) (*WriteAccessTuplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAccessTuplesResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_WriteAccessTuples_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) UpsertTenantQuota(ctx context.Context, in *UpsertTenantQuotaRequest, opts ...grpc.CallOption) (*UpsertTenantQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTenantQuotaResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_UpsertTenantQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) ListFeatureTuples(ctx context.Context, in *ListFeatureTuplesRequest, opts ...grpc.CallOption) (*ListFeatureTuplesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeatureTuplesResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_ListFeatureTuples_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) SeedCatalogTenantEnabled(ctx context.Context, in *SeedCatalogTenantEnabledRequest, opts ...grpc.CallOption) (*SeedCatalogTenantEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedCatalogTenantEnabledResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_SeedCatalogTenantEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) EmitAuditEvent(ctx context.Context, in *EmitAuditEventRequest, opts ...grpc.CallOption) (*EmitAuditEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitAuditEventResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_EmitAuditEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) SetTenantZitadelOrg(ctx context.Context, in *SetTenantZitadelOrgRequest, opts ...grpc.CallOption) (*SetTenantZitadelOrgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTenantZitadelOrgResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_SetTenantZitadelOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) ListPendingTenantProvisioning(ctx context.Context, in *ListPendingTenantProvisioningRequest, opts ...grpc.CallOption) (*ListPendingTenantProvisioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingTenantProvisioningResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_ListPendingTenantProvisioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) EnqueueTenantProvisioning(ctx context.Context, in *EnqueueTenantProvisioningRequest, opts ...grpc.CallOption) (*EnqueueTenantProvisioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueTenantProvisioningResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_EnqueueTenantProvisioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) AckTenantProvisioned(ctx context.Context, in *AckTenantProvisionedRequest, opts ...grpc.CallOption) (*AckTenantProvisionedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckTenantProvisionedResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_AckTenantProvisioned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) SetAgentEnrollmentLimits(ctx context.Context, in *SetAgentEnrollmentLimitsRequest, opts ...grpc.CallOption) (*SetAgentEnrollmentLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAgentEnrollmentLimitsResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_SetAgentEnrollmentLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) ReportTenantStatus(ctx context.Context, in *ReportTenantStatusRequest, opts ...grpc.CallOption) (*ReportTenantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTenantStatusResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_ReportTenantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) ListPendingTenantOps(ctx context.Context, in *ListPendingTenantOpsRequest, opts ...grpc.CallOption) (*ListPendingTenantOpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingTenantOpsResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_ListPendingTenantOps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) AckTenantOp(ctx context.Context, in *AckTenantOpRequest, opts ...grpc.CallOption) (*AckTenantOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckTenantOpResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_AckTenantOp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) RevokeConnectorGrant(ctx context.Context, in *RevokeConnectorGrantRequest, opts ...grpc.CallOption) (*v1.RevokeConnectorGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RevokeConnectorGrantResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_RevokeConnectorGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) GetConnectorAuthStatus(ctx context.Context, in *GetConnectorAuthStatusRequest, opts ...grpc.CallOption) (*GetConnectorAuthStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectorAuthStatusResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_GetConnectorAuthStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) GetBeliefTrainingData(ctx context.Context, in *GetBeliefTrainingDataRequest, opts ...grpc.CallOption) (*GetBeliefTrainingDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBeliefTrainingDataResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_GetBeliefTrainingData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) StoreBeliefArtifact(ctx context.Context, in *StoreBeliefArtifactRequest, opts ...grpc.CallOption) (*StoreBeliefArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreBeliefArtifactResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_StoreBeliefArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) ListDesiredConnectors(ctx context.Context, in *ListDesiredConnectorsRequest, opts ...grpc.CallOption) (*ListDesiredConnectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDesiredConnectorsResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_ListDesiredConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) ReportConnectorStatus(ctx context.Context, in *ReportConnectorStatusRequest, opts ...grpc.CallOption) (*ReportConnectorStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportConnectorStatusResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_ReportConnectorStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) AdoptConnector(ctx context.Context, in *AdoptConnectorRequest, opts ...grpc.CallOption) (*AdoptConnectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptConnectorResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_AdoptConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonOperatorServiceClient) GetConnectorCredential(ctx context.Context, in *GetConnectorCredentialRequest, opts ...grpc.CallOption) (*GetConnectorCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectorCredentialResponse)
	err := c.cc.Invoke(ctx, DaemonOperatorService_GetConnectorCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonOperatorServiceServer is the server API for DaemonOperatorService service.
// All implementations must embed UnimplementedDaemonOperatorServiceServer
// for forward compatibility.
//
// DaemonOperatorService provides strictly ZD-internal operator operations on
// the Gibson daemon. It is the post-ADR-0058 successor to the deleted
// PlatformOperatorService, carrying only the operator-only RPCs that have no
// customer surface. Customer-callable RPCs from the former admin services were
// promoted to DaemonService / TenantService in the OSS SDK (sdk#205).
//
// Every RPC is protected at the transport layer by SPIFFE mTLS and restricted
// to callers holding the "platform_operator" FGA relation on
// system_tenant:_system.
type DaemonOperatorServiceServer interface {
	// WriteAccessTuples atomically adds and/or deletes FGA tuples on behalf of
	// an authenticated caller.
	WriteAccessTuples(context.Context, *WriteAccessTuplesRequest) (*WriteAccessTuplesResponse, error)
	// UpsertTenantQuota writes the tenant's runtime quota record to Postgres.
	// Called by the operator's reconcile loop after resolving the plan.
	UpsertTenantQuota(context.Context, *UpsertTenantQuotaRequest) (*UpsertTenantQuotaResponse, error)
	// ListFeatureTuples enumerates the tenant feature tuples currently set.
	ListFeatureTuples(context.Context, *ListFeatureTuplesRequest) (*ListFeatureTuplesResponse, error)
	// SeedCatalogTenantEnabled writes tenant_enabled tuples for all platform-enabled items.
	SeedCatalogTenantEnabled(context.Context, *SeedCatalogTenantEnabledRequest) (*SeedCatalogTenantEnabledResponse, error)
	// EmitAuditEvent writes the audit record of a change that an operator
	// workload makes outside the daemon, for example a tenant namespace, a
	// Velero backup or an FGA grant of the tenant-operator. The daemon writes
	// the record to Postgres before it answers, so the caller makes the change
	// only after the record exists (ADR-0113, gibson#583).
	EmitAuditEvent(context.Context, *EmitAuditEventRequest) (*EmitAuditEventResponse, error)
	// SetTenantZitadelOrg seeds the daemon's tenant -> Zitadel-organization-id
	// mapping. Called by the tenant-operator (the lifecycle coordinator) when it
	// provisions a tenant's per-tenant Zitadel org during standup, and on
	// backfill/reconcile.
	//
	// The daemon cannot read Kubernetes (ADR-0023), so it cannot resolve a
	// tenant's per-tenant Zitadel org id from Tenant.Status.ZitadelOrgID itself.
	// The operator owns that org id and hands it to the daemon here. The daemon
	// persists it so that gibson.tenant.v1.MembershipService can write the
	// Zitadel half of human membership (add/remove org member) for granular
	// member operations, without a K8s read or a token-claim dependency
	// (ADR-0093: Zitadel owns users and tenant roles, one tenant for each
	// person).
	//
	// Idempotent: re-seeding the same (tenant_id, zitadel_org_id) is a no-op;
	// a changed org id overwrites the prior mapping.
	SetTenantZitadelOrg(context.Context, *SetTenantZitadelOrgRequest) (*SetTenantZitadelOrgResponse, error)
	// ListPendingTenantProvisioning returns the daemon-owned queue of tenants
	// awaiting Tenant-CR creation. The daemon's Signup handler enqueues one row
	// per self-serve signup once it has provisioned the founding-owner Zitadel
	// user (gibson#812); the tenant-operator's reconcile loop drains the queue by
	// creating the Tenant CR for each pending record, then AckTenantProvisioned.
	//
	// ADR-0023: the daemon never touches Kubernetes — it only reads its Postgres
	// queue here. The operator (which holds `tenants` create RBAC) creates the
	// Tenant CR. Idempotent and safe to poll: returns only rows still in
	// status=pending.
	ListPendingTenantProvisioning(context.Context, *ListPendingTenantProvisioningRequest) (*ListPendingTenantProvisioningResponse, error)
	// EnqueueTenantProvisioning inserts a pending tenant-provisioning op into the
	// daemon's tenant_admin_ops queue — the same idempotent INSERT that
	// gibson.tenant.v1.AdminTenantService/AdminProvisionTenant performs, but on
	// this WORKLOAD-AUTHENTICATED operator surface instead of the human-facing
	// admin surface (gibson#1496).
	//
	// Why this exists: AdminProvisionTenant is gated by a session-revocation
	// check that only an interactive human login satisfies, so a headless
	// self-hosted install can never call it. This RPC lets the tenant-operator
	// seed the FIRST tenant with its own SPIFFE identity — no user, no session —
	// after which the existing ListPendingTenantProvisioning drain provisions it
	// exactly as a signup-originated op. Idempotent on tenant_id: an already
	// pending provision op returns already_existed=true and no new row.
	EnqueueTenantProvisioning(context.Context, *EnqueueTenantProvisioningRequest) (*EnqueueTenantProvisioningResponse, error)
	// AckTenantProvisioned marks a pending-provisioning record done so it is not
	// re-created on the next reconcile pass. The operator calls this AFTER it has
	// ensured the Tenant CR exists (create or already-present), so a crash
	// between create and ack simply re-lists the row and the operator's
	// existence-check makes the re-create a no-op. Idempotent: acking an
	// already-done or unknown tenant_id is a no-op success.
	AckTenantProvisioned(context.Context, *AckTenantProvisionedRequest) (*AckTenantProvisionedResponse, error)
	// SetAgentEnrollmentLimits records the runtime cap an AgentEnrollment
	// declares (spec.maxRuntime) so the daemon can bound that agent's
	// sandboxed runs. The daemon cannot read the CR itself (ADR-0023), so the
	// tenant-operator reports it on every enrollment pass. Idempotent upsert.
	SetAgentEnrollmentLimits(context.Context, *SetAgentEnrollmentLimitsRequest) (*SetAgentEnrollmentLimitsResponse, error)
	ReportTenantStatus(context.Context, *ReportTenantStatusRequest) (*ReportTenantStatusResponse, error)
	// ListPendingTenantOps returns the daemon-owned queue of admin tenant CRUD
	// operations (provision/update/delete) awaiting application to the Tenant CR.
	// The dashboard's AdminTenantService enqueues one row per platform-admin CRUD
	// action; the tenant-operator's reconcile loop drains the queue by applying
	// each op to the Tenant CR (create / patch spec / delete), then AckTenantOp.
	//
	// ADR-0023: the daemon never touches Kubernetes — it only reads its Postgres
	// queue here. The operator (which holds `tenants` create/update/delete RBAC)
	// applies the op. Idempotent and safe to poll: returns only rows still
	// status=pending, in created_at order so a tenant's ops apply in sequence.
	ListPendingTenantOps(context.Context, *ListPendingTenantOpsRequest) (*ListPendingTenantOpsResponse, error)
	// AckTenantOp marks a pending admin-op record done so it is not re-applied on
	// the next reconcile pass. The operator calls this AFTER it has applied the op
	// to the Tenant CR (create/patch/delete, all idempotent), so a crash between
	// apply and ack simply re-lists the row and the operator's idempotent apply
	// makes the re-apply a no-op. Idempotent: acking an already-done or unknown
	// op_id is a no-op success.
	AckTenantOp(context.Context, *AckTenantOpRequest) (*AckTenantOpResponse, error)
	// RevokeConnectorGrant revokes a tenant's connector grant on behalf of the
	// connector-operator's ConnectorInstance finalizer. Deleting a connector
	// must revoke the vendor grant and remove the Grant and access-token secrets
	// from the tenant store; only the daemon holds a secret-store client, so the
	// operator asks it over the SPIFFE direct-dial path (ADR-0002). Same
	// semantics as gibson.tenant.v1.ConnectorAuthService.RevokeConnectorGrant,
	// with the tenant carried explicitly: best-effort vendor revocation, then
	// local deletion, idempotent.
	RevokeConnectorGrant(context.Context, *RevokeConnectorGrantRequest) (*v1.RevokeConnectorGrantResponse, error)
	// GetConnectorAuthStatus reports one tenant connector's grant and token
	// state to the connector-operator, so the ConnectorInstance carries a
	// Degraded condition instead of a silent Active when the credential is
	// dead (ADR-0061 decision 4).
	//
	// Only the daemon holds a secret-store client, so only the daemon knows
	// whether a grant still refreshes. The operator owns the CR status and
	// cannot read the store, so it pulls the reason from here on every
	// reconcile pass, exactly as the finalizer pulls the revoke. The response
	// is the same view the dashboard reads through
	// gibson.tenant.v1.ConnectorAuthService, with the tenant carried
	// explicitly. It never returns credential material.
	GetConnectorAuthStatus(context.Context, *GetConnectorAuthStatusRequest) (*GetConnectorAuthStatusResponse, error)
	// GetBeliefTrainingData returns the training data of one tenant from its
	// World: one row for each observed host, and the outcome counts of each
	// edge type (ADR-0106, gibson#788). The belief trainer of that tenant calls
	// it over SPIFFE mTLS. The handler serves only the trainer identity of the
	// tenant in the request, spiffe://<trust domain>/trainer/<tenant_id>.
	GetBeliefTrainingData(context.Context, *GetBeliefTrainingDataRequest) (*GetBeliefTrainingDataResponse, error)
	// StoreBeliefArtifact stores the two artifacts of one fit as the next
	// version of one tenant, with the state candidate (ADR-0106, gibson#788).
	// The quality gate decides which version becomes current. The handler
	// serves only the trainer identity of the tenant in the request.
	StoreBeliefArtifact(context.Context, *StoreBeliefArtifactRequest) (*StoreBeliefArtifactResponse, error)
	// ListDesiredConnectors returns every (tenant, connector) pair a tenant
	// enabled (gibson#662), with the fields of the catalog entry that the
	// ConnectorInstance needs. The connector operator pulls it and converges
	// the ConnectorInstances. The daemon holds the desired state in Postgres
	// and makes no Kubernetes call (ADR-0023). A row whose connector left the
	// catalog is not in the answer.
	ListDesiredConnectors(context.Context, *ListDesiredConnectorsRequest) (*ListDesiredConnectorsResponse, error)
	// ReportConnectorStatus records the state of one tenant connector, as the
	// connector operator reads it from the ConnectorInstance. A report for a
	// pair no tenant enabled changes nothing.
	ReportConnectorStatus(context.Context, *ReportConnectorStatusRequest) (*ReportConnectorStatusResponse, error)
	// AdoptConnector records a connector that a tenant enabled before the
	// daemon kept the desired state (gibson#662). The connector operator calls
	// it once for each ConnectorInstance that the daemon wrote in the past. A
	// pair that is already recorded stays as it is.
	AdoptConnector(context.Context, *AdoptConnectorRequest) (*AdoptConnectorResponse, error)
	// GetConnectorCredential returns the content of the connector-cred Secret of
	// one tenant connector: the "authorization" header with the short-lived
	// access token, and each declared static credential (gibson#663). It never
	// returns a refresh token or a Grant. The connector operator writes the
	// Secret. The handler serves only the direct-dial SPIFFE peer of the
	// connector operator, and refuses each other caller, also a caller with a
	// platform_operator token through the edge.
	GetConnectorCredential(context.Context, *GetConnectorCredentialRequest) (*GetConnectorCredentialResponse, error)
	mustEmbedUnimplementedDaemonOperatorServiceServer()
}

// UnimplementedDaemonOperatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonOperatorServiceServer struct{}

func (UnimplementedDaemonOperatorServiceServer) WriteAccessTuples(context.Context, *WriteAccessTuplesRequest) (*WriteAccessTuplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAccessTuples not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) UpsertTenantQuota(context.Context, *UpsertTenantQuotaRequest) (*UpsertTenantQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTenantQuota not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) ListFeatureTuples(context.Context, *ListFeatureTuplesRequest) (*ListFeatureTuplesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeatureTuples not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) SeedCatalogTenantEnabled(context.Context, *SeedCatalogTenantEnabledRequest) (*SeedCatalogTenantEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeedCatalogTenantEnabled not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) EmitAuditEvent(context.Context, *EmitAuditEventRequest) (*EmitAuditEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitAuditEvent not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) SetTenantZitadelOrg(context.Context, *SetTenantZitadelOrgRequest) (*SetTenantZitadelOrgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTenantZitadelOrg not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) ListPendingTenantProvisioning(context.Context, *ListPendingTenantProvisioningRequest) (*ListPendingTenantProvisioningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingTenantProvisioning not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) EnqueueTenantProvisioning(context.Context, *EnqueueTenantProvisioningRequest) (*EnqueueTenantProvisioningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueTenantProvisioning not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) AckTenantProvisioned(context.Context, *AckTenantProvisionedRequest) (*AckTenantProvisionedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckTenantProvisioned not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) SetAgentEnrollmentLimits(context.Context, *SetAgentEnrollmentLimitsRequest) (*SetAgentEnrollmentLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentEnrollmentLimits not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) ReportTenantStatus(context.Context, *ReportTenantStatusRequest) (*ReportTenantStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTenantStatus not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) ListPendingTenantOps(context.Context, *ListPendingTenantOpsRequest) (*ListPendingTenantOpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingTenantOps not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) AckTenantOp(context.Context, *AckTenantOpRequest) (*AckTenantOpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckTenantOp not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) RevokeConnectorGrant(context.Context, *RevokeConnectorGrantRequest) (*v1.RevokeConnectorGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeConnectorGrant not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) GetConnectorAuthStatus(context.Context, *GetConnectorAuthStatusRequest) (*GetConnectorAuthStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectorAuthStatus not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) GetBeliefTrainingData(context.Context, *GetBeliefTrainingDataRequest) (*GetBeliefTrainingDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBeliefTrainingData not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) StoreBeliefArtifact(context.Context, *StoreBeliefArtifactRequest) (*StoreBeliefArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreBeliefArtifact not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) ListDesiredConnectors(context.Context, *ListDesiredConnectorsRequest) (*ListDesiredConnectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDesiredConnectors not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) ReportConnectorStatus(context.Context, *ReportConnectorStatusRequest) (*ReportConnectorStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportConnectorStatus not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) AdoptConnector(context.Context, *AdoptConnectorRequest) (*AdoptConnectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdoptConnector not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) GetConnectorCredential(context.Context, *GetConnectorCredentialRequest) (*GetConnectorCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectorCredential not implemented")
}
func (UnimplementedDaemonOperatorServiceServer) mustEmbedUnimplementedDaemonOperatorServiceServer() {}
func (UnimplementedDaemonOperatorServiceServer) testEmbeddedByValue()                               {}

// UnsafeDaemonOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonOperatorServiceServer will
// result in compilation errors.
type UnsafeDaemonOperatorServiceServer interface {
	mustEmbedUnimplementedDaemonOperatorServiceServer()
}

func RegisterDaemonOperatorServiceServer(s grpc.ServiceRegistrar, srv DaemonOperatorServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonOperatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonOperatorService_ServiceDesc, srv)
}

func _DaemonOperatorService_WriteAccessTuples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAccessTuplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).WriteAccessTuples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_WriteAccessTuples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).WriteAccessTuples(ctx, req.(*WriteAccessTuplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_UpsertTenantQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTenantQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).UpsertTenantQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_UpsertTenantQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).UpsertTenantQuota(ctx, req.(*UpsertTenantQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_ListFeatureTuples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeatureTuplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).ListFeatureTuples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_ListFeatureTuples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).ListFeatureTuples(ctx, req.(*ListFeatureTuplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_SeedCatalogTenantEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedCatalogTenantEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).SeedCatalogTenantEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_SeedCatalogTenantEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).SeedCatalogTenantEnabled(ctx, req.(*SeedCatalogTenantEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_EmitAuditEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitAuditEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).EmitAuditEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_EmitAuditEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).EmitAuditEvent(ctx, req.(*EmitAuditEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_SetTenantZitadelOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTenantZitadelOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).SetTenantZitadelOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_SetTenantZitadelOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).SetTenantZitadelOrg(ctx, req.(*SetTenantZitadelOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_ListPendingTenantProvisioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingTenantProvisioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).ListPendingTenantProvisioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_ListPendingTenantProvisioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).ListPendingTenantProvisioning(ctx, req.(*ListPendingTenantProvisioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_EnqueueTenantProvisioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueTenantProvisioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).EnqueueTenantProvisioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_EnqueueTenantProvisioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).EnqueueTenantProvisioning(ctx, req.(*EnqueueTenantProvisioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_AckTenantProvisioned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckTenantProvisionedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).AckTenantProvisioned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_AckTenantProvisioned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).AckTenantProvisioned(ctx, req.(*AckTenantProvisionedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_SetAgentEnrollmentLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentEnrollmentLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).SetAgentEnrollmentLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_SetAgentEnrollmentLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).SetAgentEnrollmentLimits(ctx, req.(*SetAgentEnrollmentLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_ReportTenantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTenantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).ReportTenantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_ReportTenantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).ReportTenantStatus(ctx, req.(*ReportTenantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_ListPendingTenantOps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingTenantOpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).ListPendingTenantOps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_ListPendingTenantOps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).ListPendingTenantOps(ctx, req.(*ListPendingTenantOpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_AckTenantOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckTenantOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).AckTenantOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_AckTenantOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).AckTenantOp(ctx, req.(*AckTenantOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_RevokeConnectorGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeConnectorGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).RevokeConnectorGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_RevokeConnectorGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).RevokeConnectorGrant(ctx, req.(*RevokeConnectorGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_GetConnectorAuthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectorAuthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).GetConnectorAuthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_GetConnectorAuthStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).GetConnectorAuthStatus(ctx, req.(*GetConnectorAuthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_GetBeliefTrainingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeliefTrainingDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).GetBeliefTrainingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_GetBeliefTrainingData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).GetBeliefTrainingData(ctx, req.(*GetBeliefTrainingDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_StoreBeliefArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreBeliefArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).StoreBeliefArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_StoreBeliefArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).StoreBeliefArtifact(ctx, req.(*StoreBeliefArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_ListDesiredConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDesiredConnectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).ListDesiredConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_ListDesiredConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).ListDesiredConnectors(ctx, req.(*ListDesiredConnectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_ReportConnectorStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportConnectorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).ReportConnectorStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_ReportConnectorStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).ReportConnectorStatus(ctx, req.(*ReportConnectorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_AdoptConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).AdoptConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_AdoptConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).AdoptConnector(ctx, req.(*AdoptConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonOperatorService_GetConnectorCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectorCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonOperatorServiceServer).GetConnectorCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonOperatorService_GetConnectorCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonOperatorServiceServer).GetConnectorCredential(ctx, req.(*GetConnectorCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonOperatorService_ServiceDesc is the grpc.ServiceDesc for DaemonOperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonOperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.daemon.operator.v1.DaemonOperatorService",
	HandlerType: (*DaemonOperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteAccessTuples",
			Handler:    _DaemonOperatorService_WriteAccessTuples_Handler,
		},
		{
			MethodName: "UpsertTenantQuota",
			Handler:    _DaemonOperatorService_UpsertTenantQuota_Handler,
		},
		{
			MethodName: "ListFeatureTuples",
			Handler:    _DaemonOperatorService_ListFeatureTuples_Handler,
		},
		{
			MethodName: "SeedCatalogTenantEnabled",
			Handler:    _DaemonOperatorService_SeedCatalogTenantEnabled_Handler,
		},
		{
			MethodName: "EmitAuditEvent",
			Handler:    _DaemonOperatorService_EmitAuditEvent_Handler,
		},
		{
			MethodName: "SetTenantZitadelOrg",
			Handler:    _DaemonOperatorService_SetTenantZitadelOrg_Handler,
		},
		{
			MethodName: "ListPendingTenantProvisioning",
			Handler:    _DaemonOperatorService_ListPendingTenantProvisioning_Handler,
		},
		{
			MethodName: "EnqueueTenantProvisioning",
			Handler:    _DaemonOperatorService_EnqueueTenantProvisioning_Handler,
		},
		{
			MethodName: "AckTenantProvisioned",
			Handler:    _DaemonOperatorService_AckTenantProvisioned_Handler,
		},
		{
			MethodName: "SetAgentEnrollmentLimits",
			Handler:    _DaemonOperatorService_SetAgentEnrollmentLimits_Handler,
		},
		{
			MethodName: "ReportTenantStatus",
			Handler:    _DaemonOperatorService_ReportTenantStatus_Handler,
		},
		{
			MethodName: "ListPendingTenantOps",
			Handler:    _DaemonOperatorService_ListPendingTenantOps_Handler,
		},
		{
			MethodName: "AckTenantOp",
			Handler:    _DaemonOperatorService_AckTenantOp_Handler,
		},
		{
			MethodName: "RevokeConnectorGrant",
			Handler:    _DaemonOperatorService_RevokeConnectorGrant_Handler,
		},
		{
			MethodName: "GetConnectorAuthStatus",
			Handler:    _DaemonOperatorService_GetConnectorAuthStatus_Handler,
		},
		{
			MethodName: "GetBeliefTrainingData",
			Handler:    _DaemonOperatorService_GetBeliefTrainingData_Handler,
		},
		{
			MethodName: "StoreBeliefArtifact",
			Handler:    _DaemonOperatorService_StoreBeliefArtifact_Handler,
		},
		{
			MethodName: "ListDesiredConnectors",
			Handler:    _DaemonOperatorService_ListDesiredConnectors_Handler,
		},
		{
			MethodName: "ReportConnectorStatus",
			Handler:    _DaemonOperatorService_ReportConnectorStatus_Handler,
		},
		{
			MethodName: "AdoptConnector",
			Handler:    _DaemonOperatorService_AdoptConnector_Handler,
		},
		{
			MethodName: "GetConnectorCredential",
			Handler:    _DaemonOperatorService_GetConnectorCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/daemon/operator/v1/operator.proto",
}
