#!/usr/bin/env bash
# check-build-tags-selected.sh — CI guard: no build tag that nothing ever builds.
#
# Spec: gibson#1280.
#
# THE PROBLEM
# -----------
# 34 test files under tests/e2e/ sat behind `//go:build e2e` and NOTHING ever
# selected that tag: `Makefile:BUILD_TAGS` is empty, so `make test` /
# `make test-race` never compiled them, and no workflow passed `-tags e2e`.
# They could not even fail to compile. They rotted for months, and hid a real
# defect: tests/e2e/secrets/non_plugin_deny_test.go asserted a PERMISSION_DENIED
# that ComponentService/GetCredential never implemented. That assertion would
# have failed on its first run. It was found by reading the code instead.
#
# Five more tags were in the same state: test_fixtures, openbao_integration,
# openbao_smoke, llm_integration, integration_spire.
#
# THE INVARIANT
# -------------
# Every positive build tag appearing in a `//go:build` line somewhere in this
# module must appear in the `vet-tags` matrix of .github/workflows/go-ci.yml,
# which runs `go vet -tags=<leg> ./...` per leg on BOTH the pull_request and
# merge_group lanes. So go-ci.yml IS the allowlist — there is no second list to
# keep in sync, and adding a new tag without wiring it up fails the build.
#
# Compile-level signal is the floor, not the ceiling. Whether a tagged suite
# also RUNS is a separate question per tag (`integration` runs via
# `make test-integration`; `setec_integration` via e2e-setec-roundtrip.yml on
# the KVM runner; `e2e` needs a live cluster and does not run yet — tracked
# separately). This guard only guarantees the code still builds.
#
# NEGATED TAGS are not checked. A file constrained `//go:build !embedder_tests`
# is part of the DEFAULT build, so the untagged matrix leg already compiles it.
#
# Exit codes:
#   0  Every build tag is selected by a matrix leg.
#   1  One or more tags are selected by nothing.
#   2  Operational error (could not parse the matrix).
#
# Self-test mode (--selftest):
#   Drives the scanner over a synthetic source tree in a temp dir (via
#   BUILD_TAGS_SCAN_ROOT) against the REAL go-ci.yml matrix, asserting it accepts
#   a selected tag and rejects an unselected one. Writes nothing into the repo.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Both overridable so --selftest can drive the scanner over a synthetic tree
# without writing anything into the working copy.
SCAN_ROOT="${BUILD_TAGS_SCAN_ROOT:-${REPO_ROOT}}"
WORKFLOW="${BUILD_TAGS_WORKFLOW:-${REPO_ROOT}/.github/workflows/go-ci.yml}"

GUARD_NAME="check-build-tags-selected"

log_info() { echo "[${GUARD_NAME}] INFO:  $*"; }
log_err() { echo "[${GUARD_NAME}] ERROR: $*" >&2; }

# Tokens that are never repo-defined build tags: GOOS/GOARCH, toolchain
# pseudo-tags, and the code-generator convention tag.
is_builtin_token() {
    case "$1" in
    linux | darwin | windows | freebsd | openbsd | netbsd | dragonfly | solaris | plan9 | aix | ios | android | js | wasip1)
        return 0
        ;;
    amd64 | arm | arm64 | 386 | ppc64 | ppc64le | mips* | riscv64 | s390x | loong64 | wasm)
        return 0
        ;;
    cgo | unix | race | msan | asan | gc | gccgo | purego | ignore)
        return 0
        ;;
    go1.* | goexperiment.*)
        return 0
        ;;
    ignore_autogenerated)
        return 0
        ;;
    esac
    return 1
}

# ---------------------------------------------------------------------------
# Parse the vet-tags matrix out of go-ci.yml.
# ---------------------------------------------------------------------------
parse_selected_tags() {
    awk '
        /^  vet-tags:/            { in_job = 1; next }
        in_job && /^  [a-zA-Z]/   { in_job = 0 }
        in_job && /^ +build_tags:/ { in_list = 1; next }
        in_list {
            if ($0 ~ /^ +- *"/) {
                line = $0
                sub(/^ +- *"/, "", line)
                sub(/" *$/, "", line)
                print line
                next
            }
            in_list = 0
        }
    ' "${WORKFLOW}" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' | sort -u
}

# ---------------------------------------------------------------------------
# Collect every positive build tag used in the module.
# ---------------------------------------------------------------------------
collect_used_tags() {
    grep -rhE '^//go:build ' --include='*.go' "${SCAN_ROOT}" 2>/dev/null |
        sed 's#^//go:build ##' |
        tr '()&|' '    ' |
        tr ' ' '\n' |
        sed 's/^[[:space:]]*//;s/[[:space:]]*$//' |
        grep -v '^$' |
        grep -v '^!' |
        sort -u
}

# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--selftest" ]]; then
    TMP="$(mktemp -d)"
    # shellcheck disable=SC2064
    trap "rm -rf '${TMP}'" EXIT

    run_scanner() {
        BUILD_TAGS_SCAN_ROOT="${TMP}" bash "${BASH_SOURCE[0]}" >/dev/null 2>&1
    }

    log_info "Self-test: a file under a SELECTED tag must be accepted..."
    printf '//go:build e2e\n\npackage fixture\n' >"${TMP}/ok.go"
    if ! run_scanner; then
        log_err "SELFTEST FAILED: scanner rejected a file under a selected tag."
        exit 1
    fi

    log_info "Self-test: a file under an UNSELECTED tag must be rejected..."
    printf '//go:build a_tag_nothing_selects\n\npackage fixture\n' >"${TMP}/bad.go"
    if run_scanner; then
        log_err "SELFTEST FAILED: scanner accepted a tag no matrix leg selects."
        exit 1
    fi

    log_info "Self-test: a NEGATED tag must be ignored (it is in the default build)..."
    rm -f "${TMP}/bad.go"
    printf '//go:build !a_tag_nothing_selects\n\npackage fixture\n' >"${TMP}/neg.go"
    if ! run_scanner; then
        log_err "SELFTEST FAILED: scanner flagged a negated tag."
        exit 1
    fi

    log_info "SELFTEST PASSED."
    exit 0
fi

# ---------------------------------------------------------------------------
# Main scan
# ---------------------------------------------------------------------------
if [[ ! -f "${WORKFLOW}" ]]; then
    log_err "missing ${WORKFLOW}"
    exit 2
fi

mapfile -t SELECTED < <(parse_selected_tags)
if [[ ${#SELECTED[@]} -eq 0 ]]; then
    log_err "parsed zero tags out of the vet-tags matrix in .github/workflows/go-ci.yml."
    log_err "The matrix moved or changed shape and this parser no longer sees it."
    log_err "Refusing to pass vacuously — fix parse_selected_tags() in this script."
    exit 2
fi

mapfile -t USED < <(collect_used_tags)

is_selected() {
    local needle="$1" t
    for t in "${SELECTED[@]}"; do
        [[ "${t}" == "${needle}" ]] && return 0
    done
    return 1
}

VIOLATIONS=0
for tag in "${USED[@]}"; do
    is_builtin_token "${tag}" && continue
    if ! is_selected "${tag}"; then
        log_err "build tag '${tag}' is selected by no vet-tags matrix leg — nothing ever compiles these files:"
        grep -rlE "^//go:build .*\b${tag}\b" --include='*.go' "${SCAN_ROOT}" 2>/dev/null |
            sed "s#^${SCAN_ROOT}/#    #" | head -10
        VIOLATIONS=$((VIOLATIONS + 1))
    fi
done

if [[ "${VIOLATIONS}" -gt 0 ]]; then
    log_err "${VIOLATIONS} build tag(s) that nothing builds (gibson#1280)."
    log_err "Add the tag as a leg of the vet-tags matrix in .github/workflows/go-ci.yml"
    log_err "so the files at least have to compile, then decide separately whether the"
    log_err "suite should also run somewhere."
    exit 1
fi

log_info "All ${#USED[@]} build tag(s) in use are selected by a vet-tags matrix leg."
log_info "Selected: ${SELECTED[*]}"
exit 0
