#!/usr/bin/env bash
#
# check-proto-breaking.sh: the daemon-local protos do not break the wire.
#
# ADR-0028, rule 5: CI runs `buf breaking` with the WIRE_JSON rule for the
# gibson protos (gibson#698). WIRE_JSON refuses a change that breaks a binary
# or a JSON reader: a renumbered field, a changed type, a renamed JSON field, a
# removed field whose number is not reserved.
#
# The protos under internal/server/daemon/api import gibson/auth/v1/options.proto
# from the pinned sdk, so a plain `buf breaking` cannot resolve them. This
# script builds one image for HEAD and one for the base, each in a temporary
# workspace with the sdk protos beside it, and compares the two images.
#
# Usage:
#   scripts/check-proto-breaking.sh            # HEAD against origin/$BASE (default main)
#   scripts/check-proto-breaking.sh --selftest # prove that the check can fail
#
# BUF names the buf binary (default: buf on PATH).
set -euo pipefail

BUF="${BUF:-buf}"
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"
PROTO_DIR="internal/server/daemon/api"
BASE="${BASE:-${GITHUB_BASE_REF:-main}}"

log() { echo "[check-proto-breaking] $*"; }

sdk_dir() {
  go mod download github.com/zeroroot-ai/sdk >/dev/null
  go list -m -f '{{.Dir}}' github.com/zeroroot-ai/sdk
}

# image <tree root> <output file>: build the image of the daemon-local protos.
image() {
  local tree="$1" out="$2" ws
  ws="$(mktemp -d)"
  ln -s "$tree/$PROTO_DIR" "$ws/gibson-local"
  ln -s "$SDK_DIR/api/proto" "$ws/sdk-proto"
  printf 'version: v2\nmodules:\n  - path: gibson-local\n  - path: sdk-proto\n    excludes:\n      - sdk-proto/google\ndeps:\n  - buf.build/bufbuild/protovalidate\n' > "$ws/buf.yaml"
  cp "$ROOT/buf.lock" "$ws/buf.lock" 2>/dev/null || printf '# Generated by buf. DO NOT EDIT.\nversion: v2\ndeps:\n  - name: buf.build/bufbuild/protovalidate\n    commit: 50325440f8f24053b047484a6bf60b76\n    digest: b5:74cb6f5c0853c3c10aafc701614194bbd63326bdb8ef4068214454b8894b03ba4113e04b3a33a8321cdf05336e37db4dc14a5e2495db8462566914f36086ba31\n' > "$ws/buf.lock"
  (cd "$ws" && "$BUF" build gibson-local -o "$out")
  rm -rf "$ws"
}

# compare <head image> <base image>: run the WIRE_JSON rule.
compare() {
  "$BUF" breaking "$1" --against "$2" --exclude-imports \
    --config '{"version":"v2","breaking":{"use":["WIRE_JSON"]}}'
}

SDK_DIR="$(sdk_dir)"
tmp="$(mktemp -d)"
trap 'git -C "$ROOT" worktree remove --force "$tmp/base" >/dev/null 2>&1 || true; rm -rf "$tmp"' EXIT

if [ "${1:-}" = "--selftest" ]; then
  # A copy of HEAD's protos with one field renumbered must fail, for its reason.
  mkdir -p "$tmp/head" "$tmp/bad"
  cp -r "$PROTO_DIR" --parents "$tmp/head/"
  cp -r "$PROTO_DIR" --parents "$tmp/bad/"
  f="$tmp/bad/$PROTO_DIR/gibson/world/v1/world.proto"
  grep -q 'string mission_id = 2;' "$f" || { log "FAIL: the fixture field is gone from world.proto; pick another"; exit 1; }
  sed -i '0,/string mission_id = 2;/s//string mission_id = 902;/' "$f"
  image "$tmp/head" "$tmp/head.binpb"
  image "$tmp/bad" "$tmp/bad.binpb"
  if compare "$tmp/head.binpb" "$tmp/head.binpb" >/dev/null 2>&1; then log "ok    an unchanged tree passes"
  else log "FAIL  an unchanged tree was refused"; exit 1; fi
  if out="$(compare "$tmp/bad.binpb" "$tmp/head.binpb" 2>&1)"; then
    log "FAIL  a renumbered field passed"; exit 1
  fi
  if [[ "$out" != *"mission_id"* ]]; then log "FAIL  a renumbered field failed for a different reason: $out"; exit 1; fi
  log "ok    a renumbered field is refused"
  log "SELFTEST PASSED"
  exit 0
fi

if git rev-parse --verify --quiet "refs/remotes/origin/$BASE" >/dev/null; then
  against="origin/$BASE"
else
  git fetch --no-tags --depth=1 origin "+refs/heads/$BASE:refs/remotes/origin/$BASE" >/dev/null
  against="origin/$BASE"
fi
git worktree add --detach -q "$tmp/base" "$against"
image "$ROOT" "$tmp/head.binpb"
image "$tmp/base" "$tmp/base.binpb"
log "comparing the daemon-local protos against $against (WIRE_JSON)"
if compare "$tmp/head.binpb" "$tmp/base.binpb"; then
  log "no breaking change"
else
  log "FAIL: a breaking change of the daemon-local wire (ADR-0028, rule 5). Add a field or a message, and reserve a number you retire."
  exit 1
fi
