#!/usr/bin/env bash
# toolhive-served-versions.sh — write the API versions that one release of the
# ToolHive CRD chart serves, for the version test of the connector operator
# (gibson#680, ADR-0114).
#
# The connector operator pins one ToolHive API version (toolhiveAPIVersion)
# and one chart version (toolhiveChartVersion). The test
# TestToolHiveAPIVersion_IsServedByThePinnedChart reads the file this script
# writes and fails when the chart does not serve the pinned version for each
# kind the operator creates. To move ToolHive, run this script with the new
# chart version, change the two constants, and let the test decide.
#
# Usage: bash scripts/toolhive-served-versions.sh <chart-version>
set -euo pipefail

version=${1:?usage: $0 <chart-version>}
out=operators/connector/internal/controller/testdata/toolhive-served-versions.yaml
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

helm pull oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds --version "$version" --untar --untardir "$tmp" >/dev/null
{
  echo "# Generated by scripts/toolhive-served-versions.sh $version. Do not edit."
  echo "chart: toolhive-operator-crds"
  echo "version: $version"
  echo "crds:"
  # Render the chart with its defaults, then keep the two kinds the operator
  # creates.
  helm template toolhive-crds "$tmp/toolhive-operator-crds" | python3 -c '
import sys, yaml
want = ["MCPServer", "MCPRemoteProxy"]
crds = {}
for d in yaml.safe_load_all(sys.stdin):
    if d and d.get("kind") == "CustomResourceDefinition":
        crds[d["spec"]["names"]["kind"]] = d["spec"]
for k in want:
    s = crds[k]
    print("  - kind: " + k)
    print("    group: " + s["group"])
    print("    served: [" + ", ".join(v["name"] for v in s["versions"] if v.get("served")) + "]")
    print("    storage: " + next(v["name"] for v in s["versions"] if v.get("storage")))
'
} > "$out"
echo "wrote $out"
