// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file in the repo root.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/tenant/v1/catalog_plugin.proto

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogPluginService_ListPluginCatalog_FullMethodName    = "/gibson.tenant.v1.CatalogPluginService/ListPluginCatalog"
	CatalogPluginService_EnableCatalogPlugin_FullMethodName  = "/gibson.tenant.v1.CatalogPluginService/EnableCatalogPlugin"
	CatalogPluginService_ListCatalogPlugins_FullMethodName   = "/gibson.tenant.v1.CatalogPluginService/ListCatalogPlugins"
	CatalogPluginService_DisableCatalogPlugin_FullMethodName = "/gibson.tenant.v1.CatalogPluginService/DisableCatalogPlugin"
)

// CatalogPluginServiceClient is the client API for CatalogPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CatalogPluginService is the API a tenant uses to enable a plugin of the
// platform catalog (gibson#815). The platform then runs one instance of the
// plugin for that tenant.
//
// The service records what the tenant wants. It starts nothing itself: the
// tenant operator reads the desired state from the daemon and converges the
// cluster to it.
type CatalogPluginServiceClient interface {
	// ListPluginCatalog returns the catalog plugins the tenant may enable.
	ListPluginCatalog(ctx context.Context, in *ListPluginCatalogRequest, opts ...grpc.CallOption) (*ListPluginCatalogResponse, error)
	// EnableCatalogPlugin records that the tenant wants one instance of the
	// plugin. A plugin the tenant already enabled answers ALREADY_EXISTS.
	EnableCatalogPlugin(ctx context.Context, in *EnableCatalogPluginRequest, opts ...grpc.CallOption) (*EnableCatalogPluginResponse, error)
	// ListCatalogPlugins returns the plugins the tenant enabled, with the
	// state the tenant operator last reported for each instance.
	ListCatalogPlugins(ctx context.Context, in *ListCatalogPluginsRequest, opts ...grpc.CallOption) (*ListCatalogPluginsResponse, error)
	// DisableCatalogPlugin removes the plugin from what the tenant wants. A
	// plugin the tenant did not enable answers NOT_FOUND.
	DisableCatalogPlugin(ctx context.Context, in *DisableCatalogPluginRequest, opts ...grpc.CallOption) (*DisableCatalogPluginResponse, error)
}

type catalogPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogPluginServiceClient(cc grpc.ClientConnInterface) CatalogPluginServiceClient {
	return &catalogPluginServiceClient{cc}
}

func (c *catalogPluginServiceClient) ListPluginCatalog(ctx context.Context, in *ListPluginCatalogRequest, opts ...grpc.CallOption) (*ListPluginCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginCatalogResponse)
	err := c.cc.Invoke(ctx, CatalogPluginService_ListPluginCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogPluginServiceClient) EnableCatalogPlugin(ctx context.Context, in *EnableCatalogPluginRequest, opts ...grpc.CallOption) (*EnableCatalogPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableCatalogPluginResponse)
	err := c.cc.Invoke(ctx, CatalogPluginService_EnableCatalogPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogPluginServiceClient) ListCatalogPlugins(ctx context.Context, in *ListCatalogPluginsRequest, opts ...grpc.CallOption) (*ListCatalogPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatalogPluginsResponse)
	err := c.cc.Invoke(ctx, CatalogPluginService_ListCatalogPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogPluginServiceClient) DisableCatalogPlugin(ctx context.Context, in *DisableCatalogPluginRequest, opts ...grpc.CallOption) (*DisableCatalogPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableCatalogPluginResponse)
	err := c.cc.Invoke(ctx, CatalogPluginService_DisableCatalogPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogPluginServiceServer is the server API for CatalogPluginService service.
// All implementations must embed UnimplementedCatalogPluginServiceServer
// for forward compatibility.
//
// CatalogPluginService is the API a tenant uses to enable a plugin of the
// platform catalog (gibson#815). The platform then runs one instance of the
// plugin for that tenant.
//
// The service records what the tenant wants. It starts nothing itself: the
// tenant operator reads the desired state from the daemon and converges the
// cluster to it.
type CatalogPluginServiceServer interface {
	// ListPluginCatalog returns the catalog plugins the tenant may enable.
	ListPluginCatalog(context.Context, *ListPluginCatalogRequest) (*ListPluginCatalogResponse, error)
	// EnableCatalogPlugin records that the tenant wants one instance of the
	// plugin. A plugin the tenant already enabled answers ALREADY_EXISTS.
	EnableCatalogPlugin(context.Context, *EnableCatalogPluginRequest) (*EnableCatalogPluginResponse, error)
	// ListCatalogPlugins returns the plugins the tenant enabled, with the
	// state the tenant operator last reported for each instance.
	ListCatalogPlugins(context.Context, *ListCatalogPluginsRequest) (*ListCatalogPluginsResponse, error)
	// DisableCatalogPlugin removes the plugin from what the tenant wants. A
	// plugin the tenant did not enable answers NOT_FOUND.
	DisableCatalogPlugin(context.Context, *DisableCatalogPluginRequest) (*DisableCatalogPluginResponse, error)
	mustEmbedUnimplementedCatalogPluginServiceServer()
}

// UnimplementedCatalogPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogPluginServiceServer struct{}

func (UnimplementedCatalogPluginServiceServer) ListPluginCatalog(context.Context, *ListPluginCatalogRequest) (*ListPluginCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPluginCatalog not implemented")
}
func (UnimplementedCatalogPluginServiceServer) EnableCatalogPlugin(context.Context, *EnableCatalogPluginRequest) (*EnableCatalogPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableCatalogPlugin not implemented")
}
func (UnimplementedCatalogPluginServiceServer) ListCatalogPlugins(context.Context, *ListCatalogPluginsRequest) (*ListCatalogPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCatalogPlugins not implemented")
}
func (UnimplementedCatalogPluginServiceServer) DisableCatalogPlugin(context.Context, *DisableCatalogPluginRequest) (*DisableCatalogPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableCatalogPlugin not implemented")
}
func (UnimplementedCatalogPluginServiceServer) mustEmbedUnimplementedCatalogPluginServiceServer() {}
func (UnimplementedCatalogPluginServiceServer) testEmbeddedByValue()                              {}

// UnsafeCatalogPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogPluginServiceServer will
// result in compilation errors.
type UnsafeCatalogPluginServiceServer interface {
	mustEmbedUnimplementedCatalogPluginServiceServer()
}

func RegisterCatalogPluginServiceServer(s grpc.ServiceRegistrar, srv CatalogPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogPluginService_ServiceDesc, srv)
}

func _CatalogPluginService_ListPluginCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServiceServer).ListPluginCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPluginService_ListPluginCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServiceServer).ListPluginCatalog(ctx, req.(*ListPluginCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogPluginService_EnableCatalogPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableCatalogPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServiceServer).EnableCatalogPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPluginService_EnableCatalogPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServiceServer).EnableCatalogPlugin(ctx, req.(*EnableCatalogPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogPluginService_ListCatalogPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServiceServer).ListCatalogPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPluginService_ListCatalogPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServiceServer).ListCatalogPlugins(ctx, req.(*ListCatalogPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogPluginService_DisableCatalogPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableCatalogPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogPluginServiceServer).DisableCatalogPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogPluginService_DisableCatalogPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogPluginServiceServer).DisableCatalogPlugin(ctx, req.(*DisableCatalogPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogPluginService_ServiceDesc is the grpc.ServiceDesc for CatalogPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.tenant.v1.CatalogPluginService",
	HandlerType: (*CatalogPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPluginCatalog",
			Handler:    _CatalogPluginService_ListPluginCatalog_Handler,
		},
		{
			MethodName: "EnableCatalogPlugin",
			Handler:    _CatalogPluginService_EnableCatalogPlugin_Handler,
		},
		{
			MethodName: "ListCatalogPlugins",
			Handler:    _CatalogPluginService_ListCatalogPlugins_Handler,
		},
		{
			MethodName: "DisableCatalogPlugin",
			Handler:    _CatalogPluginService_DisableCatalogPlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/tenant/v1/catalog_plugin.proto",
}
