// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/tenant/v1/grants.proto

// Package gibson.tenant.v1 — GrantsService: customer-callable capability-grant
// inspection and per-agent FGA-grant management surface. Moved from
// gibson.admin.v1.GrantsAdminService (platform-sdk) into the OSS SDK as part of
// the admin-surface-recategorization (ADR-0039 implementation).
//
// Authorization: every RPC carries a (gibson.auth.v1.authz) annotation.

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrantsService_ListActiveGrants_FullMethodName  = "/gibson.tenant.v1.GrantsService/ListActiveGrants"
	GrantsService_WriteAgentGrants_FullMethodName  = "/gibson.tenant.v1.GrantsService/WriteAgentGrants"
	GrantsService_DeleteAgentGrants_FullMethodName = "/gibson.tenant.v1.GrantsService/DeleteAgentGrants"
)

// GrantsServiceClient is the client API for GrantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GrantsService is the grants surface — both the CG-JWT inspector
// (ListActiveGrants) and the per-agent FGA-grant editor
// (WriteAgentGrants / DeleteAgentGrants).
type GrantsServiceClient interface {
	// ListActiveGrants returns active capability grants for the tenant
	// resolved from identity, optionally filtered by recipient class, RPC,
	// and expiry.
	ListActiveGrants(ctx context.Context, in *ListActiveGrantsRequest, opts ...grpc.CallOption) (*ListActiveGrantsResponse, error)
	// WriteAgentGrants additively writes per-action FGA tuples for a target
	// agent / tool principal. Idempotent: requesting an already present tuple
	// counts as `already_present` rather than failing. Each successful write
	// emits an `agent_grant_added` audit event.
	WriteAgentGrants(ctx context.Context, in *WriteAgentGrantsRequest, opts ...grpc.CallOption) (*WriteAgentGrantsResponse, error)
	// DeleteAgentGrants removes per-action FGA tuples. Idempotent: tuples not
	// present count as `not_present`. Each delete emits an `agent_grant_removed`
	// audit event.
	DeleteAgentGrants(ctx context.Context, in *DeleteAgentGrantsRequest, opts ...grpc.CallOption) (*DeleteAgentGrantsResponse, error)
}

type grantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrantsServiceClient(cc grpc.ClientConnInterface) GrantsServiceClient {
	return &grantsServiceClient{cc}
}

func (c *grantsServiceClient) ListActiveGrants(ctx context.Context, in *ListActiveGrantsRequest, opts ...grpc.CallOption) (*ListActiveGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveGrantsResponse)
	err := c.cc.Invoke(ctx, GrantsService_ListActiveGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grantsServiceClient) WriteAgentGrants(ctx context.Context, in *WriteAgentGrantsRequest, opts ...grpc.CallOption) (*WriteAgentGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAgentGrantsResponse)
	err := c.cc.Invoke(ctx, GrantsService_WriteAgentGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grantsServiceClient) DeleteAgentGrants(ctx context.Context, in *DeleteAgentGrantsRequest, opts ...grpc.CallOption) (*DeleteAgentGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentGrantsResponse)
	err := c.cc.Invoke(ctx, GrantsService_DeleteAgentGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrantsServiceServer is the server API for GrantsService service.
// All implementations must embed UnimplementedGrantsServiceServer
// for forward compatibility.
//
// GrantsService is the grants surface — both the CG-JWT inspector
// (ListActiveGrants) and the per-agent FGA-grant editor
// (WriteAgentGrants / DeleteAgentGrants).
type GrantsServiceServer interface {
	// ListActiveGrants returns active capability grants for the tenant
	// resolved from identity, optionally filtered by recipient class, RPC,
	// and expiry.
	ListActiveGrants(context.Context, *ListActiveGrantsRequest) (*ListActiveGrantsResponse, error)
	// WriteAgentGrants additively writes per-action FGA tuples for a target
	// agent / tool principal. Idempotent: requesting an already present tuple
	// counts as `already_present` rather than failing. Each successful write
	// emits an `agent_grant_added` audit event.
	WriteAgentGrants(context.Context, *WriteAgentGrantsRequest) (*WriteAgentGrantsResponse, error)
	// DeleteAgentGrants removes per-action FGA tuples. Idempotent: tuples not
	// present count as `not_present`. Each delete emits an `agent_grant_removed`
	// audit event.
	DeleteAgentGrants(context.Context, *DeleteAgentGrantsRequest) (*DeleteAgentGrantsResponse, error)
	mustEmbedUnimplementedGrantsServiceServer()
}

// UnimplementedGrantsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrantsServiceServer struct{}

func (UnimplementedGrantsServiceServer) ListActiveGrants(context.Context, *ListActiveGrantsRequest) (*ListActiveGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveGrants not implemented")
}
func (UnimplementedGrantsServiceServer) WriteAgentGrants(context.Context, *WriteAgentGrantsRequest) (*WriteAgentGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAgentGrants not implemented")
}
func (UnimplementedGrantsServiceServer) DeleteAgentGrants(context.Context, *DeleteAgentGrantsRequest) (*DeleteAgentGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgentGrants not implemented")
}
func (UnimplementedGrantsServiceServer) mustEmbedUnimplementedGrantsServiceServer() {}
func (UnimplementedGrantsServiceServer) testEmbeddedByValue()                       {}

// UnsafeGrantsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrantsServiceServer will
// result in compilation errors.
type UnsafeGrantsServiceServer interface {
	mustEmbedUnimplementedGrantsServiceServer()
}

func RegisterGrantsServiceServer(s grpc.ServiceRegistrar, srv GrantsServiceServer) {
	// If the following call panics, it indicates UnimplementedGrantsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrantsService_ServiceDesc, srv)
}

func _GrantsService_ListActiveGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantsServiceServer).ListActiveGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrantsService_ListActiveGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantsServiceServer).ListActiveGrants(ctx, req.(*ListActiveGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrantsService_WriteAgentGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAgentGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantsServiceServer).WriteAgentGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrantsService_WriteAgentGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantsServiceServer).WriteAgentGrants(ctx, req.(*WriteAgentGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrantsService_DeleteAgentGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantsServiceServer).DeleteAgentGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrantsService_DeleteAgentGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantsServiceServer).DeleteAgentGrants(ctx, req.(*DeleteAgentGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrantsService_ServiceDesc is the grpc.ServiceDesc for GrantsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrantsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.tenant.v1.GrantsService",
	HandlerType: (*GrantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListActiveGrants",
			Handler:    _GrantsService_ListActiveGrants_Handler,
		},
		{
			MethodName: "WriteAgentGrants",
			Handler:    _GrantsService_WriteAgentGrants_Handler,
		},
		{
			MethodName: "DeleteAgentGrants",
			Handler:    _GrantsService_DeleteAgentGrants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/tenant/v1/grants.proto",
}
