// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/tenant/v1/membership.proto

// Package gibson.tenant.v1 — MembershipService: customer-callable tenant
// membership and team management surface. Moved from the PRIVATE
// gibson.admin.v1.TenantAdminService (platform-sdk) into the OSS SDK
// as part of the admin-surface-recategorization (ADR-0039 implementation).
//
// These RPCs are customer-callable because tenant owners and admins
// regularly manage their team memberships and access controls via the
// dashboard and ADK CLI. They are gated by the FGA "admin" relation —
// meaning the calling user must be a tenant admin — which is a
// per-resource permission level, not an operator privilege.
//
// Authorization: every RPC carries a (gibson.auth.v1.authz) annotation.
// Broker-config RPCs (GetBrokerConfig, ProbeBrokerConfig, SetBrokerConfig,
// CountSecrets) remain in gibson.admin.v1.TenantAdminService (platform-sdk)
// as they are genuinely internal-only operations.

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipService_ListMembers_FullMethodName               = "/gibson.tenant.v1.MembershipService/ListMembers"
	MembershipService_SetTenantRole_FullMethodName             = "/gibson.tenant.v1.MembershipService/SetTenantRole"
	MembershipService_TransferOwnership_FullMethodName         = "/gibson.tenant.v1.MembershipService/TransferOwnership"
	MembershipService_InviteMember_FullMethodName              = "/gibson.tenant.v1.MembershipService/InviteMember"
	MembershipService_AcceptInvitation_FullMethodName          = "/gibson.tenant.v1.MembershipService/AcceptInvitation"
	MembershipService_ResendInvitation_FullMethodName          = "/gibson.tenant.v1.MembershipService/ResendInvitation"
	MembershipService_CancelInvitation_FullMethodName          = "/gibson.tenant.v1.MembershipService/CancelInvitation"
	MembershipService_ListTeams_FullMethodName                 = "/gibson.tenant.v1.MembershipService/ListTeams"
	MembershipService_CreateTeam_FullMethodName                = "/gibson.tenant.v1.MembershipService/CreateTeam"
	MembershipService_DeleteTeam_FullMethodName                = "/gibson.tenant.v1.MembershipService/DeleteTeam"
	MembershipService_ListTeamMembers_FullMethodName           = "/gibson.tenant.v1.MembershipService/ListTeamMembers"
	MembershipService_AddTeamMember_FullMethodName             = "/gibson.tenant.v1.MembershipService/AddTeamMember"
	MembershipService_RemoveTeamMember_FullMethodName          = "/gibson.tenant.v1.MembershipService/RemoveTeamMember"
	MembershipService_SetTeamAdmin_FullMethodName              = "/gibson.tenant.v1.MembershipService/SetTeamAdmin"
	MembershipService_SetComponentAccess_FullMethodName        = "/gibson.tenant.v1.MembershipService/SetComponentAccess"
	MembershipService_GrantComponentPermissions_FullMethodName = "/gibson.tenant.v1.MembershipService/GrantComponentPermissions"
	MembershipService_SetCatalogEnabled_FullMethodName         = "/gibson.tenant.v1.MembershipService/SetCatalogEnabled"
	MembershipService_SetCatalogPublished_FullMethodName       = "/gibson.tenant.v1.MembershipService/SetCatalogPublished"
	MembershipService_GetReservedNames_FullMethodName          = "/gibson.tenant.v1.MembershipService/GetReservedNames"
)

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MembershipService manages tenant members, teams, roles, and component access
// controls.
type MembershipServiceClient interface {
	// ListMembers enumerates the members of the caller's tenant with
	// human-readable names and email addresses.
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// SetTenantRole writes or removes admin / member / writer FGA tuples on
	// the tenant for a given user. The role field must be one of "admin",
	// "member", or "writer". Atomically removes any conflicting prior role
	// tuple before writing the new one.
	SetTenantRole(ctx context.Context, in *SetTenantRoleRequest, opts ...grpc.CallOption) (*SetTenantRoleResponse, error)
	// TransferOwnership atomically swaps the owner FGA tuple on the tenant
	// from the current owner to new_owner_user_id. Fails if the caller is
	// not the current owner.
	TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error)
	// InviteMember creates a pending invitation for an email address with the
	// given tenant role and emails the invitee an accept link. The invitee
	// appears in ListMembers with status "invited" until they accept. Idempotent:
	// re-inviting the same email refreshes the pending invitation.
	InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error)
	// AcceptInvitation redeems an invitation token: it provisions the IdP user
	// (if new) and projects full membership (FGA tuple + per-tenant org
	// membership), transitioning the member to "active". The token is the
	// capability, so this RPC is unauthenticated (the invitee is not yet a
	// member of any tenant) — exactly like GetSignupProgress.
	AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*AcceptInvitationResponse, error)
	// ResendInvitation re-sends the invitation email for a pending invitation
	// without creating a duplicate.
	ResendInvitation(ctx context.Context, in *ResendInvitationRequest, opts ...grpc.CallOption) (*ResendInvitationResponse, error)
	// CancelInvitation cancels a pending invitation so it can no longer be
	// accepted.
	CancelInvitation(ctx context.Context, in *CancelInvitationRequest, opts ...grpc.CallOption) (*CancelInvitationResponse, error)
	// ListTeams enumerates the teams in the caller's tenant. Backed by FGA
	// ListObjects(tenant:X, parent, team). Each Team carries its display name
	// and current member count.
	ListTeams(ctx context.Context, in *ListTeamsRequest, opts ...grpc.CallOption) (*ListTeamsResponse, error)
	// CreateTeam creates a new team under the caller's tenant and writes the
	// (tenant:X, parent, team:Y) FGA tuple.
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
	// DeleteTeam removes a team and all its member/admin FGA tuples.
	DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error)
	// ListTeamMembers enumerates the members of a single team. is_admin
	// reflects whether the user holds the team's admin relation.
	ListTeamMembers(ctx context.Context, in *ListTeamMembersRequest, opts ...grpc.CallOption) (*ListTeamMembersResponse, error)
	// AddTeamMember adds a user to a team with the member relation.
	AddTeamMember(ctx context.Context, in *AddTeamMemberRequest, opts ...grpc.CallOption) (*AddTeamMemberResponse, error)
	// RemoveTeamMember removes a user from a team, deleting both member and
	// admin FGA tuples for that user on the team.
	RemoveTeamMember(ctx context.Context, in *RemoveTeamMemberRequest, opts ...grpc.CallOption) (*RemoveTeamMemberResponse, error)
	// SetTeamAdmin promotes or demotes a team member's admin status. When
	// is_admin is true, the admin relation is added (member relation kept for
	// backward compat); when false, the admin relation is removed.
	SetTeamAdmin(ctx context.Context, in *SetTeamAdminRequest, opts ...grpc.CallOption) (*SetTeamAdminResponse, error)
	// SetComponentAccess writes team_read_disabled / team_write_disabled /
	// team_execute_disabled FGA tuples for a component. Replaces the current
	// tuple-set atomically; any existing access tuples for the component are
	// deleted before the new set is written.
	SetComponentAccess(ctx context.Context, in *SetComponentAccessRequest, opts ...grpc.CallOption) (*SetComponentAccessResponse, error)
	// GrantComponentPermissions records the agent installation's approved
	// component capabilities. The server enforces caller-access intersection:
	// only capabilities the caller already holds (component_read/write/execute_enabled)
	// may be granted. Writes component_*_enabled FGA tuples for the agent
	// installation principal.
	GrantComponentPermissions(ctx context.Context, in *GrantComponentPermissionsRequest, opts ...grpc.CallOption) (*GrantComponentPermissionsResponse, error)
	// SetCatalogEnabled adds or removes a component from the calling tenant's
	// catalog by writing or deleting the FGA tenant_enabled tuple for the
	// (tenant, component) pair. This is the daemon-side replacement for the
	// dashboard's previous direct ComponentGrant CRD write (ADR-0041 remaining
	// gap — catalog-enablement routing through the daemon).
	//
	// When enabled is true the relation is written (idempotent if already
	// present). When enabled is false the relation is deleted (idempotent if
	// already absent).
	//
	// The component_ref must be a fully-qualified component object key of the
	// form "<kind>-<name>" (e.g. "tool-nmap", "agent-recon"). The daemon
	// normalises to "component:<component_ref>" before writing to FGA.
	//
	// Authorization: tenant admin. Only a tenant admin may modify which
	// components are available in their tenant's catalog.
	SetCatalogEnabled(ctx context.Context, in *SetCatalogEnabledRequest, opts ...grpc.CallOption) (*SetCatalogEnabledResponse, error)
	// SetCatalogPublished writes or deletes the FGA tenant_published tuple for a
	// component owned by the caller's tenant — the bring-your-own (BYO)
	// connector path (gibson#683). Publishing makes the tenant's own connector
	// available to enable within that tenant (org+ plans only); it never exposes
	// the component to other tenants. tenant_published ("this tenant owns/offers
	// it") is distinct from tenant_enabled ("this tenant has it switched on").
	SetCatalogPublished(ctx context.Context, in *SetCatalogPublishedRequest, opts ...grpc.CallOption) (*SetCatalogPublishedResponse, error)
	// GetReservedNames returns the chart-managed reserved-names denylist
	// (exact + prefix matches) used by the Tenant CRD admission webhook and
	// the dashboard signup form. Callable without authentication — the list is
	// public and contains no tenant data.
	GetReservedNames(ctx context.Context, in *GetReservedNamesRequest, opts ...grpc.CallOption) (*GetReservedNamesResponse, error)
}

type membershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipServiceClient(cc grpc.ClientConnInterface) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, MembershipService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) SetTenantRole(ctx context.Context, in *SetTenantRoleRequest, opts ...grpc.CallOption) (*SetTenantRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTenantRoleResponse)
	err := c.cc.Invoke(ctx, MembershipService_SetTenantRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_TransferOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberResponse)
	err := c.cc.Invoke(ctx, MembershipService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*AcceptInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptInvitationResponse)
	err := c.cc.Invoke(ctx, MembershipService_AcceptInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) ResendInvitation(ctx context.Context, in *ResendInvitationRequest, opts ...grpc.CallOption) (*ResendInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendInvitationResponse)
	err := c.cc.Invoke(ctx, MembershipService_ResendInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CancelInvitation(ctx context.Context, in *CancelInvitationRequest, opts ...grpc.CallOption) (*CancelInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInvitationResponse)
	err := c.cc.Invoke(ctx, MembershipService_CancelInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) ListTeams(ctx context.Context, in *ListTeamsRequest, opts ...grpc.CallOption) (*ListTeamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamsResponse)
	err := c.cc.Invoke(ctx, MembershipService_ListTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamResponse)
	err := c.cc.Invoke(ctx, MembershipService_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) DeleteTeam(ctx context.Context, in *DeleteTeamRequest, opts ...grpc.CallOption) (*DeleteTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTeamResponse)
	err := c.cc.Invoke(ctx, MembershipService_DeleteTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) ListTeamMembers(ctx context.Context, in *ListTeamMembersRequest, opts ...grpc.CallOption) (*ListTeamMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamMembersResponse)
	err := c.cc.Invoke(ctx, MembershipService_ListTeamMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) AddTeamMember(ctx context.Context, in *AddTeamMemberRequest, opts ...grpc.CallOption) (*AddTeamMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTeamMemberResponse)
	err := c.cc.Invoke(ctx, MembershipService_AddTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) RemoveTeamMember(ctx context.Context, in *RemoveTeamMemberRequest, opts ...grpc.CallOption) (*RemoveTeamMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTeamMemberResponse)
	err := c.cc.Invoke(ctx, MembershipService_RemoveTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) SetTeamAdmin(ctx context.Context, in *SetTeamAdminRequest, opts ...grpc.CallOption) (*SetTeamAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTeamAdminResponse)
	err := c.cc.Invoke(ctx, MembershipService_SetTeamAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) SetComponentAccess(ctx context.Context, in *SetComponentAccessRequest, opts ...grpc.CallOption) (*SetComponentAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetComponentAccessResponse)
	err := c.cc.Invoke(ctx, MembershipService_SetComponentAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GrantComponentPermissions(ctx context.Context, in *GrantComponentPermissionsRequest, opts ...grpc.CallOption) (*GrantComponentPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantComponentPermissionsResponse)
	err := c.cc.Invoke(ctx, MembershipService_GrantComponentPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) SetCatalogEnabled(ctx context.Context, in *SetCatalogEnabledRequest, opts ...grpc.CallOption) (*SetCatalogEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCatalogEnabledResponse)
	err := c.cc.Invoke(ctx, MembershipService_SetCatalogEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) SetCatalogPublished(ctx context.Context, in *SetCatalogPublishedRequest, opts ...grpc.CallOption) (*SetCatalogPublishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCatalogPublishedResponse)
	err := c.cc.Invoke(ctx, MembershipService_SetCatalogPublished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetReservedNames(ctx context.Context, in *GetReservedNamesRequest, opts ...grpc.CallOption) (*GetReservedNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReservedNamesResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetReservedNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
// All implementations must embed UnimplementedMembershipServiceServer
// for forward compatibility.
//
// MembershipService manages tenant members, teams, roles, and component access
// controls.
type MembershipServiceServer interface {
	// ListMembers enumerates the members of the caller's tenant with
	// human-readable names and email addresses.
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	// SetTenantRole writes or removes admin / member / writer FGA tuples on
	// the tenant for a given user. The role field must be one of "admin",
	// "member", or "writer". Atomically removes any conflicting prior role
	// tuple before writing the new one.
	SetTenantRole(context.Context, *SetTenantRoleRequest) (*SetTenantRoleResponse, error)
	// TransferOwnership atomically swaps the owner FGA tuple on the tenant
	// from the current owner to new_owner_user_id. Fails if the caller is
	// not the current owner.
	TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error)
	// InviteMember creates a pending invitation for an email address with the
	// given tenant role and emails the invitee an accept link. The invitee
	// appears in ListMembers with status "invited" until they accept. Idempotent:
	// re-inviting the same email refreshes the pending invitation.
	InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error)
	// AcceptInvitation redeems an invitation token: it provisions the IdP user
	// (if new) and projects full membership (FGA tuple + per-tenant org
	// membership), transitioning the member to "active". The token is the
	// capability, so this RPC is unauthenticated (the invitee is not yet a
	// member of any tenant) — exactly like GetSignupProgress.
	AcceptInvitation(context.Context, *AcceptInvitationRequest) (*AcceptInvitationResponse, error)
	// ResendInvitation re-sends the invitation email for a pending invitation
	// without creating a duplicate.
	ResendInvitation(context.Context, *ResendInvitationRequest) (*ResendInvitationResponse, error)
	// CancelInvitation cancels a pending invitation so it can no longer be
	// accepted.
	CancelInvitation(context.Context, *CancelInvitationRequest) (*CancelInvitationResponse, error)
	// ListTeams enumerates the teams in the caller's tenant. Backed by FGA
	// ListObjects(tenant:X, parent, team). Each Team carries its display name
	// and current member count.
	ListTeams(context.Context, *ListTeamsRequest) (*ListTeamsResponse, error)
	// CreateTeam creates a new team under the caller's tenant and writes the
	// (tenant:X, parent, team:Y) FGA tuple.
	CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error)
	// DeleteTeam removes a team and all its member/admin FGA tuples.
	DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error)
	// ListTeamMembers enumerates the members of a single team. is_admin
	// reflects whether the user holds the team's admin relation.
	ListTeamMembers(context.Context, *ListTeamMembersRequest) (*ListTeamMembersResponse, error)
	// AddTeamMember adds a user to a team with the member relation.
	AddTeamMember(context.Context, *AddTeamMemberRequest) (*AddTeamMemberResponse, error)
	// RemoveTeamMember removes a user from a team, deleting both member and
	// admin FGA tuples for that user on the team.
	RemoveTeamMember(context.Context, *RemoveTeamMemberRequest) (*RemoveTeamMemberResponse, error)
	// SetTeamAdmin promotes or demotes a team member's admin status. When
	// is_admin is true, the admin relation is added (member relation kept for
	// backward compat); when false, the admin relation is removed.
	SetTeamAdmin(context.Context, *SetTeamAdminRequest) (*SetTeamAdminResponse, error)
	// SetComponentAccess writes team_read_disabled / team_write_disabled /
	// team_execute_disabled FGA tuples for a component. Replaces the current
	// tuple-set atomically; any existing access tuples for the component are
	// deleted before the new set is written.
	SetComponentAccess(context.Context, *SetComponentAccessRequest) (*SetComponentAccessResponse, error)
	// GrantComponentPermissions records the agent installation's approved
	// component capabilities. The server enforces caller-access intersection:
	// only capabilities the caller already holds (component_read/write/execute_enabled)
	// may be granted. Writes component_*_enabled FGA tuples for the agent
	// installation principal.
	GrantComponentPermissions(context.Context, *GrantComponentPermissionsRequest) (*GrantComponentPermissionsResponse, error)
	// SetCatalogEnabled adds or removes a component from the calling tenant's
	// catalog by writing or deleting the FGA tenant_enabled tuple for the
	// (tenant, component) pair. This is the daemon-side replacement for the
	// dashboard's previous direct ComponentGrant CRD write (ADR-0041 remaining
	// gap — catalog-enablement routing through the daemon).
	//
	// When enabled is true the relation is written (idempotent if already
	// present). When enabled is false the relation is deleted (idempotent if
	// already absent).
	//
	// The component_ref must be a fully-qualified component object key of the
	// form "<kind>-<name>" (e.g. "tool-nmap", "agent-recon"). The daemon
	// normalises to "component:<component_ref>" before writing to FGA.
	//
	// Authorization: tenant admin. Only a tenant admin may modify which
	// components are available in their tenant's catalog.
	SetCatalogEnabled(context.Context, *SetCatalogEnabledRequest) (*SetCatalogEnabledResponse, error)
	// SetCatalogPublished writes or deletes the FGA tenant_published tuple for a
	// component owned by the caller's tenant — the bring-your-own (BYO)
	// connector path (gibson#683). Publishing makes the tenant's own connector
	// available to enable within that tenant (org+ plans only); it never exposes
	// the component to other tenants. tenant_published ("this tenant owns/offers
	// it") is distinct from tenant_enabled ("this tenant has it switched on").
	SetCatalogPublished(context.Context, *SetCatalogPublishedRequest) (*SetCatalogPublishedResponse, error)
	// GetReservedNames returns the chart-managed reserved-names denylist
	// (exact + prefix matches) used by the Tenant CRD admission webhook and
	// the dashboard signup form. Callable without authentication — the list is
	// public and contains no tenant data.
	GetReservedNames(context.Context, *GetReservedNamesRequest) (*GetReservedNamesResponse, error)
	mustEmbedUnimplementedMembershipServiceServer()
}

// UnimplementedMembershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServiceServer struct{}

func (UnimplementedMembershipServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedMembershipServiceServer) SetTenantRole(context.Context, *SetTenantRoleRequest) (*SetTenantRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTenantRole not implemented")
}
func (UnimplementedMembershipServiceServer) TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedMembershipServiceServer) InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedMembershipServiceServer) AcceptInvitation(context.Context, *AcceptInvitationRequest) (*AcceptInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptInvitation not implemented")
}
func (UnimplementedMembershipServiceServer) ResendInvitation(context.Context, *ResendInvitationRequest) (*ResendInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendInvitation not implemented")
}
func (UnimplementedMembershipServiceServer) CancelInvitation(context.Context, *CancelInvitationRequest) (*CancelInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInvitation not implemented")
}
func (UnimplementedMembershipServiceServer) ListTeams(context.Context, *ListTeamsRequest) (*ListTeamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeams not implemented")
}
func (UnimplementedMembershipServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedMembershipServiceServer) DeleteTeam(context.Context, *DeleteTeamRequest) (*DeleteTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (UnimplementedMembershipServiceServer) ListTeamMembers(context.Context, *ListTeamMembersRequest) (*ListTeamMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeamMembers not implemented")
}
func (UnimplementedMembershipServiceServer) AddTeamMember(context.Context, *AddTeamMemberRequest) (*AddTeamMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTeamMember not implemented")
}
func (UnimplementedMembershipServiceServer) RemoveTeamMember(context.Context, *RemoveTeamMemberRequest) (*RemoveTeamMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTeamMember not implemented")
}
func (UnimplementedMembershipServiceServer) SetTeamAdmin(context.Context, *SetTeamAdminRequest) (*SetTeamAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTeamAdmin not implemented")
}
func (UnimplementedMembershipServiceServer) SetComponentAccess(context.Context, *SetComponentAccessRequest) (*SetComponentAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetComponentAccess not implemented")
}
func (UnimplementedMembershipServiceServer) GrantComponentPermissions(context.Context, *GrantComponentPermissionsRequest) (*GrantComponentPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantComponentPermissions not implemented")
}
func (UnimplementedMembershipServiceServer) SetCatalogEnabled(context.Context, *SetCatalogEnabledRequest) (*SetCatalogEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCatalogEnabled not implemented")
}
func (UnimplementedMembershipServiceServer) SetCatalogPublished(context.Context, *SetCatalogPublishedRequest) (*SetCatalogPublishedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCatalogPublished not implemented")
}
func (UnimplementedMembershipServiceServer) GetReservedNames(context.Context, *GetReservedNamesRequest) (*GetReservedNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReservedNames not implemented")
}
func (UnimplementedMembershipServiceServer) mustEmbedUnimplementedMembershipServiceServer() {}
func (UnimplementedMembershipServiceServer) testEmbeddedByValue()                           {}

// UnsafeMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServiceServer will
// result in compilation errors.
type UnsafeMembershipServiceServer interface {
	mustEmbedUnimplementedMembershipServiceServer()
}

func RegisterMembershipServiceServer(s grpc.ServiceRegistrar, srv MembershipServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipService_ServiceDesc, srv)
}

func _MembershipService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_SetTenantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTenantRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).SetTenantRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_SetTenantRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).SetTenantRole(ctx, req.(*SetTenantRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).TransferOwnership(ctx, req.(*TransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).InviteMember(ctx, req.(*InviteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_AcceptInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).AcceptInvitation(ctx, req.(*AcceptInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_ResendInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ResendInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ResendInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ResendInvitation(ctx, req.(*ResendInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CancelInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CancelInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CancelInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CancelInvitation(ctx, req.(*CancelInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_ListTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ListTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ListTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ListTeams(ctx, req.(*ListTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_DeleteTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).DeleteTeam(ctx, req.(*DeleteTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_ListTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ListTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ListTeamMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ListTeamMembers(ctx, req.(*ListTeamMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_AddTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).AddTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_AddTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).AddTeamMember(ctx, req.(*AddTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_RemoveTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).RemoveTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_RemoveTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).RemoveTeamMember(ctx, req.(*RemoveTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_SetTeamAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTeamAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).SetTeamAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_SetTeamAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).SetTeamAdmin(ctx, req.(*SetTeamAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_SetComponentAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetComponentAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).SetComponentAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_SetComponentAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).SetComponentAccess(ctx, req.(*SetComponentAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GrantComponentPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantComponentPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GrantComponentPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GrantComponentPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GrantComponentPermissions(ctx, req.(*GrantComponentPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_SetCatalogEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCatalogEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).SetCatalogEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_SetCatalogEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).SetCatalogEnabled(ctx, req.(*SetCatalogEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_SetCatalogPublished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCatalogPublishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).SetCatalogPublished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_SetCatalogPublished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).SetCatalogPublished(ctx, req.(*SetCatalogPublishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetReservedNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservedNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetReservedNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetReservedNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetReservedNames(ctx, req.(*GetReservedNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipService_ServiceDesc is the grpc.ServiceDesc for MembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.tenant.v1.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMembers",
			Handler:    _MembershipService_ListMembers_Handler,
		},
		{
			MethodName: "SetTenantRole",
			Handler:    _MembershipService_SetTenantRole_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _MembershipService_TransferOwnership_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _MembershipService_InviteMember_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _MembershipService_AcceptInvitation_Handler,
		},
		{
			MethodName: "ResendInvitation",
			Handler:    _MembershipService_ResendInvitation_Handler,
		},
		{
			MethodName: "CancelInvitation",
			Handler:    _MembershipService_CancelInvitation_Handler,
		},
		{
			MethodName: "ListTeams",
			Handler:    _MembershipService_ListTeams_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _MembershipService_CreateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _MembershipService_DeleteTeam_Handler,
		},
		{
			MethodName: "ListTeamMembers",
			Handler:    _MembershipService_ListTeamMembers_Handler,
		},
		{
			MethodName: "AddTeamMember",
			Handler:    _MembershipService_AddTeamMember_Handler,
		},
		{
			MethodName: "RemoveTeamMember",
			Handler:    _MembershipService_RemoveTeamMember_Handler,
		},
		{
			MethodName: "SetTeamAdmin",
			Handler:    _MembershipService_SetTeamAdmin_Handler,
		},
		{
			MethodName: "SetComponentAccess",
			Handler:    _MembershipService_SetComponentAccess_Handler,
		},
		{
			MethodName: "GrantComponentPermissions",
			Handler:    _MembershipService_GrantComponentPermissions_Handler,
		},
		{
			MethodName: "SetCatalogEnabled",
			Handler:    _MembershipService_SetCatalogEnabled_Handler,
		},
		{
			MethodName: "SetCatalogPublished",
			Handler:    _MembershipService_SetCatalogPublished_Handler,
		},
		{
			MethodName: "GetReservedNames",
			Handler:    _MembershipService_GetReservedNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/tenant/v1/membership.proto",
}
