// Use of this source code is governed by the Elastic License 2.0
// that can be found in the LICENSE file in the repo root.

// OntologyExtensionService is the tenant-OWNER-facing approval surface for
// agent-proposed Taxonomy extensions (ADR-0024 §2, ADR-0033 decisions 2-3,
// gibson#392).
//
// An agent proposes a new Taxonomy node label or relationship type it
// discovers at runtime via ProposeOntologyExtension (gibson#391, the
// agent-facing HarnessCallbackService RPC in the OSS SDK). That proposal is
// folded into the caller's tenant World as a pending sighting and counted
// for recurrence by taxonomy.PromotionGate — it is NEVER auto-promoted
// (ADR-0033 decision 3).
//
// This service is the other end of that pipeline: the tenant owner reviews
// every pending proposal (ListOntologyExtensionProposals) and explicitly
// approves or rejects one. Approval runs the human-in-the-loop half of
// taxonomy.PromotionGate's settlement rule; once BOTH halves are satisfied
// (the proposal has recurred enough independent times, AND the owner
// approved it), the label is promoted into live, per-tenant, replayable
// Cypher structure immediately — the tenant's own taxonomy extension, visible
// to every mission in that tenant from then on. Rejection is a terminal
// decision recorded for audit; it never mutates the Taxonomy.
//
// Gated strictly to the tenant's OWNER relation (not "admin"): ADR-0033
// decision 3 calls for "explicit tenant-owner approval" specifically — one
// step stronger than the "tenant admin" gate DomainPackService's
// EnableDomainPack uses for already-curated catalog content. A proposal
// reviewed here is NOVEL, agent-discovered structure the platform has never
// seen before; only the tenant's Owner may admit it.
//
// Authorization: every RPC carries a (gibson.auth.v1.authz) annotation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/tenant/v1/ontology_extension.proto

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OntologyExtensionService_ListOntologyExtensionProposals_FullMethodName   = "/gibson.tenant.v1.OntologyExtensionService/ListOntologyExtensionProposals"
	OntologyExtensionService_ApproveOntologyExtensionProposal_FullMethodName = "/gibson.tenant.v1.OntologyExtensionService/ApproveOntologyExtensionProposal"
	OntologyExtensionService_RejectOntologyExtensionProposal_FullMethodName  = "/gibson.tenant.v1.OntologyExtensionService/RejectOntologyExtensionProposal"
)

// OntologyExtensionServiceClient is the client API for OntologyExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OntologyExtensionServiceClient interface {
	// ListOntologyExtensionProposals returns every ontology/taxonomy extension
	// proposal this tenant's agents have made, pending and decided alike, so
	// the tenant owner (or an admin assisting them) has full visibility into
	// what agents are proposing (ADR-0033's "the tenant owner seeing every
	// proposal").
	ListOntologyExtensionProposals(ctx context.Context, in *ListOntologyExtensionProposalsRequest, opts ...grpc.CallOption) (*ListOntologyExtensionProposalsResponse, error)
	// ApproveOntologyExtensionProposal is the tenant owner's explicit approval
	// of a pending proposal (ADR-0033 decision 3). Refused (NOT_FOUND) if
	// (kind, label) names no proposal ever observed in this tenant, and
	// (FAILED_PRECONDITION) if it already carries a terminal decision.
	//
	// Gated to "owner", not "admin": this is the stronger, singular
	// tenant-owner sign-off ADR-0033 decision 3 requires — not a routine
	// admin action any delegated admin may take.
	ApproveOntologyExtensionProposal(ctx context.Context, in *ApproveOntologyExtensionProposalRequest, opts ...grpc.CallOption) (*ApproveOntologyExtensionProposalResponse, error)
	// RejectOntologyExtensionProposal is the tenant owner's explicit rejection
	// of a pending proposal. Same refusal rules as
	// ApproveOntologyExtensionProposal, and the same "owner" gate.
	RejectOntologyExtensionProposal(ctx context.Context, in *RejectOntologyExtensionProposalRequest, opts ...grpc.CallOption) (*RejectOntologyExtensionProposalResponse, error)
}

type ontologyExtensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOntologyExtensionServiceClient(cc grpc.ClientConnInterface) OntologyExtensionServiceClient {
	return &ontologyExtensionServiceClient{cc}
}

func (c *ontologyExtensionServiceClient) ListOntologyExtensionProposals(ctx context.Context, in *ListOntologyExtensionProposalsRequest, opts ...grpc.CallOption) (*ListOntologyExtensionProposalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOntologyExtensionProposalsResponse)
	err := c.cc.Invoke(ctx, OntologyExtensionService_ListOntologyExtensionProposals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyExtensionServiceClient) ApproveOntologyExtensionProposal(ctx context.Context, in *ApproveOntologyExtensionProposalRequest, opts ...grpc.CallOption) (*ApproveOntologyExtensionProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveOntologyExtensionProposalResponse)
	err := c.cc.Invoke(ctx, OntologyExtensionService_ApproveOntologyExtensionProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ontologyExtensionServiceClient) RejectOntologyExtensionProposal(ctx context.Context, in *RejectOntologyExtensionProposalRequest, opts ...grpc.CallOption) (*RejectOntologyExtensionProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectOntologyExtensionProposalResponse)
	err := c.cc.Invoke(ctx, OntologyExtensionService_RejectOntologyExtensionProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OntologyExtensionServiceServer is the server API for OntologyExtensionService service.
// All implementations must embed UnimplementedOntologyExtensionServiceServer
// for forward compatibility.
type OntologyExtensionServiceServer interface {
	// ListOntologyExtensionProposals returns every ontology/taxonomy extension
	// proposal this tenant's agents have made, pending and decided alike, so
	// the tenant owner (or an admin assisting them) has full visibility into
	// what agents are proposing (ADR-0033's "the tenant owner seeing every
	// proposal").
	ListOntologyExtensionProposals(context.Context, *ListOntologyExtensionProposalsRequest) (*ListOntologyExtensionProposalsResponse, error)
	// ApproveOntologyExtensionProposal is the tenant owner's explicit approval
	// of a pending proposal (ADR-0033 decision 3). Refused (NOT_FOUND) if
	// (kind, label) names no proposal ever observed in this tenant, and
	// (FAILED_PRECONDITION) if it already carries a terminal decision.
	//
	// Gated to "owner", not "admin": this is the stronger, singular
	// tenant-owner sign-off ADR-0033 decision 3 requires — not a routine
	// admin action any delegated admin may take.
	ApproveOntologyExtensionProposal(context.Context, *ApproveOntologyExtensionProposalRequest) (*ApproveOntologyExtensionProposalResponse, error)
	// RejectOntologyExtensionProposal is the tenant owner's explicit rejection
	// of a pending proposal. Same refusal rules as
	// ApproveOntologyExtensionProposal, and the same "owner" gate.
	RejectOntologyExtensionProposal(context.Context, *RejectOntologyExtensionProposalRequest) (*RejectOntologyExtensionProposalResponse, error)
	mustEmbedUnimplementedOntologyExtensionServiceServer()
}

// UnimplementedOntologyExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOntologyExtensionServiceServer struct{}

func (UnimplementedOntologyExtensionServiceServer) ListOntologyExtensionProposals(context.Context, *ListOntologyExtensionProposalsRequest) (*ListOntologyExtensionProposalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOntologyExtensionProposals not implemented")
}
func (UnimplementedOntologyExtensionServiceServer) ApproveOntologyExtensionProposal(context.Context, *ApproveOntologyExtensionProposalRequest) (*ApproveOntologyExtensionProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveOntologyExtensionProposal not implemented")
}
func (UnimplementedOntologyExtensionServiceServer) RejectOntologyExtensionProposal(context.Context, *RejectOntologyExtensionProposalRequest) (*RejectOntologyExtensionProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectOntologyExtensionProposal not implemented")
}
func (UnimplementedOntologyExtensionServiceServer) mustEmbedUnimplementedOntologyExtensionServiceServer() {
}
func (UnimplementedOntologyExtensionServiceServer) testEmbeddedByValue() {}

// UnsafeOntologyExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OntologyExtensionServiceServer will
// result in compilation errors.
type UnsafeOntologyExtensionServiceServer interface {
	mustEmbedUnimplementedOntologyExtensionServiceServer()
}

func RegisterOntologyExtensionServiceServer(s grpc.ServiceRegistrar, srv OntologyExtensionServiceServer) {
	// If the following call panics, it indicates UnimplementedOntologyExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OntologyExtensionService_ServiceDesc, srv)
}

func _OntologyExtensionService_ListOntologyExtensionProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOntologyExtensionProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyExtensionServiceServer).ListOntologyExtensionProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OntologyExtensionService_ListOntologyExtensionProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyExtensionServiceServer).ListOntologyExtensionProposals(ctx, req.(*ListOntologyExtensionProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OntologyExtensionService_ApproveOntologyExtensionProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveOntologyExtensionProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyExtensionServiceServer).ApproveOntologyExtensionProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OntologyExtensionService_ApproveOntologyExtensionProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyExtensionServiceServer).ApproveOntologyExtensionProposal(ctx, req.(*ApproveOntologyExtensionProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OntologyExtensionService_RejectOntologyExtensionProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectOntologyExtensionProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OntologyExtensionServiceServer).RejectOntologyExtensionProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OntologyExtensionService_RejectOntologyExtensionProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OntologyExtensionServiceServer).RejectOntologyExtensionProposal(ctx, req.(*RejectOntologyExtensionProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OntologyExtensionService_ServiceDesc is the grpc.ServiceDesc for OntologyExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OntologyExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.tenant.v1.OntologyExtensionService",
	HandlerType: (*OntologyExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOntologyExtensionProposals",
			Handler:    _OntologyExtensionService_ListOntologyExtensionProposals_Handler,
		},
		{
			MethodName: "ApproveOntologyExtensionProposal",
			Handler:    _OntologyExtensionService_ApproveOntologyExtensionProposal_Handler,
		},
		{
			MethodName: "RejectOntologyExtensionProposal",
			Handler:    _OntologyExtensionService_RejectOntologyExtensionProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/tenant/v1/ontology_extension.proto",
}
