// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/tenant/v1/provider.proto

// Package gibson.tenant.v1 — ProviderService: customer-callable LLM provider
// management surface. Consolidated from the existing TenantService provider
// RPCs and ProbeProvider from gibson.admin.v1.TenantAdminService (platform-sdk).
//
// Part of the admin-surface-recategorization (ADR-0039 implementation).
//
// Deduplication notes:
//   - GetSupportedProviders, ListProviderModels already existed in TenantService;
//     the platform-sdk admin/v1/tenant.proto duplicates are dropped.
//   - ProbeProvider is new: moved from platform-sdk TenantAdminService.
//   - CredentialField, ModelDescriptor, SupportedProvider message definitions are
//     the richer tenant.proto versions (include CredentialFieldType enum); the
//     admin/v1 versions are superseded.
//
// Authorization: every RPC carries a (gibson.auth.v1.authz) annotation.

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_ListProviders_FullMethodName         = "/gibson.tenant.v1.ProviderService/ListProviders"
	ProviderService_GetProvider_FullMethodName           = "/gibson.tenant.v1.ProviderService/GetProvider"
	ProviderService_CreateProvider_FullMethodName        = "/gibson.tenant.v1.ProviderService/CreateProvider"
	ProviderService_UpdateProvider_FullMethodName        = "/gibson.tenant.v1.ProviderService/UpdateProvider"
	ProviderService_DeleteProvider_FullMethodName        = "/gibson.tenant.v1.ProviderService/DeleteProvider"
	ProviderService_TestProvider_FullMethodName          = "/gibson.tenant.v1.ProviderService/TestProvider"
	ProviderService_GetSupportedProviders_FullMethodName = "/gibson.tenant.v1.ProviderService/GetSupportedProviders"
	ProviderService_ProbeProvider_FullMethodName         = "/gibson.tenant.v1.ProviderService/ProbeProvider"
	ProviderService_ListProviderModels_FullMethodName    = "/gibson.tenant.v1.ProviderService/ListProviderModels"
	ProviderService_GetProviderHealth_FullMethodName     = "/gibson.tenant.v1.ProviderService/GetProviderHealth"
	ProviderService_GetDefaultProvider_FullMethodName    = "/gibson.tenant.v1.ProviderService/GetDefaultProvider"
	ProviderService_SetDefaultProvider_FullMethodName    = "/gibson.tenant.v1.ProviderService/SetDefaultProvider"
	ProviderService_ExecuteLLM_FullMethodName            = "/gibson.tenant.v1.ProviderService/ExecuteLLM"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderService manages LLM provider configurations for a tenant.
type ProviderServiceClient interface {
	// ListProviders returns all provider configs for the calling tenant.
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	// GetProvider returns a single provider config by name.
	GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*GetProviderResponse, error)
	// CreateProvider encrypts and stores a new provider config.
	CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error)
	// UpdateProvider replaces an existing provider config.
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error)
	// DeleteProvider removes a provider config from the store.
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error)
	// TestProvider validates a proposed provider config by making a minimal live
	// request.
	TestProvider(ctx context.Context, in *TestProviderRequest, opts ...grpc.CallOption) (*TestProviderResponse, error)
	// GetSupportedProviders returns the daemon's static catalogue of LLM provider
	// types with their per-provider credential field schemas.
	GetSupportedProviders(ctx context.Context, in *GetSupportedProvidersRequest, opts ...grpc.CallOption) (*GetSupportedProvidersResponse, error)
	// ProbeProvider validates candidate provider credentials WITHOUT persisting
	// them, and returns the live model catalogue the provider's API exposes for
	// those credentials. Used by the wizard's "Test connection" step.
	//
	// SECURITY: credentials transit memory only — they are passed to the
	// transient provider client, the call is made, and the values are dropped
	// when the request returns. They are never logged, never persisted, and
	// never returned to the caller.
	//
	// Source: previously ProbeProvider in gibson.admin.v1.TenantAdminService
	// (platform-sdk); moved here as it is customer-callable.
	ProbeProvider(ctx context.Context, in *ProbeProviderRequest, opts ...grpc.CallOption) (*ProbeProviderResponse, error)
	// ListProviderModels fetches the live model catalogue for an already-
	// configured provider, looked up by name. Credentials are read from the
	// encrypted store; the caller does not pass them.
	ListProviderModels(ctx context.Context, in *ListProviderModelsRequest, opts ...grpc.CallOption) (*ListProviderModelsResponse, error)
	// GetProviderHealth returns the last-known health status of a stored provider.
	GetProviderHealth(ctx context.Context, in *GetProviderHealthRequest, opts ...grpc.CallOption) (*GetProviderHealthResponse, error)
	// GetDefaultProvider returns the tenant's currently configured default provider.
	GetDefaultProvider(ctx context.Context, in *GetDefaultProviderRequest, opts ...grpc.CallOption) (*GetDefaultProviderResponse, error)
	// SetDefaultProvider designates an existing stored provider as the default.
	SetDefaultProvider(ctx context.Context, in *SetDefaultProviderRequest, opts ...grpc.CallOption) (*SetDefaultProviderResponse, error)
	// ExecuteLLM proxies a single (non-streaming) LLM completion.
	ExecuteLLM(ctx context.Context, in *ExecuteLLMRequest, opts ...grpc.CallOption) (*ExecuteLLMResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*GetProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_CreateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_DeleteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) TestProvider(ctx context.Context, in *TestProviderRequest, opts ...grpc.CallOption) (*TestProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_TestProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetSupportedProviders(ctx context.Context, in *GetSupportedProvidersRequest, opts ...grpc.CallOption) (*GetSupportedProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedProvidersResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetSupportedProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProbeProvider(ctx context.Context, in *ProbeProviderRequest, opts ...grpc.CallOption) (*ProbeProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_ProbeProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListProviderModels(ctx context.Context, in *ListProviderModelsRequest, opts ...grpc.CallOption) (*ListProviderModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProviderModelsResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListProviderModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetProviderHealth(ctx context.Context, in *GetProviderHealthRequest, opts ...grpc.CallOption) (*GetProviderHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderHealthResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetProviderHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetDefaultProvider(ctx context.Context, in *GetDefaultProviderRequest, opts ...grpc.CallOption) (*GetDefaultProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetDefaultProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SetDefaultProvider(ctx context.Context, in *SetDefaultProviderRequest, opts ...grpc.CallOption) (*SetDefaultProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_SetDefaultProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ExecuteLLM(ctx context.Context, in *ExecuteLLMRequest, opts ...grpc.CallOption) (*ExecuteLLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteLLMResponse)
	err := c.cc.Invoke(ctx, ProviderService_ExecuteLLM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// ProviderService manages LLM provider configurations for a tenant.
type ProviderServiceServer interface {
	// ListProviders returns all provider configs for the calling tenant.
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	// GetProvider returns a single provider config by name.
	GetProvider(context.Context, *GetProviderRequest) (*GetProviderResponse, error)
	// CreateProvider encrypts and stores a new provider config.
	CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error)
	// UpdateProvider replaces an existing provider config.
	UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error)
	// DeleteProvider removes a provider config from the store.
	DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error)
	// TestProvider validates a proposed provider config by making a minimal live
	// request.
	TestProvider(context.Context, *TestProviderRequest) (*TestProviderResponse, error)
	// GetSupportedProviders returns the daemon's static catalogue of LLM provider
	// types with their per-provider credential field schemas.
	GetSupportedProviders(context.Context, *GetSupportedProvidersRequest) (*GetSupportedProvidersResponse, error)
	// ProbeProvider validates candidate provider credentials WITHOUT persisting
	// them, and returns the live model catalogue the provider's API exposes for
	// those credentials. Used by the wizard's "Test connection" step.
	//
	// SECURITY: credentials transit memory only — they are passed to the
	// transient provider client, the call is made, and the values are dropped
	// when the request returns. They are never logged, never persisted, and
	// never returned to the caller.
	//
	// Source: previously ProbeProvider in gibson.admin.v1.TenantAdminService
	// (platform-sdk); moved here as it is customer-callable.
	ProbeProvider(context.Context, *ProbeProviderRequest) (*ProbeProviderResponse, error)
	// ListProviderModels fetches the live model catalogue for an already-
	// configured provider, looked up by name. Credentials are read from the
	// encrypted store; the caller does not pass them.
	ListProviderModels(context.Context, *ListProviderModelsRequest) (*ListProviderModelsResponse, error)
	// GetProviderHealth returns the last-known health status of a stored provider.
	GetProviderHealth(context.Context, *GetProviderHealthRequest) (*GetProviderHealthResponse, error)
	// GetDefaultProvider returns the tenant's currently configured default provider.
	GetDefaultProvider(context.Context, *GetDefaultProviderRequest) (*GetDefaultProviderResponse, error)
	// SetDefaultProvider designates an existing stored provider as the default.
	SetDefaultProvider(context.Context, *SetDefaultProviderRequest) (*SetDefaultProviderResponse, error)
	// ExecuteLLM proxies a single (non-streaming) LLM completion.
	ExecuteLLM(context.Context, *ExecuteLLMRequest) (*ExecuteLLMResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedProviderServiceServer) GetProvider(context.Context, *GetProviderRequest) (*GetProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedProviderServiceServer) CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedProviderServiceServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedProviderServiceServer) DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedProviderServiceServer) TestProvider(context.Context, *TestProviderRequest) (*TestProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestProvider not implemented")
}
func (UnimplementedProviderServiceServer) GetSupportedProviders(context.Context, *GetSupportedProvidersRequest) (*GetSupportedProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedProviders not implemented")
}
func (UnimplementedProviderServiceServer) ProbeProvider(context.Context, *ProbeProviderRequest) (*ProbeProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeProvider not implemented")
}
func (UnimplementedProviderServiceServer) ListProviderModels(context.Context, *ListProviderModelsRequest) (*ListProviderModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviderModels not implemented")
}
func (UnimplementedProviderServiceServer) GetProviderHealth(context.Context, *GetProviderHealthRequest) (*GetProviderHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderHealth not implemented")
}
func (UnimplementedProviderServiceServer) GetDefaultProvider(context.Context, *GetDefaultProviderRequest) (*GetDefaultProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaultProvider not implemented")
}
func (UnimplementedProviderServiceServer) SetDefaultProvider(context.Context, *SetDefaultProviderRequest) (*SetDefaultProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultProvider not implemented")
}
func (UnimplementedProviderServiceServer) ExecuteLLM(context.Context, *ExecuteLLMRequest) (*ExecuteLLMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteLLM not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetProvider(ctx, req.(*GetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_CreateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CreateProvider(ctx, req.(*CreateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_DeleteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).DeleteProvider(ctx, req.(*DeleteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_TestProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).TestProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_TestProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).TestProvider(ctx, req.(*TestProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetSupportedProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetSupportedProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetSupportedProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetSupportedProviders(ctx, req.(*GetSupportedProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProbeProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProbeProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ProbeProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProbeProvider(ctx, req.(*ProbeProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListProviderModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListProviderModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListProviderModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListProviderModels(ctx, req.(*ListProviderModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetProviderHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetProviderHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetProviderHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetProviderHealth(ctx, req.(*GetProviderHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetDefaultProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetDefaultProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetDefaultProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetDefaultProvider(ctx, req.(*GetDefaultProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SetDefaultProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SetDefaultProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SetDefaultProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SetDefaultProvider(ctx, req.(*SetDefaultProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ExecuteLLM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteLLMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ExecuteLLM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ExecuteLLM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ExecuteLLM(ctx, req.(*ExecuteLLMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.tenant.v1.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _ProviderService_ListProviders_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _ProviderService_GetProvider_Handler,
		},
		{
			MethodName: "CreateProvider",
			Handler:    _ProviderService_CreateProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _ProviderService_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _ProviderService_DeleteProvider_Handler,
		},
		{
			MethodName: "TestProvider",
			Handler:    _ProviderService_TestProvider_Handler,
		},
		{
			MethodName: "GetSupportedProviders",
			Handler:    _ProviderService_GetSupportedProviders_Handler,
		},
		{
			MethodName: "ProbeProvider",
			Handler:    _ProviderService_ProbeProvider_Handler,
		},
		{
			MethodName: "ListProviderModels",
			Handler:    _ProviderService_ListProviderModels_Handler,
		},
		{
			MethodName: "GetProviderHealth",
			Handler:    _ProviderService_GetProviderHealth_Handler,
		},
		{
			MethodName: "GetDefaultProvider",
			Handler:    _ProviderService_GetDefaultProvider_Handler,
		},
		{
			MethodName: "SetDefaultProvider",
			Handler:    _ProviderService_SetDefaultProvider_Handler,
		},
		{
			MethodName: "ExecuteLLM",
			Handler:    _ProviderService_ExecuteLLM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/tenant/v1/provider.proto",
}
