// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/tenant/v1/signup.proto

// Package gibson.tenant.v1 — SignupService: server-side tenant provisioning for
// self-serve signup (E9, gibson#812, ADR-0043/0044).
//
// Before E9 the dashboard provisioned a tenant during signup by (a) holding a
// privileged Zitadel "signup-bot" IAM PAT to create the Zitadel org/user and
// (b) writing the Tenant / TenantMember Kubernetes CRs directly with its
// in-cluster ServiceAccount. That gave the web tier two broad, standing
// privileges (IdP admin + cluster write) purely to bootstrap a tenant.
//
// SignupService.Signup collapses that privilege: the dashboard makes ONE
// unauthenticated RPC carrying the founding-owner email, workspace name, and
// plan tier, and the DAEMON performs the provisioning. The daemon does NOT add
// a parallel Zitadel-admin write codepath — it provisions by creating and
// owning the Tenant custom resource, which the gibson-tenant-operator already
// reconciles into the per-tenant Zitadel org (TenantIdentity, gibson#803),
// secrets backend, FGA grants, and data plane via its ordered sub-CRD chain
// (gibson#805). One provisioning path (ADR-0027), operator-owned.
//
// Once a customer is on this RPC the dashboard no longer needs the signup-bot
// IAM PAT or cluster write access — that removal is dashboard#812 / dashboard#813.
//
// Authorization: Signup is UNAUTHENTICATED. It runs before any tenant or
// membership exists, so there is no principal to FGA-check (exactly like
// SetSignupProgress on UserService). The opaque attempt_id UUID is the
// correlation capability; the daemon validates and rate-limits the request and
// is the sole holder of the cluster-write privilege.

package tenantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignupService_Signup_FullMethodName = "/gibson.tenant.v1.SignupService/Signup"
)

// SignupServiceClient is the client API for SignupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SignupService provisions a new tenant from a self-serve signup request.
//
// It is the server-side replacement for the dashboard's privileged signup
// path: the dashboard calls Signup instead of holding a Zitadel admin PAT and
// writing Tenant/TenantMember CRs itself.
type SignupServiceClient interface {
	// Signup provisions a tenant for a self-serve signup attempt.
	//
	// The daemon creates (and owns) the Tenant CR with the supplied owner email,
	// workspace display name, and plan tier; the gibson-tenant-operator then
	// reconciles it into the Zitadel org + secrets + grants + data plane. The RPC
	// returns as soon as the Tenant CR is accepted (create-and-return); the
	// caller polls provisioning progress via UserService.GetSignupProgress
	// (keyed by the same attempt_id) and/or the tenant's readiness signals.
	//
	// Idempotent on attempt_id + tenant slug: re-issuing the same signup (e.g. a
	// client retry) returns the existing tenant rather than failing, so a dropped
	// response does not strand a half-provisioned tenant.
	//
	// UNAUTHENTICATED: runs before any tenant/membership exists. The attempt_id
	// UUID is the capability; the daemon is the sole holder of the provisioning
	// privilege (no IdP PAT or cluster write in the caller).
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
}

type signupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignupServiceClient(cc grpc.ClientConnInterface) SignupServiceClient {
	return &signupServiceClient{cc}
}

func (c *signupServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, SignupService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupServiceServer is the server API for SignupService service.
// All implementations must embed UnimplementedSignupServiceServer
// for forward compatibility.
//
// SignupService provisions a new tenant from a self-serve signup request.
//
// It is the server-side replacement for the dashboard's privileged signup
// path: the dashboard calls Signup instead of holding a Zitadel admin PAT and
// writing Tenant/TenantMember CRs itself.
type SignupServiceServer interface {
	// Signup provisions a tenant for a self-serve signup attempt.
	//
	// The daemon creates (and owns) the Tenant CR with the supplied owner email,
	// workspace display name, and plan tier; the gibson-tenant-operator then
	// reconciles it into the Zitadel org + secrets + grants + data plane. The RPC
	// returns as soon as the Tenant CR is accepted (create-and-return); the
	// caller polls provisioning progress via UserService.GetSignupProgress
	// (keyed by the same attempt_id) and/or the tenant's readiness signals.
	//
	// Idempotent on attempt_id + tenant slug: re-issuing the same signup (e.g. a
	// client retry) returns the existing tenant rather than failing, so a dropped
	// response does not strand a half-provisioned tenant.
	//
	// UNAUTHENTICATED: runs before any tenant/membership exists. The attempt_id
	// UUID is the capability; the daemon is the sole holder of the provisioning
	// privilege (no IdP PAT or cluster write in the caller).
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	mustEmbedUnimplementedSignupServiceServer()
}

// UnimplementedSignupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignupServiceServer struct{}

func (UnimplementedSignupServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedSignupServiceServer) mustEmbedUnimplementedSignupServiceServer() {}
func (UnimplementedSignupServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignupServiceServer will
// result in compilation errors.
type UnsafeSignupServiceServer interface {
	mustEmbedUnimplementedSignupServiceServer()
}

func RegisterSignupServiceServer(s grpc.ServiceRegistrar, srv SignupServiceServer) {
	// If the following call panics, it indicates UnimplementedSignupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignupService_ServiceDesc, srv)
}

func _SignupService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignupService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignupService_ServiceDesc is the grpc.ServiceDesc for SignupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.tenant.v1.SignupService",
	HandlerType: (*SignupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _SignupService_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/tenant/v1/signup.proto",
}
