// Command envreaders writes and checks configs/env-readers.txt, the set of
// environment variable names the gibson source can read.
//
// It is the producer half of ADR-0094 layer 2 (charts#303). The chart injects
// env vars into containers whose source lives here, and its merge gate fails
// when it injects a name that is absent from this set. The chart vendors the
// file, so the set must come from the repository that owns the readers.
//
// The set over-approximates on purpose. It holds every env-shaped token in
// every string literal, and every env-shaped selector, in every tracked Go
// file that is not a test. It does not list helpers. A list of os.Getenv,
// envOr, envBool and envInt found 20 of the 27 names cmd/ext-authz reads,
// because seven go through durationOr and intOr. A set that MISSES a name
// makes the chart gate report a live env var as dead, and deleting one of
// those boots a pod with an empty value. A set with a name too many only
// hides one dead env var.
//
// A name in a comment is not a reader. A name in a test file is not a reader.
//
// Usage:
//
//	envreaders -dir <repo root> -write   refresh configs/env-readers.txt
//	envreaders -dir <repo root> -check   exit 1 when the file is stale
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/scanner"
	"go/token"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Artifact is the committed reader set, relative to the repository root.
const Artifact = "configs/env-readers.txt"

// MinFiles and MinNames refuse a scan that read almost nothing. A wrong
// working directory or an empty checkout must not write an empty set.
const (
	MinFiles = 200
	MinNames = 100
)

const header = `# env-readers.txt — GENERATED by tools/envreaders. Do not hand-edit.
# Refresh with ` + "`make env-readers`" + `. ` + "`make check-env-readers`" + ` fails when it is stale.
#
# Every environment variable name the gibson source can read (ADR-0094
# layer 2, charts#303). The set over-approximates: it holds every env-shaped
# token in a string literal and every env-shaped selector, from every tracked
# Go file that is not a test. zeroroot-ai/charts vendors this file.
`

var (
	envToken = regexp.MustCompile(`[A-Z][A-Z0-9_]{2,}`)
	envIdent = regexp.MustCompile(`^[A-Z][A-Z0-9_]{2,}$`)
)

func isWord(b byte) bool {
	return b == '_' || (b >= '0' && b <= '9') || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}

// NamesInSource returns the env-shaped names one Go source file can read.
func NamesInSource(filename string, src []byte) map[string]bool {
	out := map[string]bool{}
	fset := token.NewFileSet()
	file := fset.AddFile(filename, fset.Base(), len(src))
	var s scanner.Scanner
	// Comments are not scanned: a name in a comment is not a reader.
	s.Init(file, src, func(token.Position, string) {}, 0)
	prev := token.ILLEGAL
	for {
		_, tok, lit := s.Scan()
		if tok == token.EOF {
			break
		}
		switch tok {
		case token.STRING, token.CHAR:
			for _, loc := range envToken.FindAllStringIndex(lit, -1) {
				// A whole word only: FOO in "xFOO_BARy" is not a name.
				if loc[0] > 0 && isWord(lit[loc[0]-1]) {
					continue
				}
				if loc[1] < len(lit) && isWord(lit[loc[1]]) {
					continue
				}
				out[lit[loc[0]:loc[1]]] = true
			}
		case token.IDENT:
			if prev == token.PERIOD && envIdent.MatchString(lit) {
				out[lit] = true
			}
		}
		prev = tok
	}
	return out
}

// trackedGoFiles lists the Go files git tracks under dir that are not tests,
// vendored code or test data. Tracked files only: CI checks sibling
// repositories out inside the tree, and those are not this repository.
func trackedGoFiles(dir string) ([]string, error) {
	cmd := exec.Command("git", "-C", dir, "ls-files", "-z", "--", "*.go")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	raw, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files in %s: %w: %s", dir, err, strings.TrimSpace(stderr.String()))
	}
	var files []string
	for _, f := range strings.Split(string(raw), "\x00") {
		if f == "" || strings.HasSuffix(f, "_test.go") {
			continue
		}
		skip := false
		for _, part := range strings.Split(filepath.ToSlash(filepath.Dir(f)), "/") {
			if part == "testdata" || part == "vendor" {
				skip = true
			}
		}
		if !skip {
			files = append(files, f)
		}
	}
	return files, nil
}

// Scan returns the sorted reader set of the repository at dir.
func Scan(dir string, minFiles, minNames int) ([]string, error) {
	files, err := trackedGoFiles(dir)
	if err != nil {
		return nil, err
	}
	if len(files) < minFiles {
		return nil, fmt.Errorf("scanned %d Go file(s) in %s, the floor is %d: this is not the gibson tree", len(files), dir, minFiles)
	}
	set := map[string]bool{}
	for _, f := range files {
		src, err := os.ReadFile(filepath.Join(dir, f))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", f, err)
		}
		for n := range NamesInSource(f, src) {
			set[n] = true
		}
	}
	if len(set) < minNames {
		return nil, fmt.Errorf("found %d name(s) in %d file(s), the floor is %d: the scan read nothing", len(set), len(files), minNames)
	}
	names := make([]string, 0, len(set))
	for n := range set {
		names = append(names, n)
	}
	sort.Strings(names)
	return names, nil
}

// Render is the artifact text for a reader set.
func Render(names []string) string {
	return header + strings.Join(names, "\n") + "\n"
}

// Parse reads the names out of artifact text.
func Parse(text string) []string {
	var names []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		names = append(names, line)
	}
	return names
}

// Drift compares the committed set with the scanned set.
func Drift(committed, scanned []string) (missing, stale []string) {
	have := map[string]bool{}
	for _, n := range committed {
		have[n] = true
	}
	want := map[string]bool{}
	for _, n := range scanned {
		want[n] = true
		if !have[n] {
			missing = append(missing, n)
		}
	}
	for _, n := range committed {
		if !want[n] {
			stale = append(stale, n)
		}
	}
	return missing, stale
}

func run(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("envreaders", flag.ContinueOnError)
	fs.SetOutput(stderr)
	dir := fs.String("dir", ".", "repository root")
	write := fs.Bool("write", false, "refresh "+Artifact)
	check := fs.Bool("check", false, "exit 1 when "+Artifact+" is stale")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *write == *check {
		fmt.Fprintln(stderr, "envreaders: give exactly one of -write and -check")
		return 2
	}
	names, err := Scan(*dir, MinFiles, MinNames)
	if err != nil {
		fmt.Fprintln(stderr, "envreaders:", err)
		return 2
	}
	path := filepath.Join(*dir, Artifact)
	if *write {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(stderr, "envreaders:", err)
			return 2
		}
		if err := os.WriteFile(path, []byte(Render(names)), 0o644); err != nil {
			fmt.Fprintln(stderr, "envreaders:", err)
			return 2
		}
		fmt.Fprintf(stdout, "wrote %s (%d names)\n", Artifact, len(names))
		return 0
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(stderr, "envreaders: %s is missing. Run `make env-readers`.\n", Artifact)
		return 1
	}
	missing, stale := Drift(Parse(string(raw)), names)
	if len(missing) == 0 && len(stale) == 0 && string(raw) == Render(names) {
		fmt.Fprintf(stdout, "ok  %s matches the source (%d names)\n", Artifact, len(names))
		return 0
	}
	for _, n := range missing {
		fmt.Fprintf(stderr, "envreaders: the source reads %s and %s does not list it\n", n, Artifact)
	}
	for _, n := range stale {
		fmt.Fprintf(stderr, "envreaders: %s lists %s and the source no longer reads it\n", Artifact, n)
	}
	fmt.Fprintf(stderr, "envreaders: %s is stale. Run `make env-readers` and commit the result.\n", Artifact)
	return 1
}

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }
