// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gibson/platform/v1/dispatch_override.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DispatchOverrideService_OverrideDispatchPolicy_FullMethodName = "/gibson.platform.v1.DispatchOverrideService/OverrideDispatchPolicy"
)

// DispatchOverrideServiceClient is the client API for DispatchOverrideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DispatchOverrideService is a daemon-local platform-operator escape hatch
// that lets a platform operator temporarily allow PLUGIN/AGENT dispatch for
// UNTRUSTED-content components on a named tenant when Setec is degraded
// (R3.4 of the setec-sandbox-prod-default spec).
//
// Authorization is gated on the `platform_operator` FGA relation against
// `system_tenant:_system` — the design's `can_override_policy` semantic
// is implied by `platform_operator` (the FGA model intentionally does not
// introduce a separate relation for this; the design's §C4 explicitly notes
// "no model changes; can_override_policy already implied by platform_operator").
//
// Server-side enforcement (see the handler in
// `core/gibson/internal/daemon/dispatch_override.go`):
//   - `ttl_seconds` is clamped to `min(req.ttl_seconds, 3600)` (1-hour upper bound).
//   - `reason` is mandatory; empty reason returns InvalidArgument.
//   - The override record is persisted in Redis with the absolute expiry; a
//     daemon restart does not silently extend an active override.
//   - Every override emits a synchronous audit event (`audit.WriteSync`) with
//     the operator's Zitadel `sub` (sourced from the `x-gibson-user-id` header
//     forwarded by ext-authz), the affected tenant, the clamped TTL, and the
//     reason text — the RPC reply is not sent until the audit write is acked.
type DispatchOverrideServiceClient interface {
	// OverrideDispatchPolicy creates a time-bounded override that flips the
	// dispatch policy gate's deny-on-UNTRUSTED+PLUGIN/AGENT outcome to allow
	// for the given tenant. The override auto-evicts at TTL expiry; clients
	// can re-issue the call to extend (each extension emits its own audit event).
	OverrideDispatchPolicy(ctx context.Context, in *OverrideDispatchPolicyRequest, opts ...grpc.CallOption) (*OverrideDispatchPolicyResponse, error)
}

type dispatchOverrideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchOverrideServiceClient(cc grpc.ClientConnInterface) DispatchOverrideServiceClient {
	return &dispatchOverrideServiceClient{cc}
}

func (c *dispatchOverrideServiceClient) OverrideDispatchPolicy(ctx context.Context, in *OverrideDispatchPolicyRequest, opts ...grpc.CallOption) (*OverrideDispatchPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverrideDispatchPolicyResponse)
	err := c.cc.Invoke(ctx, DispatchOverrideService_OverrideDispatchPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchOverrideServiceServer is the server API for DispatchOverrideService service.
// All implementations must embed UnimplementedDispatchOverrideServiceServer
// for forward compatibility.
//
// DispatchOverrideService is a daemon-local platform-operator escape hatch
// that lets a platform operator temporarily allow PLUGIN/AGENT dispatch for
// UNTRUSTED-content components on a named tenant when Setec is degraded
// (R3.4 of the setec-sandbox-prod-default spec).
//
// Authorization is gated on the `platform_operator` FGA relation against
// `system_tenant:_system` — the design's `can_override_policy` semantic
// is implied by `platform_operator` (the FGA model intentionally does not
// introduce a separate relation for this; the design's §C4 explicitly notes
// "no model changes; can_override_policy already implied by platform_operator").
//
// Server-side enforcement (see the handler in
// `core/gibson/internal/daemon/dispatch_override.go`):
//   - `ttl_seconds` is clamped to `min(req.ttl_seconds, 3600)` (1-hour upper bound).
//   - `reason` is mandatory; empty reason returns InvalidArgument.
//   - The override record is persisted in Redis with the absolute expiry; a
//     daemon restart does not silently extend an active override.
//   - Every override emits a synchronous audit event (`audit.WriteSync`) with
//     the operator's Zitadel `sub` (sourced from the `x-gibson-user-id` header
//     forwarded by ext-authz), the affected tenant, the clamped TTL, and the
//     reason text — the RPC reply is not sent until the audit write is acked.
type DispatchOverrideServiceServer interface {
	// OverrideDispatchPolicy creates a time-bounded override that flips the
	// dispatch policy gate's deny-on-UNTRUSTED+PLUGIN/AGENT outcome to allow
	// for the given tenant. The override auto-evicts at TTL expiry; clients
	// can re-issue the call to extend (each extension emits its own audit event).
	OverrideDispatchPolicy(context.Context, *OverrideDispatchPolicyRequest) (*OverrideDispatchPolicyResponse, error)
	mustEmbedUnimplementedDispatchOverrideServiceServer()
}

// UnimplementedDispatchOverrideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchOverrideServiceServer struct{}

func (UnimplementedDispatchOverrideServiceServer) OverrideDispatchPolicy(context.Context, *OverrideDispatchPolicyRequest) (*OverrideDispatchPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OverrideDispatchPolicy not implemented")
}
func (UnimplementedDispatchOverrideServiceServer) mustEmbedUnimplementedDispatchOverrideServiceServer() {
}
func (UnimplementedDispatchOverrideServiceServer) testEmbeddedByValue() {}

// UnsafeDispatchOverrideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchOverrideServiceServer will
// result in compilation errors.
type UnsafeDispatchOverrideServiceServer interface {
	mustEmbedUnimplementedDispatchOverrideServiceServer()
}

func RegisterDispatchOverrideServiceServer(s grpc.ServiceRegistrar, srv DispatchOverrideServiceServer) {
	// If the following call panics, it indicates UnimplementedDispatchOverrideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DispatchOverrideService_ServiceDesc, srv)
}

func _DispatchOverrideService_OverrideDispatchPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverrideDispatchPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchOverrideServiceServer).OverrideDispatchPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DispatchOverrideService_OverrideDispatchPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchOverrideServiceServer).OverrideDispatchPolicy(ctx, req.(*OverrideDispatchPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DispatchOverrideService_ServiceDesc is the grpc.ServiceDesc for DispatchOverrideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DispatchOverrideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gibson.platform.v1.DispatchOverrideService",
	HandlerType: (*DispatchOverrideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OverrideDispatchPolicy",
			Handler:    _DispatchOverrideService_OverrideDispatchPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gibson/platform/v1/dispatch_override.proto",
}
